// =============================================================================
// PROCESSOS ADICIONAIS DA PLATAFORMA PAGSMILE — 29-37
// Dashboards, Analytics, Notificações, Taxas, Helena IA, Messages, Docs, Config
// =============================================================================

export const PROCESSOS_EXTRA = [

  // ═══════════════════════════════════════════════════════════════════════════
  // 29. DASHBOARD CEO (VISÃO ESTRATÉGICA)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-029',
    nome: 'Dashboard CEO — Visão Estratégica da Operação',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'CEO / Gestão / Comercial',
    objetivo: 'Definir a composição e funcionalidades do Dashboard CEO para visão executiva da operação, assegurando:',
    objetivoItens: [
      'KPIs macro: leads totais, propostas, contratos, TPV pipeline, receita estimada.',
      'Visão de funil (CEOFunnelOverview): conversão lead→proposta→aceite→compliance→contrato com taxas % entre etapas.',
      'Performance por vendedor (SellerPerformanceTable): leads, propostas, contratos, receita por comercial, ranking ordenável.',
      'Tendências temporais (CEOTrendChart): evolução de leads, propostas e contratos por período com múltiplas séries.',
      'Visão de compliance (CEOComplianceOverview): casos por status (Pendente, Em Processamento, Aprovado, Manual, Recusado), taxa de aprovação automática vs manual, distribuição por subfaixa v4.',
      'Contratos (CEOContractsOverview): contratos assinados vs pendentes vs cancelados, receita confirmada, TPV contratado.',
      'Produtividade do time (TeamProductivityPanel): tempo médio por etapa (lead→contato: Xh, contato→proposta: Xd, proposta→aceite: Xd, aceite→contrato: Xd).',
    ],
    escopoInclui: [
      'CEOKPICards: 6 cartões — Leads (total + variação), Propostas (enviadas + aceitas), Contratos (assinados), TPV Pipeline (R$), Receita Estimada (R$), Taxa Conversão (%). Cada card mostra variação % vs período anterior.',
      'CEOFunnelOverview: gráfico de funil (recharts) — barras horizontais com contagem e % de conversão entre etapas.',
      'SellerPerformanceTable: tabela com colunas — Vendedor, Leads, Propostas Enviadas, Aceitas, Contratos, TPV Total, Receita. Ordenável por qualquer coluna.',
      'CEOTrendChart: gráfico de linha — eixo X (tempo), séries: leads criados, propostas enviadas, contratos assinados. Granularidade: dia/semana/mês.',
      'CEOComplianceOverview: 2 gráficos — pizza de status + barras de subfaixas v4 (1A-5).',
      'CEOContractsOverview: KPIs de contratos + gráfico de evolução mensal.',
      'TeamProductivityPanel: tempo médio por etapa do funil (calculado via diff de datas).',
      'Filtro de período: 7d, 30d, 90d, 12m, all — aplica-se a todos os painéis.',
    ],
    escopoNaoInclui: [
      'Dashboard Comercial operacional (ver PROC-030).',
      'Dados & Insights analíticos avançados (ver PROC-031).',
    ],
    steps: [
      { id: '01', resp: 'CEO/Admin', atividade: 'Acessa DashboardCEO no menu principal (seção Leads & Propostas)', decisao: '', gate: '', sla: '', saida: 'Dashboard carregado com dados do período selecionado (default: 30d)', proximo: '02' },
      { id: '02', resp: 'Sistema', atividade: 'useQuery carrega Lead.list(), Proposal.list(), Contract.list(), OnboardingCase.list(), User.list(). Calcula KPIs, funil, tendências, performance por vendedor em tempo real via useMemo.', decisao: '', gate: '', sla: '< 5s', saida: '7 painéis renderizados com dados atualizados', proximo: '03' },
      { id: '03', resp: 'CEO/Admin', atividade: 'Seleciona período no filtro superior (7d/30d/90d/12m/all). Todos os painéis reagem ao filtro e recalculam métricas.', decisao: 'Período de análise?', gate: '', sla: '', saida: 'Métricas recalculadas para o período selecionado', proximo: '04' },
      { id: '04', resp: 'CEO/Admin', atividade: 'Analisa CEOKPICards: identifica variação vs período anterior (↑ verde ou ↓ vermelho). Métricas macro validam saúde da operação.', decisao: '', gate: '', sla: '', saida: 'Visão rápida de saúde geral', proximo: '05' },
      { id: '05', resp: 'CEO/Admin', atividade: 'Analisa CEOFunnelOverview: identifica etapa com maior drop-off (ex: proposta→aceite = 40% significa 60% de perda). Foco em gargalos.', decisao: 'Gargalo identificado?', gate: '', sla: '', saida: 'Gargalo do funil identificado', proximo: '06' },
      { id: '06', resp: 'CEO/Admin', atividade: 'Analisa SellerPerformanceTable: ranking por receita ou conversão. Identifica top performers e underperformers. Pode ordenar por qualquer métrica.', decisao: '', gate: '', sla: '', saida: 'Performance individual identificada', proximo: '07' },
      { id: '07', resp: 'CEO/Admin', atividade: 'Analisa CEOComplianceOverview: proporção de aprovações automáticas (1A-3B) vs manuais (4) vs bloqueios (5). Avalia eficiência do compliance.', decisao: '', gate: '', sla: '', saida: 'Eficiência de compliance avaliada', proximo: '08' },
      { id: '08', resp: 'CEO/Admin', atividade: 'Analisa TeamProductivityPanel: tempo médio entre etapas. Se lead→contato > 48h → problema de SLA. Se proposta→aceite > 10d → problema de proposta.', decisao: '', gate: '', sla: '', saida: 'Gargalos de tempo identificados para ação gerencial', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Dados em tempo real: ', text: 'Todas as métricas são calculadas em tempo real a partir das entidades (Lead, Proposal, Contract, OnboardingCase) via useQuery.' },
      { bold: 'Filtro de período global: ', text: 'Todos os 7 painéis respondem ao filtro. created_date é a base temporal.' },
      { bold: 'Funil calculado: ', text: 'Conversão = (leads na etapa N+1 com created_date no período / leads na etapa N no período) × 100%.' },
      { bold: 'Produtividade: ', text: 'Tempo médio = média(diff(Lead.lastInteractionDate, Lead.created_date)) para cada transição.' },
      { bold: 'Variação percentual: ', text: 'KPIs mostram (valor_período_atual - valor_período_anterior) / valor_período_anterior × 100%.' },
    ],
    complianceIntro: 'Controles de acesso:',
    complianceItens: [
      'Apenas Admin pode acessar o Dashboard CEO (verificado por user.role).',
      'Dados financeiros (TPV, receita) são estimativas baseadas nos leads do pipeline — não são dados reais de faturamento.',
      'Nenhum dado de PII é exibido nos gráficos agregados.',
    ],
    governanca: [
      { bold: 'O CEO/Admin ', text: 'consome dados para tomada de decisão estratégica: alocação de recursos, metas, gargalos.' },
      { bold: 'O Sistema ', text: 'calcula e apresenta métricas automaticamente, sem intervenção humana.' },
    ],
    raciRoles: ['CEO/Admin', 'Sistema'],
    raciActivities: [
      { name: 'Acessar dashboard', values: ['R', ''] },
      { name: 'Calcular KPIs e gráficos', values: ['', 'R'] },
      { name: 'Analisar gargalos', values: ['R', ''] },
      { name: 'Tomar decisões estratégicas', values: ['R', ''] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 30. DASHBOARD COMERCIAL (OPERACIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-030',
    nome: 'Dashboard Comercial — Gestão Operacional de Vendas',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / Gestão',
    objetivo: 'Definir a composição e funcionalidades do Dashboard Comercial para gestão operacional diária:',
    objetivoItens: [
      'KPIs operacionais (CommercialKPIs): 8 cards — leads hoje/semana/mês, propostas enviadas/aceitas, compliance pendente, contratos, receita.',
      'Métricas rápidas (CommercialQuickMetrics): leads sem contato, propostas expirando, SLAs em risco.',
      'Funil de vendas (SalesFunnelChart): gráfico visual do pipeline atual.',
      'Leads por origem (LeadsByOriginChart): Pagsmile v5, PIX v4, Reunião, IA, Introducer, Landing Page, Proposta Padrão, Simplificado.',
      'Leads por segmento (LeadsBySegmentChart): 10 segmentos com contagem e TPV.',
      'Tendência de leads (LeadsTrendChart): evolução temporal por dia/semana.',
      'Status de propostas (ProposalStatusPieChart): rascunho, enviada, visualizada, aceita, recusada, expirada.',
      'TPV por segmento (TpvBySegmentChart): volume por vertical.',
      'Receita vs Margem (RevenueMarginChart): estimativa de receita e margem.',
      'Top Introducers (TopIntroducersTable): ranking por leads e conversão.',
      'Resumo Propostas Padrão (StandardProposalsSummary): leads por proposta padrão.',
      'Leads recentes (RecentLeadsTable): últimos 20 leads com ações rápidas.',
      'Distribuição Lead Qualifier (LeadQualifierDistribution): EXCELENTE→INSUFICIENTE.',
      'Alertas comerciais (CommercialAlerts): urgências para ação imediata.',
      'Insights IA (CommercialInsights): recomendações automáticas.',
    ],
    escopoInclui: [
      'CommercialKPIs: 8 cards com variação temporal (vs período anterior).',
      'CommercialQuickMetrics: alertas numéricos de urgência.',
      'SalesFunnelChart: 7 etapas do funil com contagem.',
      'LeadsByOriginChart: gráfico de barras por canal de origem.',
      'LeadsBySegmentChart: gráfico de barras por segmento.',
      'LeadsTrendChart: gráfico de linha temporal.',
      'ProposalStatusPieChart: gráfico de pizza com 6 status.',
      'TpvBySegmentChart: barras de TPV por segmento.',
      'RevenueMarginChart: barras empilhadas receita + margem.',
      'TopIntroducersTable: tabela com leads, conversão, receita por Introducer.',
      'StandardProposalsSummary: cards por proposta padrão ativa.',
      'RecentLeadsTable: tabela com protocolo, empresa, score, status, ações.',
      'LeadQualifierDistribution: gráfico donut da distribuição de maturidade.',
      'CommercialAlerts: alertas priorizados (vermelho urgente, amarelo atenção).',
      'CommercialInsights: 3-5 insights gerados automaticamente.',
    ],
    escopoNaoInclui: [
      'Dashboard CEO estratégico (ver PROC-029).',
      'Pipeline Kanban interativo (ver PROC-007).',
      'Dados & Insights avançados (ver PROC-031).',
    ],
    steps: [
      { id: '01', resp: 'Comercial/Admin', atividade: 'Acessa DashboardComercial no menu (seção Leads & Propostas)', decisao: '', gate: '', sla: '', saida: 'Dashboard com 15 painéis', proximo: '02' },
      { id: '02', resp: 'Sistema', atividade: 'Carrega Lead, Proposal, PixProposal, Contract, Introducer, StandardProposal, SegmentDefaultRates. Calcula 15 painéis via useMemo.', decisao: '', gate: '', sla: '< 5s', saida: 'Todos os painéis renderizados', proximo: '03' },
      { id: '03', resp: 'Comercial', atividade: 'Verifica CommercialAlerts primeiro: leads sem contato >3d (vermelho), propostas expirando <2d (amarelo), SLA ultrapassado (vermelho). Clica no alerta → link direto para a ação.', decisao: 'Urgências?', gate: '', sla: '', saida: 'Ações urgentes priorizadas', proximo: '04' },
      { id: '04', resp: 'Comercial', atividade: 'Analisa CommercialQuickMetrics: números brutos de leads pendentes, propostas ativas, compliance em andamento.', decisao: '', gate: '', sla: '', saida: 'Contexto operacional do momento', proximo: '05' },
      { id: '05', resp: 'Comercial', atividade: 'Navega gráficos: LeadsByOriginChart (qual canal funciona melhor?), LeadsBySegmentChart (qual segmento?), ProposalStatusPieChart (quantas aceitas vs recusadas?).', decisao: '', gate: '', sla: '', saida: 'Insights visuais para otimização', proximo: '06' },
      { id: '06', resp: 'Comercial', atividade: 'Usa RecentLeadsTable para acessar últimos leads e tomar ação rápida (iniciar contato, gerar proposta, ver detalhes).', decisao: '', gate: '', sla: '', saida: 'Ação comercial executada', proximo: '07' },
      { id: '07', resp: 'Gestor', atividade: 'Analisa CommercialInsights: sugestões automáticas baseadas nos dados (ex: "Segmento Educação tem 85% de conversão — priorize"). Usa para direcionar o time.', decisao: '', gate: '', sla: '', saida: 'Direcionamento estratégico para o time', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Alertas proativos: ', text: 'CommercialAlerts detecta automaticamente: leads >3 dias sem contato, propostas <2 dias para expirar, SLA de first contact ultrapassado. Prioriza por urgência (vermelho > amarelo > verde).' },
      { bold: 'Insights IA: ', text: 'CommercialInsights analisa dados agregados e sugere ações: melhor canal, melhor segmento, taxa de conversão por fonte, Introducers mais eficientes.' },
      { bold: 'Métricas em tempo real: ', text: 'Todas calculadas a partir das entidades, sem cache. useQuery refetch automático.' },
      { bold: '15 painéis independentes: ', text: 'Cada painel calcula suas próprias métricas. Falha em um não afeta os outros.' },
    ],
    complianceIntro: 'Controles:',
    complianceItens: [
      'Dados de leads são read-only no dashboard (sem edição direta — links levam para páginas de ação).',
      'CommercialAlerts usam links diretos para páginas operacionais.',
      'Acesso restrito a Admin e usuários autenticados.',
    ],
    governanca: [
      { bold: 'O Comercial ', text: 'usa o dashboard para priorizar ações diárias e identificar oportunidades.' },
      { bold: 'O Gestor ', text: 'monitora performance do time, distribui leads e direciona esforços.' },
      { bold: 'O Sistema ', text: 'calcula todas as métricas automaticamente sem intervenção.' },
    ],
    raciRoles: ['Comercial', 'Gestor', 'Sistema'],
    raciActivities: [
      { name: 'Acessar dashboard', values: ['R', 'R', ''] },
      { name: 'Calcular métricas', values: ['', '', 'R'] },
      { name: 'Agir em alertas', values: ['R', 'I', ''] },
      { name: 'Monitorar performance', values: ['I', 'R', ''] },
      { name: 'Analisar insights', values: ['R', 'R', ''] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 31. DADOS & INSIGHTS (ANALYTICS AVANÇADO)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-031',
    nome: 'Dados & Insights — Analytics Avançado Multi-Dimensional (18 Seções)',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Dados / BI / Comercial / Compliance',
    objetivo: 'Definir as 18 seções analíticas do módulo Dados & Insights para análise profunda da operação:',
    objetivoItens: [
      '18 seções temáticas expansíveis cobrindo todo o espectro: funil, perfil, volume, taxas, rentabilidade, introducers, compliance, scoring v4, risco, operacional, comercial, parceiros, IA, saúde dos dados, benchmark.',
      'Gráficos interativos (Recharts): barras, linhas, pizza, donut (DonutChart), barras horizontais (HorizontalBarList).',
      'StatCards com variação percentual, trend icon e cor contextual.',
      'MinMaxMedianTable para estatísticas detalhadas.',
      'Filtros por período aplicáveis globalmente.',
    ],
    escopoInclui: [
      '1. InsightsFunnelSection: funil 7 etapas com taxa conversão entre cada.',
      '2. InsightsLeadProfileSection: leads por segmento, porte, região, fonte.',
      '3. InsightsMixSection: distribuição TPV por método (cartão/PIX/boleto) — DonutChart.',
      '4. InsightsTPVSection: volume transacional por segmento e período — barras + linha.',
      '5. InsightsRatesSection: taxas médias praticadas vs benchmark por segmento.',
      '6. InsightsProposalRatesSection: taxas médias das propostas aceitas por segmento/faixa.',
      '7. InsightsProfitabilitySection: receita vs custo vs margem por segmento — barras empilhadas.',
      '8. InsightsIntroducerSection: ranking Introducers por leads, conversão, receita.',
      '9. InsightsComplianceSection: distribuição por status compliance + taxa aprovação auto/manual.',
      '10. InsightsRiskScoringV4Section: distribuição scores v4, subfaixas, top variáveis V ativas.',
      '11. InsightsComplianceJourneySection: tempo médio por etapa do compliance (questionário → docs → biometria → scoring).',
      '12. InsightsRiskOperationalSection: risco operacional — chargebacks, fraude, bloqueios.',
      '13. InsightsRiskPortfolioSection: perfil de risco do portfólio ativo — subfaixas, RR médio.',
      '14. InsightsOperationalSection: SLA compliance (% dentro do prazo), throughput.',
      '15. InsightsCommercialPerfSection: performance por vendedor — leads, propostas, conversão, receita.',
      '16. InsightsPartnerSection: análise de parceiros adquirentes — custo médio, volume, rentabilidade.',
      '17. InsightsAISection: métricas das IAs — PRISCILA (score médio, distribuição), Qualifier (distribuição EXCELENTE→INSUFICIENTE), SENTINEL (aprovação auto vs manual).',
      '18. InsightsDataHealthSection: saúde dos dados — % campos preenchidos por entidade, completude, inconsistências detectadas.',
      'InsightsBenchmarkSection: benchmarking taxas vs mercado (se dados disponíveis).',
    ],
    escopoNaoInclui: [
      'Dashboards operacionais (ver PROC-029, PROC-030).',
      'Configuração de regras (ver PROC-026).',
    ],
    steps: [
      { id: '01', resp: 'Admin/Gestor', atividade: 'Acessa DadosInsights no menu (seção standalone). Página com header e 18+ seções em acordeão expansível (Accordion).', decisao: '', gate: '', sla: '', saida: 'Página carregada com seções colapsadas', proximo: '02' },
      { id: '02', resp: 'Sistema', atividade: 'Carrega dados de TODAS as entidades: Lead, Proposal, PixProposal, Contract, OnboardingCase, ComplianceScore, Partner, PartnerCost, Introducer, User, StandardProposal, SegmentDefaultRates, DocumentUpload. Usa useQuery com chaves de cache separadas por seção.', decisao: '', gate: '', sla: '< 10s', saida: 'Dados carregados, seções prontas para renderizar ao expandir', proximo: '03' },
      { id: '03', resp: 'Admin/Gestor', atividade: 'Expande seção de interesse (ex: InsightsFunnelSection). StatCards mostram métricas resumidas (total leads, conversão geral, TPV total). Gráficos mostram detalhamento (funil por etapa, taxa entre etapas).', decisao: '', gate: '', sla: '', saida: 'Seção expandida com dados', proximo: '04' },
      { id: '04', resp: 'Admin/Gestor', atividade: 'Navega entre seções para análise cruzada: ex: "Leads por segmento" (seção 2) → "Taxas por segmento" (seção 5) → "Rentabilidade por segmento" (seção 7) → conclusão: "Segmento X tem maior volume mas menor margem".', decisao: '', gate: '', sla: '', saida: 'Insights acionáveis de análise cruzada', proximo: '05' },
      { id: '05', resp: 'Admin/Gestor', atividade: 'Analisa InsightsDataHealthSection: verifica % de preenchimento de campos críticos, identifica leads com dados incompletos, valida consistência dos dados.', decisao: '', gate: '', sla: '', saida: 'Qualidade dos dados avaliada', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: '18 seções independentes: ', text: 'Cada seção calcula suas métricas internamente. Não há dependência entre seções. Falha em uma não afeta as outras.' },
      { bold: 'Componentes reutilizáveis: ', text: 'StatCard (KPI com variação), ChartCard (container gráfico), DonutChart (pizza), HorizontalBarList (ranking horizontal), MinMaxMedianTable (min/max/mediana/média).' },
      { bold: 'insightsUtils: ', text: 'Funções utilitárias compartilhadas: formatCurrency, formatPercent, getColor, filterByPeriod, calculateConversion.' },
      { bold: 'Filtro de período: ', text: 'Aplicável globalmente a todas as seções via prop compartilhado.' },
      { bold: 'Lazy rendering: ', text: 'Seções colapsadas não calculam métricas — apenas ao expandir.' },
    ],
    complianceIntro: 'Controles:',
    complianceItens: [
      'Acesso restrito a Admin.',
      'Dados são read-only (analytics puro, sem edição).',
      'Dados pessoais (PII) não são expostos em gráficos agregados — apenas métricas numéricas.',
      'InsightsDataHealthSection detecta inconsistências sem expor dados sensíveis.',
    ],
    governanca: [
      { bold: 'O Admin/Gestor ', text: 'usa insights para otimizar operação, identificar gargalos, oportunidades de crescimento e problemas de qualidade de dados.' },
      { bold: 'O Sistema ', text: 'calcula e renderiza métricas sem intervenção, com cache otimizado.' },
    ],
    raciRoles: ['Admin/Gestor', 'Sistema'],
    raciActivities: [
      { name: 'Acessar analytics', values: ['R', ''] },
      { name: 'Calcular 18 seções', values: ['', 'R'] },
      { name: 'Analisar insights', values: ['R', ''] },
      { name: 'Identificar gargalos', values: ['R', ''] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 32. NOTIFICAÇÕES E AUTOMAÇÕES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-032',
    nome: 'Sistema de Notificações e Automações (17 Backend Functions)',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Sistema / Comercial / Compliance',
    objetivo: 'Definir todas as notificações automáticas e automações agendadas da plataforma:',
    objetivoItens: [
      '12 notificações Slack em tempo real via SlackBot connector (scopes: chat:write, chat:write.public, channels:read, chat:write.customize).',
      '1 e-mail automático de follow-up para leads inativos.',
      '4 automações agendadas (verificação de SLAs, expiração propostas, leads incompletos, enriquecimento).',
    ],
    escopoInclui: [
      'NOTIFICAÇÕES SLACK (entity automations - on create/update):',
      '  notifyNewLead: Lead criado → Slack com protocolo, empresa, segmento, scores PRISCILA.',
      '  notifyStdProposalLead: Lead via proposta padrão → Slack com segmento e proposta.',
      '  notifyLandingPageLead: Lead via landing page → Slack com Introducer e segmento.',
      '  notifyProposalViewed: Proposal.status=visualizada → Slack com código e cliente.',
      '  notifyProposalAccepted: Proposal.status=aceita → Slack com código, cliente, TPV.',
      '  notifyNewProposal: Proposal criada → Slack com código, segmento, responsável.',
      '  notifyLeadStatusChange: Lead.status mudou → Slack com status anterior→novo.',
      '  notifyLeadHighRisk: Lead com iaRiskScore>70 → Slack URGENTE.',
      '  notifyComplianceCaseChange: OnboardingCase.status mudou → Slack.',
      '  notifyComplianceCompleted: OnboardingCase finalizado → Slack com decisão.',
      '  notifyComplianceScore: ComplianceScore criado → Slack com subfaixa e RR.',
      '  notifyContractUpdate: Contract.status mudou → Slack.',
      'E-MAIL:',
      '  sendFollowUpEmail: Lead inativo >7 dias → e-mail genérico via Core.SendEmail.',
      'AUTOMAÇÕES AGENDADAS (scheduled):',
      '  checkLeadSLA: diário → verifica leads sem contato vs SLA configurado.',
      '  checkExpiringProposals: diário → identifica propostas <2 dias para expirar.',
      '  checkIncompleteLeads: diário → identifica leads sem contato >X dias.',
      '  expireProposals: diário → muda status para "expirada" quando validUntil < hoje.',
      'ENTITY AUTOMATIONS:',
      '  onLeadCreatedEnrich: Lead criado → enriquecimento CNPJ via BrasilAPI.',
    ],
    escopoNaoInclui: [
      'Notificações do portal do Introducer (dashboard próprio).',
      'Notificações push mobile (não implementado).',
    ],
    steps: [
      { id: '01', resp: 'Sistema', atividade: 'Evento ocorre: Lead criado (entity create), Proposal atualizada (entity update), OnboardingCase atualizado (entity update), ou agendamento diário (scheduled cron)', decisao: 'Tipo de evento?', gate: '', sla: '', saida: 'Evento detectado pela automação configurada', proximo: '02' },
      { id: '02', resp: 'Sistema', atividade: 'Backend function correspondente é invocada. Para notificações Slack: função recebe event.data (entidade atual) e event.old_data (estado anterior para updates). Para agendadas: função consulta entidades diretamente.', decisao: '', gate: '', sla: '< 5s', saida: 'Dados processados, mensagem formatada', proximo: '03' },
      { id: '03', resp: 'Sistema', atividade: 'Notificação Slack: usa base44.asServiceRole.connectors.getConnection("slackbot") → accessToken → POST chat.postMessage com blocos formatados (título, campos, cores, botões). E-mail: usa base44.integrations.Core.SendEmail.', decisao: '', gate: '', sla: '< 10s', saida: 'Mensagem entregue no canal Slack ou e-mail enviado', proximo: '04' },
      { id: '04', resp: 'Sistema', atividade: 'Para automações agendadas: atualiza entidades relevantes (Lead.slaStatus, Proposal.status=expirada, etc.) e dispara notificações Slack de consolidação se aplicável.', decisao: '', gate: '', sla: '', saida: 'Entidades atualizadas + notificações enviadas', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Slack em tempo real: ', text: 'Notificações via SlackBot connector autorizado (scopes: chat:write, chat:write.public, channels:read, chat:write.customize). Mensagens com blocos formatados (rich text).' },
      { bold: 'E-mail follow-up: ', text: 'sendFollowUpEmail usa Core.SendEmail. Conteúdo genérico sem dados sensíveis — apenas "temos interesse em conversar".' },
      { bold: 'SLA check diário: ', text: 'checkLeadSLA roda diariamente via scheduled automation. Verifica created_date vs agora > threshold configurado.' },
      { bold: 'Enriquecimento on create: ', text: 'onLeadCreatedEnrich é entity automation (Lead create). Enriquece CNPJ via BrasilAPI, salva dados enriquecidos no Lead.' },
      { bold: 'Expiração automática: ', text: 'expireProposals roda diariamente. Filtra Proposals com validUntil < hoje AND status ∉ {aceita, recusada, cancelada, expirada}. Muda para status=expirada.' },
      { bold: 'Idempotência: ', text: 'Notificações de visualização usam verificação de status anterior (old_data.status ≠ "visualizada") para evitar duplicação.' },
    ],
    complianceIntro: 'Controles de automação:',
    complianceItens: [
      'Todas as automações são configuradas no backend e executam sem intervenção humana.',
      'Logs de execução disponíveis no dashboard do backend para auditoria.',
      'E-mails não contêm dados sensíveis (PII) — apenas link para acessar o sistema.',
      'Slack não expõe dados financeiros detalhados — apenas resumo (empresa, segmento, status).',
    ],
    governanca: [
      { bold: 'O Sistema ', text: 'executa todas as 17+ automações sem intervenção humana.' },
      { bold: 'O Admin ', text: 'pode ativar/desativar automações no dashboard do backend (list_automations / manage_automation).' },
    ],
    raciRoles: ['Sistema', 'Admin', 'Comercial'],
    raciActivities: [
      { name: 'Detectar evento', values: ['R', '', ''] },
      { name: 'Enviar notificação Slack', values: ['R', '', 'I'] },
      { name: 'Enviar e-mail follow-up', values: ['R', '', 'I'] },
      { name: 'Executar automação agendada', values: ['R', '', ''] },
      { name: 'Configurar/desativar automações', values: ['', 'R', ''] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 33. GESTÃO DE TAXAS PADRÃO POR SEGMENTO
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-033',
    nome: 'Gestão de Taxas Padrão por Segmento (SegmentDefaultRates) com Cascata',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Admin / Financeiro / Comercial',
    objetivo: 'Definir o fluxo de gestão das taxas padrão por segmento que alimentam propostas automáticas e landing pages:',
    objetivoItens: [
      'CRUD de SegmentDefaultRates por segmento (10 segmentos ativos).',
      'Taxas por campo: MDR à vista, 2-6x, 7-12x, 13-21x, antecipação mensal (%), fee transação (R$), antifraude (R$), 3DS (R$), PIX percentual (%), PIX fixo (R$), boleto (R$).',
      'Preview visual (SegmentRatePreview) antes de salvar.',
      'Cascata automática (cascadeSegmentRatesUpdate): alteração propaga para StandardProposal.isDefaultForSegment + Introducer.standardRates[] vinculados.',
    ],
    escopoInclui: [
      'GerenciarTaxasPadrao: lista de segmentos com SegmentRatesList (nome, MCC, riskLevel, taxas resumidas).',
      'SegmentRateForm: formulário completo de edição por segmento com todos os campos numéricos.',
      'SegmentRatePreview: preview em tempo real ao editar (tabela visual com taxas).',
      'cascadeSegmentRatesUpdate: backend function que propaga alterações automaticamente.',
    ],
    escopoNaoInclui: [
      'Taxas do parceiro adquirente (custos, ver PROC-020).',
      'Taxas de proposta personalizada (definidas pelo comercial, ver PROC-003).',
    ],
    steps: [
      { id: '01', resp: 'Admin', atividade: 'Acessa GerenciarTaxasPadrao (menu Ferramentas). SegmentRatesList exibe 10 segmentos com taxas atuais, MCC, nível de risco. Cada card mostra MDR 1x, PIX, antecipação como resumo.', decisao: '', gate: '', sla: '', saida: 'Lista de segmentos visível', proximo: '02' },
      { id: '02', resp: 'Admin', atividade: 'Clica "Editar" no segmento desejado. SegmentRateForm carrega: segmentName, MCC, riskLevel, mdrAvista, mdr2a6x, mdr7a12x, mdr13a21x, percentualAntecipacao, feeTransacao, antifraude, taxa3ds, pixTaxaPercentual, pixTaxaFixa, boleto.', decisao: '', gate: '', sla: '', saida: 'Formulário carregado com taxas atuais', proximo: '03' },
      { id: '03', resp: 'Admin', atividade: 'Edita valores. SegmentRatePreview atualiza em tempo real à direita: mostra tabela visual com taxas formatadas (ex: "MDR 1x: 3.29%", "PIX: 0.99%").', decisao: '', gate: '', sla: '', saida: 'Preview visual atualizado', proximo: '04' },
      { id: '04', resp: 'Admin', atividade: 'Clica "Salvar". SegmentDefaultRates atualizado no banco.', decisao: 'Validação: todos os campos numéricos ≥ 0?', gate: 'G1', sla: '', saida: 'SegmentDefaultRates persistido', proximo: '05' },
      { id: '05', resp: 'Sistema', atividade: 'cascadeSegmentRatesUpdate (backend function) é disparado automaticamente: (1) Busca StandardProposal com segment=segmentoAlterado AND isDefaultForSegment=true → atualiza rates da proposta padrão. (2) Busca Introducers com standardRates[] contendo segmentoAlterado → atualiza taxas na landing page do Introducer.', decisao: '', gate: '', sla: 'Imediato', saida: 'Propostas padrão + landing pages atualizadas automaticamente', proximo: '06' },
      { id: '06', resp: 'Sistema', atividade: 'Log de cascata: registra quantas StandardProposal e Introducers foram atualizados. Exibe confirmação ao Admin.', decisao: '', gate: '', sla: 'Imediato', saida: 'Admin informado do resultado da cascata', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Cascata automática: ', text: 'cascadeSegmentRatesUpdate propaga para StandardProposal.isDefaultForSegment + Introducer.standardRates[]. Garante que links rápidos e landing pages sempre exibem taxas atualizadas.' },
      { bold: '10 segmentos: ', text: 'Educação, Infoprodutos, E-commerce, SaaS, Gateway, Marketplace, MPE, Dropshipping, Plataformas Verticais, Link de Pagamento.' },
      { bold: 'Risco por segmento: ', text: 'Cada segmento tem nível de risco (Baixo/Médio/Alto) que contextualiza as taxas sugeridas.' },
      { bold: 'MCC vinculado: ', text: 'Cada segmento tem MCC principal para referência nas propostas e contratos.' },
      { bold: 'Preview obrigatório: ', text: 'SegmentRatePreview atualiza em tempo real para o Admin verificar antes de salvar.' },
    ],
    complianceIntro: 'Controles de gestão de taxas:',
    complianceItens: [
      'Apenas Admin pode alterar taxas padrão (role=admin verificado).',
      'Cascata é automática mas auditável: função registra log de cada atualização.',
      'Propostas já enviadas/aceitas NÃO são alteradas pela cascata — apenas templates ativos.',
    ],
    governanca: [
      { bold: 'O Admin ', text: 'define taxas padrão — são a base de verdade para propostas automáticas e landing pages.' },
      { bold: 'O Sistema ', text: 'propaga mudanças automaticamente via cascata para manter consistência.' },
      { bold: 'O Comercial ', text: 'não tem acesso para editar taxas padrão — apenas para usar nas propostas.' },
    ],
    raciRoles: ['Admin', 'Sistema', 'Comercial'],
    raciActivities: [
      { name: 'Editar taxas padrão', values: ['R', '', ''] },
      { name: 'Preview antes de salvar', values: ['R', 'C', ''] },
      { name: 'Propagar cascata', values: ['', 'R', ''] },
      { name: 'Usar taxas em propostas', values: ['', '', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 34. HELENA IA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-034',
    nome: 'Helena IA — Assistente Inteligente de Compliance e Análise',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Compliance / IA / Admin',
    objetivo: 'Definir o funcionamento da IA Helena como assistente inteligente:',
    objetivoItens: [
      'Análise de risco automatizada para casos de onboarding.',
      'Dashboard de configuração de integrações (CAF, BigDataCorp).',
      'Relatórios de análise (HelenaAnalysis) por caso.',
      'Status de integrações externas e logs de chamadas.',
    ],
    escopoInclui: [
      'HelenaIA: interface com status de integrações (CAF, BDC) e configuração.',
      'HelenaAnalysis: entidade com resultados de análises individuais.',
      'IntegracoesExternas: logs de chamadas (IntegrationLog) com status, duração, resposta.',
      'Geração de relatórios e recomendações via InvokeLLM.',
    ],
    escopoNaoInclui: [
      'Risk Scoring v4 motor (processo separado, ver PROC-019).',
      'SENTINEL agente (executado automaticamente, ver PROC-005).',
    ],
    steps: [
      { id: '01', resp: 'Admin', atividade: 'Acessa HelenaIA (menu Integrações) para verificar status das integrações: CAF (biometria), BigDataCorp (enriquecimento CNPJ). Visualiza IntegrationConfig com status, últimas chamadas, taxa de sucesso.', decisao: '', gate: '', sla: '', saida: 'Status das integrações visível', proximo: '02' },
      { id: '02', resp: 'Admin', atividade: 'Verifica IntegrationLog: histórico de chamadas com timestamp, status (sucesso/falha), duração (ms), tipo de requisição. Filtra por período e tipo.', decisao: 'Integrações funcionando?', gate: '', sla: '', saida: 'Saúde das integrações avaliada', proximo: '03' },
      { id: '03', resp: 'Admin/Analista', atividade: 'Solicita análise Helena para um caso específico. Helena usa InvokeLLM para cruzar dados do OnboardingCase, Merchant, QuestionnaireResponses, ExternalValidationResults com padrões históricos.', decisao: '', gate: '', sla: '< 60s', saida: 'HelenaAnalysis criada com relatório detalhado', proximo: '04' },
      { id: '04', resp: 'Admin/Analista', atividade: 'Revisa relatório Helena: score de risco estimado, pontos de atenção, recomendação (Aprovar/Manual/Recusar), comparação com perfil do segmento.', decisao: 'Seguir recomendação?', gate: '', sla: '', saida: 'Decisão informada sobre o caso', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Assistente, não decisor: ', text: 'Helena sugere, mas a decisão final é sempre humana (human-in-the-loop).' },
      { bold: 'IntegrationLog completo: ', text: 'Cada chamada a CAF/BDC gera log com timestamp, status, duração e resposta resumida.' },
      { bold: 'HelenaAnalysis persistida: ', text: 'Cada análise é salva para rastreabilidade, aprendizado e auditoria.' },
    ],
    complianceIntro: 'Controles:',
    complianceItens: [
      'Helena atua como consultora — sem poder de decisão autônomo.',
      'Cada análise persistida e auditável.',
      'IntegrationLog garante rastreabilidade de todas as chamadas externas.',
    ],
    governanca: [
      { bold: 'Helena IA ', text: 'sugere e informa — nunca decide autonomamente.' },
      { bold: 'O Analista ', text: 'usa as sugestões como insumo para sua decisão final.' },
      { bold: 'O Admin ', text: 'monitora status das integrações e resolve falhas.' },
    ],
    raciRoles: ['Admin', 'Analista', 'Helena IA', 'Sistema'],
    raciActivities: [
      { name: 'Monitorar integrações', values: ['R', '', '', ''] },
      { name: 'Solicitar análise', values: ['R', 'R', '', ''] },
      { name: 'Executar análise', values: ['', '', 'R', 'C'] },
      { name: 'Decidir sobre caso', values: ['', 'R', '', ''] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 35. MESSAGE TEMPLATES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-035',
    nome: 'Gestão de Templates de Mensagem (WhatsApp/E-mail)',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / Marketing / Admin',
    objetivo: 'Definir o fluxo de criação e uso de templates de mensagem para comunicação padronizada:',
    objetivoItens: [
      'CRUD de MessageTemplate com nome, categoria, canal, conteúdo.',
      'Variáveis dinâmicas: {nome_empresa}, {contato}, {protocolo}, {link_proposta}, {segmento}, {vendedor}.',
      'Categorias por etapa do funil: primeiro_contato, follow_up, envio_proposta, pos_aceite, compliance, contrato.',
      'Preview com dados de exemplo e cópia rápida.',
    ],
    escopoInclui: [
      'MessageTemplates: CRUD com lista, criação, edição, preview.',
      'Variáveis dinâmicas substituídas automaticamente ao selecionar lead.',
      'Categorias organizadas por etapa do funil comercial.',
      'Preview com dados de exemplo antes de copiar.',
      'Botão de cópia rápida para clipboard.',
    ],
    escopoNaoInclui: [
      'Envio automático de mensagens (apenas templates para copiar manualmente).',
      'Integração direta com WhatsApp Business API.',
    ],
    steps: [
      { id: '01', resp: 'Admin', atividade: 'Acessa MessageTemplates (menu Ferramentas). Lista templates existentes com nome, categoria, canal.', decisao: '', gate: '', sla: '', saida: 'Lista de templates visível', proximo: '02' },
      { id: '02', resp: 'Admin', atividade: 'Cria novo template: define nome, categoria (primeiro_contato/follow_up/envio_proposta/pos_aceite/compliance/contrato), canal (WhatsApp/e-mail), conteúdo com variáveis {xxx}.', decisao: '', gate: '', sla: '', saida: 'MessageTemplate salvo', proximo: '03' },
      { id: '03', resp: 'Comercial', atividade: 'Ao interagir com lead (ex: no Pipeline ou QuestionariosLeads), seleciona template da categoria apropriada. Sistema substitui variáveis pelos dados reais do lead: {nome_empresa} → "Empresa XYZ", {protocolo} → "LEAD-2026-00123".', decisao: '', gate: '', sla: '', saida: 'Mensagem personalizada pronta', proximo: '04' },
      { id: '04', resp: 'Comercial', atividade: 'Copia mensagem para clipboard e cola no WhatsApp/e-mail. Comunicação padronizada e profissional.', decisao: '', gate: '', sla: '', saida: 'Mensagem enviada ao cliente', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Variáveis dinâmicas: ', text: 'Substituídas em tempo real: {nome_empresa}, {contato}, {protocolo}, {link_proposta}, {link_compliance}, {segmento}, {vendedor}, {data_hoje}.' },
      { bold: 'Categorias por etapa: ', text: 'Templates organizados por etapa do funil para seleção rápida e contextual.' },
      { bold: 'CRUD restrito: ', text: 'Apenas Admin cria/edita templates. Comercial pode usar (copiar) mas não editar o template base.' },
    ],
    complianceIntro: 'Controles:',
    complianceItens: [
      'Templates padronizados garantem comunicação consistente com o cliente.',
      'Admin controla o conteúdo — comercial não pode alterar templates.',
    ],
    governanca: [
      { bold: 'O Admin ', text: 'define templates padronizados para comunicação consistente da equipe.' },
      { bold: 'O Comercial ', text: 'usa templates para agilizar comunicação sem perder qualidade e consistência.' },
    ],
    raciRoles: ['Admin', 'Comercial'],
    raciActivities: [
      { name: 'Criar/editar template', values: ['R', ''] },
      { name: 'Usar template (copiar)', values: ['', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 36. GESTÃO DE DOCUMENTOS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-036',
    nome: 'Gestão e Validação de Documentos de Compliance',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Compliance / Admin',
    objetivo: 'Definir o fluxo de gestão, validação e consulta de documentos enviados durante compliance:',
    objetivoItens: [
      'Visualização centralizada de todos os DocumentUpload por caso de onboarding.',
      'Validação manual: Pendente → Validado ou Rejeitado (com comentário obrigatório para rejeição).',
      'Solicitação de documentos adicionais ao cliente (OnboardingCase.status → "Docs Solicitados").',
      'Download individual e em lote ZIP (downloadCaseDocuments backend).',
      'Visualização inline via DocumentViewerModal (PDF renderizado, imagens).',
      'Tipos de documento configuráveis por template (DocumentType entity).',
    ],
    escopoInclui: [
      'GestaoDocumentos: dashboard de documentos pendentes de validação por caso.',
      'CaseDocumentsTab: aba "Documentos" dentro da análise de caso (AnaliseDeCasos).',
      'DocumentViewerModal: visualização inline de PDF (iframe) e imagens (img).',
      'Download individual (fileUrl direto) e ZIP (downloadCaseDocuments → getCaseDocumentUrls + JSZip).',
      'Validação: botões Validar/Rejeitar com comentário obrigatório para rejeição.',
      'DocumentType: entity com nome, descrição, formatos aceitos, tamanho máximo, merchantType (PF/PJ/BOTH), isRequired, conditionalLogic.',
    ],
    escopoNaoInclui: [
      'Upload pelo cliente (feito durante compliance, ver PROC-005).',
      'Configuração de documentos obrigatórios por template (ver PROC-026).',
    ],
    steps: [
      { id: '01', resp: 'Analista', atividade: 'Acessa GestaoDocumentos (dashboard) ou aba "Documentos" de um caso (CaseDocumentsTab). Vê lista de DocumentUpload: documentName, fileName, fileType, fileSize, uploadDate, validationStatus (Pendente/Validado/Rejeitado).', decisao: '', gate: '', sla: '', saida: 'Lista de documentos com status de validação', proximo: '02' },
      { id: '02', resp: 'Analista', atividade: 'Clica "Ver" para abrir DocumentViewerModal. PDF renderizado inline via iframe. Imagens (JPG/PNG) exibidas diretamente. Verifica legibilidade, autenticidade e conformidade do documento.', decisao: 'Documento legível? Dados corretos? Formato válido? Não adulterado?', gate: 'G1', sla: '', saida: 'Documento revisado visualmente', proximo: '03' },
      { id: '03', resp: 'Analista', atividade: 'Clica "Validar" (marca como Validado) ou "Rejeitar" (campo de comentário obrigatório para motivo da rejeição). DocumentUpload.validationStatus atualizado.', decisao: '', gate: '', sla: '', saida: 'Status do documento atualizado', proximo: '04' },
      { id: '04', resp: 'Sistema', atividade: 'Verifica: todos os documentos obrigatórios validados? Se sim → caso pode prosseguir normalmente. Se não (rejeição) → OnboardingCase.status → "Docs Solicitados". Comercial notificado para solicitar novos documentos ao cliente.', decisao: 'Todos validados?', gate: 'G2', sla: '', saida: 'Status do caso atualizado', proximo: '05' },
      { id: '05', resp: 'Analista', atividade: 'Pode baixar documentos individuais (link direto) ou todos de uma vez via "Baixar Todos (ZIP)". downloadCaseDocuments gera ZIP com todos os arquivos do caso.', decisao: '', gate: '', sla: '', saida: 'Documentos baixados para arquivo', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Validação manual obrigatória: ', text: 'Cada documento deve ser revisado individualmente pelo analista.' },
      { bold: 'Rejeição com motivo: ', text: 'Ao rejeitar, o analista DEVE informar o motivo (campo obrigatório). Motivo é persistido para auditoria.' },
      { bold: 'ZIP download: ', text: 'downloadCaseDocuments (backend) usa getCaseDocumentUrls para coletar URLs, fetch para baixar conteúdo, JSZip para empacotar em ZIP.' },
      { bold: 'Formatos suportados: ', text: 'PDF renderizado inline via iframe. JPG/JPEG/PNG exibidos como imagem. Outros formatos: download direto.' },
      { bold: 'Documentos não deletados: ', text: 'Documentos rejeitados não são deletados — apenas marcados como rejeitados. Cliente pode enviar novos.' },
      { bold: 'DocumentType configurável: ', text: 'Cada template de questionário define quais documentos são obrigatórios via requiredDocuments[] com conditionalLogic.' },
    ],
    complianceIntro: 'Controles de gestão documental:',
    complianceItens: [
      'Cada validação registra analista (assignedAnalystId), data (manualReviewDate) e motivo (se rejeição).',
      'Documentos nunca são deletados — histórico completo preservado.',
      'Retenção mínima: 5 anos após última atualização (LGPD + regulatório).',
      'Acesso restrito a Admin e Analista de Compliance.',
    ],
    governanca: [
      { bold: 'O Analista de Compliance ', text: 'é o único responsável pela validação/rejeição de documentos.' },
      { bold: 'O Sistema ', text: 'garante rastreabilidade completa de cada validação e download.' },
      { bold: 'O Comercial ', text: 'é informado quando documentos são rejeitados para solicitar novos ao cliente.' },
    ],
    raciRoles: ['Analista', 'Sistema', 'Comercial', 'Admin'],
    raciActivities: [
      { name: 'Revisar documento', values: ['R', '', '', 'C'] },
      { name: 'Validar/Rejeitar', values: ['R', '', '', ''] },
      { name: 'Atualizar status caso', values: ['', 'R', 'I', ''] },
      { name: 'Solicitar novos docs', values: ['R', '', 'I', ''] },
      { name: 'Download ZIP', values: ['R', 'C', '', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 37. CONFIGURAÇÕES E AUDITORIA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-037',
    nome: 'Configurações Gerais, Regras de Compliance e Auditoria',
    versao: '1.0.0',
    data: '06/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Admin / Compliance / Sistema',
    objetivo: 'Definir os módulos de configuração do sistema, regras de compliance e auditoria:',
    objetivoItens: [
      'Configurações gerais: parâmetros do sistema, SLAs, limites (Configuracoes).',
      'Integrações externas: CAF (biometria), BigDataCorp (enriquecimento CNPJ), status e logs (IntegracoesExternas).',
      'Regras de compliance configuráveis: ComplianceRule com condições, ações, prioridade (RegrasDeCompliance).',
      'Simulador de regras: testar regra contra dados de exemplo (RuleSimulatorModal).',
      'Auditoria completa: AuditLog com filtros por ação, responsável, entidade, período (Auditoria).',
    ],
    escopoInclui: [
      'Configuracoes: parâmetros gerais, SLAs de contato (dias), limites de expiração, configurações de e-mail.',
      'IntegracoesExternas: status de CAF e BigDataCorp, IntegrationConfig (credenciais, URLs, status). IntegrationLog (chamada, status, duração, resposta). Dashboard de saúde das integrações.',
      'RegrasDeCompliance: CRUD de ComplianceRule — nome, descrição, condição (if field operator value), ação (then do X), prioridade, isActive. Regras aplicadas automaticamente na análise.',
      'RuleSimulatorModal: insere dados de exemplo → sistema avalia quais regras seriam ativadas → exibe resultado.',
      'Auditoria: AuditLog listagem com filtros — ação (criou_proposta, assinou_contrato, etc.), responsável (user), entidade afetada, período. Detalhes expandíveis com dados antes/depois.',
    ],
    escopoNaoInclui: [
      'Configuração de parceiros adquirentes (ver PROC-020).',
      'Configuração de Introducers (ver PROC-010).',
      'Configuração de taxas padrão (ver PROC-033).',
    ],
    steps: [
      { id: '01', resp: 'Admin', atividade: 'Acessa módulo desejado: Configurações (menu Admin), Integrações Externas (menu Integrações), Regras de Compliance (menu Ferramentas), Auditoria (menu Admin).', decisao: '', gate: '', sla: '', saida: 'Interface de configuração carregada', proximo: '02' },
      { id: '02A', resp: 'Admin', atividade: 'CONFIGURAÇÕES: edita parâmetros — SLA de primeiro contato (em horas), prazo expiração propostas (em dias), e-mail de notificação, parâmetros gerais.', decisao: '', gate: '', sla: '', saida: 'Parâmetros atualizados', proximo: '03' },
      { id: '02B', resp: 'Admin', atividade: 'INTEGRAÇÕES: verifica status de CAF e BigDataCorp. IntegrationConfig mostra URL, credenciais (mascaradas), status (ativo/inativo), último teste. IntegrationLog lista chamadas com timestamp, tipo, status, duração (ms).', decisao: 'Integração saudável?', gate: '', sla: '', saida: 'Status das integrações avaliado', proximo: '03' },
      { id: '02C', resp: 'Admin', atividade: 'REGRAS: cria/edita ComplianceRule — ex: "Se CNPJ MEI + TPV > R$6.750/mês → Flag HIGH_PIX_VOLUME_MEI". Pode testar no RuleSimulatorModal com dados fictícios antes de ativar.', decisao: '', gate: '', sla: '', saida: 'Regras configuradas e testadas', proximo: '03' },
      { id: '02D', resp: 'Admin', atividade: 'AUDITORIA: filtra AuditLog por período, ação, responsável. Expande entrada para ver detalhes completos: dados antes (old), dados depois (new), IP, timestamp.', decisao: '', gate: '', sla: '', saida: 'Trilha de auditoria consultada', proximo: '03' },
      { id: '03', resp: 'Sistema', atividade: 'Aplica configurações em tempo real. Regras ativadas passam a ser avaliadas no próximo scoring. IntegrationConfig validado. AuditLog registra cada alteração de configuração.', decisao: '', gate: '', sla: 'Imediato', saida: 'Sistema atualizado com novas configurações', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Apenas Admin: ', text: 'Todas as configurações são restritas a usuários com role=admin.' },
      { bold: 'Simulador de regras: ', text: 'RuleSimulatorModal permite testar regra contra dados fictícios antes de ativá-la, evitando impacto indesejado.' },
      { bold: 'Auditoria imutável: ', text: 'AuditLog é append-only — registros não podem ser editados ou deletados.' },
      { bold: 'IntegrationLog completo: ', text: 'Cada chamada externa gera log com timestamp, status, duração e resposta resumida.' },
      { bold: 'Regras versionáveis: ', text: 'ComplianceRule tem isActive para ativar/desativar sem deletar. Histórico preservado.' },
    ],
    complianceIntro: 'Controles de governança:',
    complianceItens: [
      'Toda alteração de configuração gera AuditLog (quem, quando, o quê).',
      'Regras de compliance são testáveis antes de ativar (sem impacto em produção).',
      'IntegrationLog garante rastreabilidade de chamadas a APIs externas (CAF, BDC).',
      'AuditLog é imutável e append-only — não pode ser alterado retroativamente.',
      'Retenção de audit logs: 5 anos mínimo.',
    ],
    governanca: [
      { bold: 'O Admin ', text: 'é o único responsável por configurações, regras e integrações do sistema.' },
      { bold: 'O Sistema ', text: 'aplica configurações automaticamente e registra cada mudança em AuditLog.' },
      { bold: 'O Compliance ', text: 'define requisitos de regras que o Admin implementa na ferramenta.' },
    ],
    raciRoles: ['Admin', 'Compliance', 'Sistema'],
    raciActivities: [
      { name: 'Configurar parâmetros', values: ['R', '', ''] },
      { name: 'Configurar integrações', values: ['R', '', ''] },
      { name: 'Criar regras compliance', values: ['R', 'C', ''] },
      { name: 'Simular regras', values: ['R', '', 'C'] },
      { name: 'Consultar auditoria', values: ['R', 'R', ''] },
      { name: 'Registrar audit log', values: ['', '', 'R'] },
    ],
  },
];