// =============================================================================
// TODOS OS PROCESSOS DA PLATAFORMA PAGSMILE — MODELO FORMAL v2.0
// Formato: Identificação, Objetivo, Escopo, Passo a Passo, Regras de Negócio,
// Compliance & Segurança, Governança, Matriz RACI
// =============================================================================

export const PROCESSOS = [

  // ═══════════════════════════════════════════════════════════════════════════
  // 1. CAPTAÇÃO DE LEAD VIA QUESTIONÁRIO
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-001',
    nome: 'Captação de Lead via Questionário Público',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / Marketing / Sistema / IA',
    objetivo: 'Definir o fluxo completo de captação de leads através de questionários públicos (v2 Autocomplete, Completo v1, Simplificado e PIX), garantindo:',
    objetivoItens: [
      'Rastreabilidade ponta a ponta do lead desde o primeiro clique.',
      'Enriquecimento automático de dados via BrasilAPI (autocomplete CNPJ).',
      'Análise automática de qualidade e risco por 3 motores de IA (PRISCILA, Lead Qualifier, Análise de Risco Avançada).',
      'Atribuição imediata ao pipeline comercial com scores e classificações.',
      'Registro completo de atividades (LeadActivity) para auditoria.',
    ],
    escopoInclui: [
      'Geração de links rastreáveis (OnboardingLink) com UTMs e referralCode.',
      'Preenchimento do questionário público pelo cliente potencial.',
      'Autocomplete de CNPJ via BrasilAPI (14+ campos preenchidos automaticamente).',
      'Criação automática de Lead no banco de dados.',
      'Disparo automático de PRISCILA (score 0-100, risco, decisão).',
      'Disparo automático de Lead Qualifier (nível EXCELENTE→INSUFICIENTE).',
      'Disparo automático de Análise de Risco Avançada (iaRiskScore, iaDecision).',
      'Notificação Slack (notifyNewLead) com dados do lead.',
      'Incremento de métricas no OnboardingLink (clicks, submissions, completions).',
    ],
    escopoNaoInclui: [
      'Preenchimento manual pelo comercial (ver Processo Questionário de Reunião).',
      'Processamento por IA de notas de reunião (ver Processo Robô IA).',
      'Captação via Landing Page de Introducer (ver Processo Landing Page).',
      'Criação de proposta (processo subsequente).',
    ],
    steps: [
      { id: '01', resp: 'Comercial', atividade: 'Gera link rastreável na página LinksQuestionariosLeads', decisao: 'Escolhe tipo: v2 Autocomplete, Completo, Simplificado ou PIX', gate: '', sla: '', saida: 'OnboardingLink criado com uniqueCode, commercialAgentName, UTMs', proximo: '02' },
      { id: '02', resp: 'Comercial', atividade: 'Envia link ao cliente potencial via WhatsApp, e-mail ou outro canal', decisao: '', gate: '', sla: '', saida: 'Link enviado + registro de envio (interno)', proximo: '03' },
      { id: '03', resp: 'Cliente', atividade: 'Acessa link público e inicia questionário', decisao: '', gate: '', sla: '', saida: 'OnboardingLink.clickCount++ registrado', proximo: '04' },
      { id: '04', resp: 'Cliente', atividade: 'Preenche CNPJ → autocomplete BrasilAPI preenche 14+ campos', decisao: 'CNPJ válido? Situação cadastral ativa?', gate: 'G1', sla: '', saida: 'Dados da empresa preenchidos automaticamente (Razão Social, Nome Fantasia, CNAE, endereço, sócios, capital social)', proximo: '05' },
      { id: '05', resp: 'Cliente', atividade: 'Preenche etapas restantes do questionário (tipo negócio, volume, taxas, contato)', decisao: 'Todos os campos obrigatórios preenchidos?', gate: 'G2', sla: '', saida: 'Formulário completo com todas as respostas', proximo: '06' },
      { id: '06', resp: 'Cliente', atividade: 'Submete questionário', decisao: '', gate: '', sla: '', saida: 'Submissão confirmada', proximo: '07' },
      { id: '07', resp: 'Sistema', atividade: 'Cria entidade Lead com todos os dados coletados + protocolo único', decisao: '', gate: '', sla: 'Imediato', saida: 'Lead criado (status=questionario_preenchido, protocolo=LEAD-YYYY-NNNNN)', proximo: '08' },
      { id: '08', resp: 'Sistema', atividade: 'Atualiza métricas do OnboardingLink (submissionCount++)', decisao: '', gate: '', sla: 'Imediato', saida: 'OnboardingLink.submissionCount incrementado', proximo: '09' },
      { id: '09', resp: 'IA (PRISCILA)', atividade: 'Executa análise PRISCILA: score de qualidade 0-100, nível de risco, decisão', decisao: 'Score ≥ 70 → alta qualidade; < 40 → baixa qualidade', gate: '', sla: '< 30s', saida: 'Lead atualizado: priscilaQualityScore, priscilaRiskLevel, priscilaDecisionPath', proximo: '10' },
      { id: '10', resp: 'IA (Lead Qualifier)', atividade: 'Executa Lead Qualifier: classifica maturidade do lead', decisao: 'EXCELENTE / BOM / REGULAR / FRACO / INSUFICIENTE', gate: '', sla: '< 30s', saida: 'Lead atualizado: leadQualifierScore, leadQualifierLevel, leadQualifierReport', proximo: '11' },
      { id: '11', resp: 'IA (Risco)', atividade: 'Executa Análise de Risco Avançada: iaRiskScore 0-100, decisão, sugestões', decisao: 'AUTO_APROVAR / REVISAO_MANUAL / REJEITAR', gate: '', sla: '< 60s', saida: 'Lead atualizado: iaRiskScore, iaDecision, iaSuggestions, iaAnalysisReport', proximo: '12' },
      { id: '12', resp: 'Sistema', atividade: 'Notifica Slack com dados do novo lead (notifyNewLead)', decisao: '', gate: '', sla: 'Imediato', saida: 'Mensagem Slack enviada com nome, TPV, score, segmento', proximo: '13' },
      { id: '13', resp: 'Sistema', atividade: 'Cria LeadActivity (tipo: questionário_preenchido)', decisao: '', gate: '', sla: 'Imediato', saida: 'LeadActivity registrada com timestamp e detalhes', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Unicidade de CNPJ: ', text: 'O sistema não bloqueia CNPJ duplicado, mas exibe alertas visuais no pipeline se já existe lead com mesmo CNPJ.' },
      { bold: 'Protocolo único: ', text: 'Cada Lead recebe protocolo no formato LEAD-YYYY-NNNNN, gerado automaticamente, irrevogável.' },
      { bold: 'Autocomplete obrigatório (v2): ', text: 'No questionário v2 Autocomplete, o CNPJ deve ser preenchido primeiro para liberar os demais campos.' },
      { bold: 'Situação cadastral: ', text: 'Se CNPJ retorna situação cadastral ≠ "Ativa", é registrada flag silenciosa SPECIAL_SITUATION no lead.' },
      { bold: 'Score IA paralelo: ', text: 'Os 3 motores de IA executam em paralelo após criação do Lead, sem depender um do outro.' },
      { bold: 'Slack obrigatório: ', text: 'Toda criação de Lead gera notificação Slack via automação notifyNewLead.' },
      { bold: 'OnboardingLink rastreável: ', text: 'Cada link gerado pelo comercial incrementa métricas de click, submission e completion para analytics.' },
      { bold: 'Lead sem questionário: ', text: 'Não é possível criar Lead diretamente pela UI sem passar por um questionário ou formulário interno.' },
    ],
    complianceIntro: 'Segregação de funções garantida:',
    complianceItens: [
      { bold: 'Comercial: ', text: 'gera links e envia, sem acesso a modificar respostas do cliente.' },
      { bold: 'Cliente: ', text: 'preenche questionário, sem acesso ao backoffice.' },
      { bold: 'Sistema/IA: ', text: 'executa scoring automático, sem interferência humana nos algoritmos.' },
      'Trilha de auditoria completa (LeadActivity para cada interação).',
      'Dados do cliente protegidos por autenticação (admin vê, cliente não acessa backoffice).',
      'Retenção de dados conforme LGPD: dados do questionário armazenados junto ao Lead.',
    ],
    governanca: [
      { bold: 'O Comercial ', text: 'é o dono da captação e responsável por gerar e distribuir links corretos.' },
      { bold: 'O Cliente ', text: 'é responsável pela veracidade dos dados informados no questionário.' },
      { bold: 'O Sistema ', text: 'garante processamento automático (IA, notificações, métricas) sem intervenção humana.' },
      { bold: 'A IA ', text: 'atua como consultora: gera scores e sugestões, mas a decisão final cabe ao Comercial.' },
    ],
    raciRoles: ['Comercial', 'Cliente', 'Sistema/IA', 'Admin'],
    raciActivities: [
      { name: 'Gerar link rastreável', values: ['R', '', '', 'A'] },
      { name: 'Enviar link ao cliente', values: ['R', '', '', 'I'] },
      { name: 'Preencher questionário', values: '', values: ['I', 'R', '', ''] },
      { name: 'Autocomplete CNPJ', values: ['', 'R', 'C', ''] },
      { name: 'Criar Lead no banco', values: ['', '', 'R', 'I'] },
      { name: 'Executar PRISCILA', values: ['', '', 'R', 'I'] },
      { name: 'Executar Lead Qualifier', values: ['', '', 'R', 'I'] },
      { name: 'Notificar Slack', values: ['I', '', 'R', 'I'] },
      { name: 'Triagem e contato', values: ['R', '', '', 'A'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. CAPTAÇÃO VIA LANDING PAGE DE INTRODUCER
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-002',
    nome: 'Captação de Lead via Landing Page de Introducer',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / Parcerias / Marketing / Sistema',
    objetivo: 'Definir o fluxo de captação de leads via landing pages co-branded de Introducers (parceiros de indicação), assegurando:',
    objetivoItens: [
      'Rastreabilidade do lead ao Introducer (referralCode automático).',
      'Exibição de taxas corretas por segmento na landing page.',
      'Captura de dados do lead no formulário de fechamento.',
      'Criação automática de Lead + Proposta com taxas do segmento.',
      'Vinculação automática ao comercialAgent do Introducer.',
    ],
    escopoInclui: [
      'Acesso do cliente à landing page /parceiro/{slug}.',
      'Visualização de taxas por segmento (standardRates do Introducer).',
      'Uso da calculadora de taxas interativa.',
      'Preenchimento do formulário de fechamento (FechamentoLandingPage).',
      'Criação de Lead com introducerId e introducerReferralCode.',
      'Criação automática de Proposal com taxas do segmento selecionado.',
      'Redirect para Compliance Dinâmico após submissão.',
    ],
    escopoNaoInclui: [
      'Cadastro do Introducer (ver Processo Gestão de Introducers).',
      'Configuração de taxas do Introducer (admin apenas).',
      'Captação direta sem Introducer (ver Processo Questionário Público).',
    ],
    steps: [
      { id: '01', resp: 'Introducer', atividade: 'Compartilha link /parceiro/{slug} com cliente potencial', decisao: '', gate: '', sla: '', saida: 'Link compartilhado via WhatsApp/e-mail/redes', proximo: '02' },
      { id: '02', resp: 'Cliente', atividade: 'Acessa landing page co-branded (logo Introducer + Pagsmile)', decisao: '', gate: '', sla: '', saida: 'LandingPageEvent (page_view) registrado', proximo: '03' },
      { id: '03', resp: 'Cliente', atividade: 'Navega segmentos e visualiza taxas por segmento', decisao: '', gate: '', sla: '', saida: 'LandingPageEvent (segment_view, segment_info) registrados', proximo: '04' },
      { id: '04', resp: 'Cliente', atividade: 'Utiliza calculadora de taxas para simular custos', decisao: '', gate: '', sla: '', saida: 'LandingPageEvent (calculator_interact) registrado', proximo: '05' },
      { id: '05', resp: 'Cliente', atividade: 'Clica "Contratar" no segmento desejado', decisao: '', gate: '', sla: '', saida: 'LandingPageEvent (cta_contratar) + redirect para FechamentoLandingPage', proximo: '06' },
      { id: '06', resp: 'Cliente', atividade: 'Preenche formulário de fechamento (CNPJ, dados empresa, volume, modelo negócio)', decisao: 'Todos os campos obrigatórios preenchidos?', gate: 'G1', sla: '', saida: 'Formulário completo com segmento selecionado', proximo: '07' },
      { id: '07', resp: 'Sistema', atividade: 'Cria LandingPageLead com dados + introducerId + referralCode', decisao: '', gate: '', sla: 'Imediato', saida: 'LandingPageLead criado', proximo: '08' },
      { id: '08', resp: 'Sistema', atividade: 'Cria Lead vinculado ao Introducer (introducerId, introducerName, referralCode)', decisao: '', gate: '', sla: 'Imediato', saida: 'Lead criado (status=questionario_preenchido)', proximo: '09' },
      { id: '09', resp: 'Sistema', atividade: 'Cria Proposal automaticamente com taxas do segmento (SegmentDefaultRates)', decisao: '', gate: '', sla: 'Imediato', saida: 'Proposal criada (status=enviada, sourceFlow=introducer_landing_page)', proximo: '10' },
      { id: '10', resp: 'Sistema', atividade: 'Vincula Proposal ao Lead (currentProposalId) e atualiza status', decisao: '', gate: '', sla: 'Imediato', saida: 'Lead.currentProposalId preenchido, status=proposta_enviada', proximo: '11' },
      { id: '11', resp: 'Sistema', atividade: 'Redireciona cliente para ComplianceDinamico com model correto', decisao: '', gate: '', sla: 'Imediato', saida: 'Redirect para /ComplianceDinamico?model=xxx&leadId=yyy', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Introducer vinculado automaticamente: ', text: 'O referralCode do Introducer é capturado da URL e persistido no Lead.' },
      { bold: 'Taxas do Introducer: ', text: 'As taxas exibidas na landing page vêm de Introducer.standardRates[], configuradas pelo admin.' },
      { bold: 'Proposta automática: ', text: 'A Proposal é criada com taxas do SegmentDefaultRates (não do Introducer) para manter consistência.' },
      { bold: 'Compliance imediato: ', text: 'O cliente é redirecionado para compliance sem precisar de aceite formal da proposta (aceite implícito ao submeter o formulário).' },
      { bold: 'Analytics completo: ', text: 'Cada interação na landing page gera um LandingPageEvent com sessionId, deviceType, referrer.' },
      { bold: 'Slug único: ', text: 'Cada Introducer tem uniqueLandingPageSlug exclusivo, validado na criação.' },
    ],
    complianceIntro: 'Segregação de funções garantida:',
    complianceItens: [
      { bold: 'Introducer: ', text: 'apenas compartilha link, sem acesso a dados de leads ou taxas reais.' },
      { bold: 'Cliente: ', text: 'preenche formulário, vê taxas de vitrine (não necessariamente as finais).' },
      { bold: 'Sistema: ', text: 'cria Lead + Proposal automaticamente, sem intervenção humana.' },
      { bold: 'Admin: ', text: 'configura taxas do Introducer e SegmentDefaultRates separadamente.' },
      'Analytics de landing page rastreiam comportamento sem dados pessoais identificáveis.',
      'LandingPageEvents registram sessionId anônimo (sem PII).',
    ],
    governanca: [
      { bold: 'O Introducer ', text: 'é responsável por compartilhar o link correto e manter relacionamento com o cliente indicado.' },
      { bold: 'O Comercial ', text: 'define as taxas padrão por segmento e as taxas da landing page do Introducer.' },
      { bold: 'O Sistema ', text: 'garante criação automática de Lead + Proposal sem falhas.' },
      { bold: 'O Admin ', text: 'é responsável por cadastrar, ativar/desativar Introducers e configurar taxas.' },
    ],
    raciRoles: ['Introducer', 'Cliente', 'Sistema', 'Comercial', 'Admin'],
    raciActivities: [
      { name: 'Compartilhar link', values: ['R', '', '', 'I', 'I'] },
      { name: 'Acessar landing page', values: ['', 'R', '', '', ''] },
      { name: 'Preencher formulário', values: ['', 'R', '', '', ''] },
      { name: 'Criar Lead', values: ['', '', 'R', 'I', 'I'] },
      { name: 'Criar Proposal', values: ['', '', 'R', 'I', 'I'] },
      { name: 'Redirect Compliance', values: ['', '', 'R', '', ''] },
      { name: 'Configurar taxas', values: ['', '', '', 'R', 'A'] },
      { name: 'Cadastrar Introducer', values: ['', '', '', 'C', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. CRIAÇÃO E ENVIO DE PROPOSTA COMERCIAL
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-003',
    nome: 'Criação e Envio de Proposta Comercial Personalizada',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / Financeiro / Sistema',
    objetivo: 'Definir o fluxo de criação, validação e envio de propostas comerciais personalizadas, assegurando:',
    objetivoItens: [
      'Taxas validadas contra limites do parceiro adquirente selecionado.',
      'Simulação de rentabilidade (receita × custo = margem) antes do envio.',
      'Versionamento controlado (V1, V2, V3) com lineage completa.',
      'Geração de link público seguro (token 64 caracteres) para acesso do cliente.',
      'Registro de auditoria para cada proposta gerada.',
    ],
    escopoInclui: [
      'Seleção ou pré-preenchimento de dados do Lead.',
      'Seleção de parceiro adquirente (Partner).',
      'Preenchimento de taxas por bandeira × 4 faixas de parcelamento.',
      'Configuração de antecipação (RAV, prazo, % do TPV).',
      'Configuração de taxas complementares (PIX, boleto, antifraude, 3DS, setup, mínimo garantido).',
      'Sobrescrita manual de taxa final por parcela (taxaFinalOverrides).',
      'Validação obrigatória antes de gerar.',
      'Salvamento como rascunho ou geração como enviada.',
      'Criação de AuditLog e atualização do Lead.',
    ],
    escopoNaoInclui: [
      'Propostas Padrão por segmento (ver Processo Propostas Padrão).',
      'Propostas PIX Only (ver Processo Propostas PIX).',
      'Aceite/Recusa pelo cliente (ver Processo Aceite de Proposta).',
    ],
    steps: [
      { id: '01', resp: 'Comercial', atividade: 'Acessa CriarProposta (via "Nova Proposta" ou "Gerar Proposta" do lead)', decisao: 'Vem de lead? Template? Edição?', gate: '', sla: '', saida: 'Formulário carregado (vazio ou pré-preenchido)', proximo: '02' },
      { id: '02', resp: 'Comercial', atividade: 'Seleciona segmento para carregar taxas padrão (SegmentRatesLoader)', decisao: 'Usar taxas padrão ou preencher manualmente?', gate: '', sla: '', saida: 'Taxas base preenchidas por segmento (se selecionado)', proximo: '03' },
      { id: '03', resp: 'Comercial', atividade: 'Preenche dados do cliente (nome, CNPJ, MCC, contato, tipo negócio)', decisao: 'Todos os campos obrigatórios?', gate: 'G1', sla: '', saida: 'CardDadosCliente preenchido e validado', proximo: '04' },
      { id: '04', resp: 'Comercial', atividade: 'Seleciona parceiro adquirente (PartnerSelector)', decisao: 'Parceiro com MCC compatível?', gate: '', sla: '', saida: 'Partner selecionado com taxas base para comparação', proximo: '05' },
      { id: '05', resp: 'Comercial', atividade: 'Preenche taxas de cartão por bandeira × 4 faixas (CardTaxasCartao)', decisao: 'Taxas acima do custo do parceiro?', gate: 'G2', sla: '', saida: '5 bandeiras × 4 faixas preenchidas (visual: vermelho se abaixo do custo)', proximo: '06' },
      { id: '06', resp: 'Comercial', atividade: 'Configura antecipação (CardAntecipacao) e sobrescritas (FinalRateOverridesEditor)', decisao: '', gate: '', sla: '', saida: 'RAV, prazo, % TPV antecipado + overrides por parcela', proximo: '07' },
      { id: '07', resp: 'Comercial', atividade: 'Preenche taxas complementares (CardOutrasTaxas)', decisao: '', gate: '', sla: '', saida: 'PIX, boleto, antifraude, 3DS, setup, mínimo garantido (3 meses)', proximo: '08' },
      { id: '08', resp: 'Comercial', atividade: 'Revisa preview à direita (PropostaPreview + ProfitabilityPanel)', decisao: 'Margem positiva? Rentabilidade OK?', gate: 'G3', sla: '', saida: 'Preview da tabela 1x-21x + simulação de margem', proximo: '09' },
      { id: '09', resp: 'Comercial', atividade: 'Clica "Gerar Proposta" (ou "Salvar Rascunho")', decisao: 'Validação automática: nome, CNPJ 14 dígitos, MCC, contato, tipo negócio, ≥1 taxa cartão', gate: 'G4', sla: '', saida: 'Proposal criada (status=enviada ou rascunho)', proximo: '10' },
      { id: '10', resp: 'Sistema', atividade: 'Gera código (PROP-YYYY-NNNNN) e token público (64 chars)', decisao: '', gate: '', sla: 'Imediato', saida: 'codigo + tokenPublico gerados e persistidos', proximo: '11' },
      { id: '11', resp: 'Sistema', atividade: 'Cria AuditLog + atualiza Lead (currentProposalId, status=proposta_enviada)', decisao: '', gate: '', sla: 'Imediato', saida: 'AuditLog + LeadActivity + Lead atualizados', proximo: '12' },
      { id: '12', resp: 'Comercial', atividade: 'Copia link público e envia ao cliente', decisao: '', gate: '', sla: '', saida: 'Link /PropostaPublica?token=xxx enviado ao cliente', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Validação obrigatória: ', text: 'Nome, CNPJ (14 dígitos), MCC, contato e tipo de negócio são obrigatórios para gerar. Rascunho não exige validação.' },
      { bold: 'Taxas vs. Custo parceiro: ', text: 'O sistema exibe alerta visual (vermelho) se taxa está abaixo do custo do parceiro, mas NÃO bloqueia.' },
      { bold: 'Versionamento: ', text: 'Criar nova versão incrementa version, marca anterior como isCurrentVersion=false, mantém rootProposalId.' },
      { bold: 'Token único: ', text: 'Token público de 64 caracteres alfanuméricos, único por proposta, usado para acesso público.' },
      { bold: 'parseTaxa: ', text: 'Todas as taxas são convertidas de string brasileira (vírgula decimal) para número antes de persistir.' },
      { bold: 'Override de taxa final: ', text: 'O campo taxaFinalOverrides permite sobrescrever visualmente a taxa final por parcela (1-21x) sem alterar a lógica de cálculo.' },
      { bold: 'Proposta PRISCILA: ', text: 'Se ?usePriscila=1, as taxas sugeridas pela IA são auto-preenchidas a partir de priscilaAnalysisReport.taxasSugeridas.' },
    ],
    complianceIntro: 'Segregação de funções e controles:',
    complianceItens: [
      { bold: 'Comercial: ', text: 'cria e envia proposta, define taxas dentro dos limites comerciais.' },
      { bold: 'Sistema: ', text: 'valida campos, gera código/token, registra auditoria automaticamente.' },
      { bold: 'Admin: ', text: 'define parceiros ativos e limites de taxa (PartnerCost).' },
      'Cada proposta gera AuditLog com código, cliente, status e responsável.',
      'Alterações de status do lead são rastreadas via LeadActivity.',
      'Token público não expõe dados internos (apenas carrega proposta por token).',
    ],
    governanca: [
      { bold: 'O Comercial ', text: 'é o dono da proposta e responsável pela precificação e envio.' },
      { bold: 'O Admin ', text: 'define os parceiros e limites de custo que orientam o Comercial.' },
      { bold: 'O Sistema ', text: 'garante integridade dos dados (validação, código único, token, auditoria).' },
      { bold: 'O Financeiro ', text: 'é informado via ProfitabilityPanel (rentabilidade), sem poder de veto na criação.' },
    ],
    raciRoles: ['Comercial', 'Sistema', 'Admin', 'Financeiro'],
    raciActivities: [
      { name: 'Preencher dados do cliente', values: ['R', '', '', ''] },
      { name: 'Selecionar parceiro', values: ['R', '', 'C', ''] },
      { name: 'Definir taxas', values: ['R', '', 'C', 'I'] },
      { name: 'Validar campos', values: ['', 'R', '', ''] },
      { name: 'Gerar código/token', values: ['', 'R', '', ''] },
      { name: 'Criar AuditLog', values: ['', 'R', '', 'I'] },
      { name: 'Atualizar Lead', values: ['', 'R', '', ''] },
      { name: 'Enviar link ao cliente', values: ['R', '', '', 'I'] },
      { name: 'Simular rentabilidade', values: ['R', 'C', '', 'I'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. ACEITE / RECUSA / CONTRAPROPOSTA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-004',
    nome: 'Aceite, Recusa e Contraproposta pelo Cliente',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Cliente / Comercial / Sistema / Compliance',
    objetivo: 'Definir o fluxo de decisão do cliente ao receber uma proposta comercial (personalizada, padrão ou PIX), assegurando:',
    objetivoItens: [
      'Registro de visualização com rastreabilidade (data, hora, sessão).',
      'Aceite digital formal com redirect automático para compliance.',
      'Recusa com motivo obrigatório para retroalimentar o comercial.',
      'Contraproposta estruturada para renegociação.',
      'Notificações Slack em tempo real para cada evento.',
    ],
    escopoInclui: [
      'Acesso à proposta pública via token (PropostaPublica, PropostaPadraoPublica, PropostaPixPublica).',
      'Registro automático de visualização (status enviada → visualizada).',
      'Aceite digital (AceiteModal) com redirect para Compliance.',
      'Recusa com motivo (RecusaModal) e registro de rejectedReason.',
      'Contraproposta (ContrapropostaModal) com sugestão de novas taxas.',
      'Tratamento de propostas expiradas (bloqueio de ações).',
    ],
    escopoNaoInclui: [
      'Criação da proposta (ver Processo Criação de Proposta).',
      'Execução do compliance pós-aceite (ver Processo Compliance).',
      'Geração do contrato (ver Processo Contrato).',
    ],
    steps: [
      { id: '01', resp: 'Cliente', atividade: 'Acessa link público da proposta (/PropostaPublica?token=xxx)', decisao: '', gate: '', sla: '', saida: 'Proposta carregada pelo token', proximo: '02' },
      { id: '02', resp: 'Sistema', atividade: 'Registra visualização: status → "visualizada", cria LeadActivity', decisao: 'Primeira visualização? (sessionStorage idempotente)', gate: '', sla: 'Imediato', saida: 'Proposal.status=visualizada + LeadActivity + Slack notificado', proximo: '03' },
      { id: '03', resp: 'Cliente', atividade: 'Analisa taxas, parcelas, PIX, boleto, antecipação, mínimo garantido', decisao: '', gate: '', sla: '', saida: 'Cliente informado das condições completas', proximo: '04' },
      { id: '04', resp: 'Cliente', atividade: 'Decide: Aceitar, Recusar ou Contrapropor', decisao: 'Proposta expirada? → bloqueio de ações', gate: 'G1', sla: 'Dentro da validade', saida: 'Decisão do cliente', proximo: '05A/05B/05C' },
      { id: '05A', resp: 'Cliente', atividade: 'ACEITAR: confirma aceite no AceiteModal', decisao: '', gate: 'G2', sla: '', saida: 'Proposal.status=aceita, acceptedDate, Lead.status=proposta_aceita', proximo: '06A' },
      { id: '05B', resp: 'Cliente', atividade: 'RECUSAR: informa motivo no RecusaModal', decisao: 'Motivo obrigatório', gate: 'G2B', sla: '', saida: 'Proposal.status=recusada, rejectedDate, rejectedReason', proximo: '06B' },
      { id: '05C', resp: 'Cliente', atividade: 'CONTRAPROPOR: sugere novas taxas no ContrapropostaModal', decisao: '', gate: 'G2C', sla: '', saida: 'Proposal.status=contraproposta, counterProposalDetails', proximo: '06C' },
      { id: '06A', resp: 'Sistema', atividade: 'Notifica Slack (notifyProposalAccepted) + redirect para Compliance', decisao: '', gate: '', sla: 'Imediato', saida: 'Slack + redirect /ComplianceDinamico?model=xxx', proximo: 'FIM (Compliance)' },
      { id: '06B', resp: 'Sistema', atividade: 'Notifica Slack + atualiza Lead.status=proposta_recusada', decisao: '', gate: '', sla: 'Imediato', saida: 'Slack + LeadActivity "proposta_recusada"', proximo: 'FIM' },
      { id: '06C', resp: 'Sistema', atividade: 'Notifica Slack + Lead.status=em_contato_comercial (renegociação)', decisao: '', gate: '', sla: 'Imediato', saida: 'Slack + LeadActivity "proposta_contraproposta"', proximo: 'FIM (Comercial renegocia)' },
    ],
    regrasNegocio: [
      { bold: 'Visualização idempotente: ', text: 'A primeira visualização registra status=visualizada. Acessos subsequentes na mesma sessão não geram novo registro.' },
      { bold: 'Expiração: ', text: 'Se validUntil < data atual e status ∉ {aceita, recusada, contraproposta}, a proposta é exibida mas ações são bloqueadas.' },
      { bold: 'Motivo obrigatório na recusa: ', text: 'O cliente deve informar o motivo (seleção + texto livre opcional) para recusar.' },
      { bold: 'Contraproposta estruturada: ', text: 'O cliente preenche sugestão de taxas que ficam em counterProposalDetails para o Comercial analisar.' },
      { bold: 'Redirect pós-aceite: ', text: 'Após aceitar, o cliente é automaticamente redirecionado para o compliance do segmento correto (resolveComplianceModel).' },
      { bold: 'Analytics: ', text: 'Cada ação (aceite, recusa, contraproposta) gera evento analytics com proposal_id, código, nome, segmento.' },
    ],
    complianceIntro: 'Controles de integridade:',
    complianceItens: [
      'Aceite digital com timestamp completo (acceptedDate ISO).',
      'Recusa com motivo obrigatório para trilha de auditoria.',
      'LeadActivity registra cada decisão com timestamp e ator.',
      'Notificações Slack garantem visibilidade imediata para o time comercial.',
      'Propostas expiradas são exibidas mas com ações bloqueadas (integridade temporal).',
    ],
    governanca: [
      { bold: 'O Cliente ', text: 'é o único decisor: aceita, recusa ou contrapropõe. Nenhuma decisão é forçada.' },
      { bold: 'O Sistema ', text: 'registra a decisão e dispara notificações automaticamente, sem intervenção humana.' },
      { bold: 'O Comercial ', text: 'é informado em tempo real e decide próximos passos (renegociação ou novo contato).' },
    ],
    raciRoles: ['Cliente', 'Sistema', 'Comercial'],
    raciActivities: [
      { name: 'Acessar proposta', values: ['R', '', 'I'] },
      { name: 'Registrar visualização', values: ['', 'R', 'I'] },
      { name: 'Decidir (aceitar/recusar/contrapropor)', values: ['R', '', 'I'] },
      { name: 'Atualizar status', values: ['', 'R', 'I'] },
      { name: 'Notificar Slack', values: ['', 'R', 'I'] },
      { name: 'Redirect Compliance', values: ['', 'R', ''] },
      { name: 'Renegociar (se contraproposta)', values: ['C', '', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. COMPLIANCE / KYC (ONBOARDING)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-005',
    nome: 'Compliance e KYC — Onboarding do Cliente',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Compliance / IA (SENTINEL) / Jurídico / Cliente',
    objetivo: 'Definir o fluxo completo de compliance e KYC para onboarding de novos clientes após aceite da proposta, assegurando:',
    objetivoItens: [
      'Questionário de compliance segmentado (10 templates v4 por vertical de negócio).',
      'Pré-preenchimento automático com dados do Lead (useLeadPrefill).',
      'Upload de documentos obrigatórios com validação de formato/tamanho.',
      'Biometria facial via CAF (Liveness + Facematch).',
      'Scoring de risco em 3 camadas pelo motor Risk Scoring v4.',
      'Análise qualitativa da IA SENTINEL (parecer + recomendação).',
      'Decisão automatizada (subfaixas 1A-3B: aprovação; subfaixa 4: revisão manual; subfaixa 5: bloqueio).',
    ],
    escopoInclui: [
      'Preenchimento do questionário de compliance dinâmico (ComplianceDinamico).',
      'Upload de documentos (DocumentUploadFull).',
      'Biometria facial (Liveness + Facematch via CAF).',
      'Motor Risk Scoring v4: C1 (base segmento) + C2 (variáveis V01-V53) + C3 (enriquecimento E01-E11).',
      'Verificação de bloqueios B01-B10.',
      'Análise SENTINEL em 3 fases.',
      'Decisão automatizada com Rolling Reserve e nível de monitoramento.',
      'Criação de OnboardingCase + ComplianceScore + ComplianceFinding.',
    ],
    escopoNaoInclui: [
      'Criação da proposta (processo anterior).',
      'Geração do contrato (processo subsequente).',
      'Revalidação periódica (ver Processo Revalidação).',
    ],
    steps: [
      { id: '01', resp: 'Cliente', atividade: 'Acessa ComplianceDinamico com model do segmento (redirect pós-aceite)', decisao: '', gate: '', sla: '', saida: 'Questionário carregado com template correto', proximo: '02' },
      { id: '02', resp: 'Sistema', atividade: 'useLeadPrefill carrega dados do Lead para pré-preenchimento', decisao: '', gate: '', sla: 'Imediato', saida: 'Campos pré-preenchidos (CNPJ, Razão Social, endereço, sócios)', proximo: '03' },
      { id: '03', resp: 'Cliente', atividade: 'Preenche perguntas do compliance (agrupadas em steps de 4 perguntas)', decisao: 'Perguntas condicionais (dependsOn) ativam/desativam conforme respostas', gate: '', sla: '', saida: 'Respostas salvas (auto-save + ComplianceSession)', proximo: '04' },
      { id: '04', resp: 'Cliente', atividade: 'Upload de documentos obrigatórios (DocumentUploadFull)', decisao: 'Formatos aceitos: PDF, JPG, PNG. Max 10MB por arquivo.', gate: 'G1', sla: '', saida: 'Documentos enviados e registrados em DocumentUpload', proximo: '05' },
      { id: '05', resp: 'Sistema', atividade: 'Redirect para CAF: Liveness + Facematch (biometria)', decisao: 'Biometria aprovada pela CAF?', gate: 'G2', sla: '< 5 min', saida: 'Resultado da biometria registrado', proximo: '06' },
      { id: '06', resp: 'Sistema', atividade: 'Cria OnboardingCase + ComplianceSession com dados completos', decisao: '', gate: '', sla: 'Imediato', saida: 'OnboardingCase (status=Pendente) + ComplianceSession', proximo: '07' },
      { id: '07', resp: 'IA (Motor v4)', atividade: 'Executa Risk Scoring v4: C1 (base segmento) + C2 (variáveis) + C3 (enriquecimento)', decisao: 'Score final 0-1000. Bloqueios B01-B10 verificados.', gate: 'G3', sla: '< 60s', saida: 'ComplianceScore: score_final, subfaixa, rolling_reserve, monitoramento_nivel', proximo: '08' },
      { id: '08', resp: 'IA (SENTINEL)', atividade: 'Análise qualitativa em 3 fases: questionário, validações externas, score composto', decisao: 'Subfaixas 1A-3B → Aprovado | 4 → Manual | 5 → Bloqueio', gate: 'G4', sla: '< 2 min', saida: 'OnboardingCase.iaDecision + parecer_final + findings', proximo: '09A/09B/09C' },
      { id: '09A', resp: 'Sistema', atividade: 'APROVADO (subfaixas 1A-3B): OnboardingCase.status=Aprovado', decisao: '', gate: '', sla: 'Imediato', saida: 'Status=Aprovado + condicoes_automaticas aplicadas', proximo: 'FIM (Contrato)' },
      { id: '09B', resp: 'Analista', atividade: 'REVISÃO MANUAL (subfaixa 4): analista revisa caso com sugestões da IA', decisao: 'Analista decide: Aprovar, Aprovar com condições ou Recusar', gate: 'G5', sla: '2 DU', saida: 'Decisão manual registrada + manualReviewComments', proximo: 'FIM' },
      { id: '09C', resp: 'Sistema', atividade: 'BLOQUEIO (subfaixa 5 / B01-B10): OnboardingCase.status=Recusado', decisao: '', gate: '', sla: 'Imediato', saida: 'Status=Recusado + bloqueios_ativos registrados', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Template por segmento: ', text: 'Cada um dos 10 segmentos tem seu template de compliance v4 com perguntas específicas.' },
      { bold: 'Score 0-1000: ', text: 'Score final = max(0, min(849, C1+C2+C3)). Apenas bloqueios B01-B10 podem gerar score ≥ 850.' },
      { bold: 'Subfaixas: ', text: '1A (0-149)=Verde Express, 1B (150-249)=Verde, 2A (250-349)=Azul Leve, 2B (350-449)=Azul, 3A (450-549)=Amarelo, 3B (550-649)=Laranja, 4 (650-849)=Vermelho Manual, 5 (850+)=Bloqueio.' },
      { bold: 'Rolling Reserve: ', text: '1A-1B=0%, 2A=5%, 2B=10%, 3A=15%, 3B-4=20%.' },
      { bold: 'Monitoramento: ', text: '1A=PADRÃO, 1B=REFORÇADO_LEVE, 2A-2B=REFORÇADO, 3A=INTENSO, 3B=INTENSO_PLUS, 4=MÁXIMO.' },
      { bold: 'Auto-save: ', text: 'Progresso salvo automaticamente em localStorage + backend (ComplianceSession) a cada mudança.' },
      { bold: 'Biometria obrigatória: ', text: 'Liveness + Facematch via CAF são obrigatórios para finalizar o onboarding.' },
    ],
    complianceIntro: 'Controles regulatórios:',
    complianceItens: [
      'KYC completo: identificação, estrutura societária, UBOs, PLD/AML, sanções.',
      'Verificação de sanções internacionais (OFAC, EU, ONU) via CAF/BDC.',
      'Segregação: IA sugere, analista decide (para revisão manual).',
      'Trilha completa: ComplianceScore, ComplianceFinding, OnboardingCase com timestamps.',
      'Retenção mínima de evidências: 5 anos.',
      'RBAC: acesso aos casos restrito por perfil.',
    ],
    governanca: [
      { bold: 'O Cliente ', text: 'é responsável por fornecer dados e documentos verdadeiros.' },
      { bold: 'A IA (SENTINEL + Motor v4) ', text: 'executa scoring e sugere decisão, sem poder de aprovação final em casos manuais.' },
      { bold: 'O Analista de Compliance ', text: 'é o único que pode decidir casos de subfaixa 4 (revisão manual).' },
      { bold: 'O Sistema ', text: 'garante execução automática para subfaixas 1A-3B e 5 (aprovação/bloqueio automáticos).' },
    ],
    raciRoles: ['Cliente', 'IA/Motor v4', 'Analista Compliance', 'Sistema', 'Comercial'],
    raciActivities: [
      { name: 'Preencher questionário', values: ['R', '', '', '', 'I'] },
      { name: 'Upload documentos', values: ['R', '', '', '', ''] },
      { name: 'Biometria', values: ['R', '', '', '', ''] },
      { name: 'Scoring v4 (C1+C2+C3)', values: ['', 'R', '', 'C', ''] },
      { name: 'Análise SENTINEL', values: ['', 'R', 'C', '', ''] },
      { name: 'Decisão automática (1A-3B, 5)', values: ['', '', '', 'R', 'I'] },
      { name: 'Decisão manual (subfaixa 4)', values: ['', 'C', 'R', '', 'I'] },
      { name: 'Criar OnboardingCase', values: ['', '', '', 'R', 'I'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 6. GERAÇÃO E ASSINATURA DE CONTRATO
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-006',
    nome: 'Geração, Revisão e Assinatura de Contrato',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Jurídico / Comercial / Sistema (IA) / Cliente',
    objetivo: 'Definir o fluxo de geração automática de contrato por IA, revisão pelo comercial, envio e assinatura digital pelo cliente, assegurando:',
    objetivoItens: [
      'Pré-geração automática de contrato por IA (preGenerateContract) com dados do Lead + Proposta.',
      'Herança de taxas da proposta aceita + Rolling Reserve do Scoring v4.',
      'Revisão e complementação pelo comercial no EditorContrato.',
      'Envio de link público seguro para assinatura digital.',
      'Rastreabilidade completa de quem gerou, revisou e assinou.',
    ],
    escopoInclui: [
      'Pré-geração de contrato por IA (preGenerateContract backend function).',
      'Edição e revisão no EditorContrato.',
      'Envio de link público (ContratoPublico).',
      'Assinatura digital pelo cliente.',
      'Registro de datas e responsáveis.',
    ],
    escopoNaoInclui: [
      'Compliance/KYC (processo anterior).',
      'Alteração de tarifas pós-contrato (ver Processo Alteração de Tarifas).',
      'Revalidação periódica de compliance (ver Processo Revalidação).',
    ],
    steps: [
      { id: '01', resp: 'Sistema (IA)', atividade: 'preGenerateContract() gera contrato com dados do Lead + Proposal + OnboardingCase', decisao: '', gate: '', sla: '< 30s', saida: 'Contract criado (status=pre_generated) com taxas, módulos, SLAs', proximo: '02' },
      { id: '02', resp: 'Comercial', atividade: 'Acessa EditorContrato e revisa campos pré-preenchidos', decisao: 'Dados corretos? Campos faltantes?', gate: 'G1', sla: '1 DU', saida: 'Contrato revisado com todos os campos obrigatórios', proximo: '03' },
      { id: '03', resp: 'Comercial', atividade: 'Complementa dados faltantes (representante legal, dados bancários, testemunhas)', decisao: '', gate: '', sla: '', saida: 'Contract.status=ready', proximo: '04' },
      { id: '04', resp: 'Comercial', atividade: 'Envia link público para assinatura digital', decisao: '', gate: '', sla: '', saida: 'Link /ContratoPublico?code=xxx enviado ao cliente', proximo: '05' },
      { id: '05', resp: 'Cliente', atividade: 'Acessa contrato público e revisa cláusulas completas', decisao: '', gate: '', sla: '', saida: 'Contrato visualizado pelo cliente', proximo: '06' },
      { id: '06', resp: 'Cliente', atividade: 'Assina digitalmente o contrato', decisao: '', gate: 'G2', sla: '5 DU', saida: 'Contract.status=signed, signedDate registrada', proximo: '07' },
      { id: '07', resp: 'Sistema', atividade: 'Registra assinatura, atualiza Lead (status=ativado)', decisao: '', gate: '', sla: 'Imediato', saida: 'AuditLog + LeadActivity + Lead.status=ativado', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Pré-geração por IA: ', text: 'A IA preenche automaticamente: cliente, CNPJ, módulos, taxas, SLAs, Rolling Reserve, dados bancários (se disponíveis).' },
      { bold: 'Taxas herdadas: ', text: 'As taxas do contrato vêm exclusivamente da Proposal aceita. Rolling Reserve vem do ComplianceScore.rolling_reserve_percent.' },
      { bold: 'Módulos dinâmicos: ', text: 'Módulos habilitados dependem do tipo de proposta (PIX only → apenas pixRecebimentos; Completa → cartão + PIX + boleto).' },
      { bold: 'Assinatura digital: ', text: 'A assinatura digital é registrada com IP, data/hora e nome do signatário.' },
      { bold: 'Revalidação agendada: ', text: 'Após assinatura, o sistema agenda revalidação periódica de compliance automaticamente.' },
    ],
    complianceIntro: 'Controles contratuais:',
    complianceItens: [
      { bold: 'Comercial: ', text: 'revisa e complementa, mas não pode alterar taxas definidas na proposta aceita.' },
      { bold: 'Cliente: ', text: 'assina digitalmente com registro de IP e timestamp.' },
      { bold: 'Jurídico: ', text: 'define templates de cláusulas padrão (customClauses).' },
      'Trilha de auditoria: quem gerou, quem revisou, quem enviou, quem assinou.',
      'Retenção de contratos assinados: 5 anos mínimo.',
    ],
    governanca: [
      { bold: 'O Sistema (IA) ', text: 'gera o contrato base, sem poder de envio ou assinatura.' },
      { bold: 'O Comercial ', text: 'revisa, complementa e envia — é o dono operacional do contrato.' },
      { bold: 'O Jurídico ', text: 'define os templates e cláusulas padrão, sem responsabilidade de envio.' },
      { bold: 'O Cliente ', text: 'é o único signatário e responsável por aceitar os termos.' },
    ],
    raciRoles: ['Sistema/IA', 'Comercial', 'Jurídico', 'Cliente'],
    raciActivities: [
      { name: 'Pré-gerar contrato', values: ['R', '', 'C', ''] },
      { name: 'Revisar contrato', values: ['', 'R', 'C', ''] },
      { name: 'Complementar dados', values: ['', 'R', '', ''] },
      { name: 'Enviar link público', values: ['', 'R', '', ''] },
      { name: 'Assinar contrato', values: ['', '', '', 'R'] },
      { name: 'Registrar assinatura', values: ['R', '', '', ''] },
      { name: 'Definir cláusulas padrão', values: ['', '', 'R', ''] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 7. PIPELINE COMERCIAL (GESTÃO DO FUNIL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-007',
    nome: 'Gestão do Pipeline Comercial (Kanban)',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / Gestão',
    objetivo: 'Definir o fluxo de gerenciamento do funil de vendas via board Kanban, assegurando:',
    objetivoItens: [
      'Visão panorâmica de todos os leads em cada estágio do funil (7 colunas).',
      'Movimentação drag-and-drop com atualização automática de status e registro de atividade.',
      'Métricas financeiras por coluna (TPV mensal, TPV anual, receita estimada).',
      'Alertas de aging para leads parados em um estágio por muito tempo.',
      'Análise de conversão entre estágios.',
    ],
    escopoInclui: [
      'Visualização Kanban com 7 colunas de funil.',
      'Drag-and-drop para mover leads entre colunas.',
      'Métricas de TPV e receita por coluna.',
      'Alertas de aging (PipelineAgingAlerts).',
      'Gráfico de conversão (PipelineConversionChart).',
      'Busca e filtros de período.',
    ],
    escopoNaoInclui: [
      'Criação de leads (processo anterior).',
      'Criação de propostas (processo separado).',
      'Compliance e contratos (processos subsequentes).',
    ],
    steps: [
      { id: '01', resp: 'Sistema', atividade: 'Leads entram automaticamente na primeira coluna ("Leads Quest. Completo")', decisao: '', gate: '', sla: 'Imediato', saida: 'Lead visível no Kanban com card resumido', proximo: '02' },
      { id: '02', resp: 'Comercial', atividade: 'Visualiza board com 7 colunas, métricas e alertas de aging', decisao: '', gate: '', sla: '', saida: 'Visão panorâmica do funil', proximo: '03' },
      { id: '03', resp: 'Comercial', atividade: 'Arrasta card de lead para coluna seguinte (drag-and-drop)', decisao: '', gate: '', sla: '', saida: 'Lead.status atualizado + LeadActivity criada', proximo: '04' },
      { id: '04', resp: 'Sistema', atividade: 'Atualiza status do Lead, lastInteractionDate e cria LeadActivity', decisao: '', gate: '', sla: 'Imediato', saida: 'Status, data e atividade registrados', proximo: '05' },
      { id: '05', resp: 'Comercial', atividade: 'Monitora alertas de aging e gráfico de conversão', decisao: 'Leads parados? Drop-off alto?', gate: '', sla: '', saida: 'Insights para ação comercial', proximo: 'FIM (ciclo contínuo)' },
    ],
    regrasNegocio: [
      { bold: '7 colunas fixas: ', text: 'Leads (Quest. Completo), Em Contato + Simplificado, Proposta Enviada, Proposta Aceita, Compliance KYC, Contrato Gerado, Perdido.' },
      { bold: 'Drag-and-drop: ', text: 'Cada movimentação atualiza Lead.status para o primeiro status da coluna destino.' },
      { bold: 'Métricas por coluna: ', text: 'TPV/mês, TPV/ano, Receita/mês (2.5%), Receita/ano — calculados em tempo real.' },
      { bold: 'Match inteligente: ', text: 'Contratos e propostas são vinculados ao lead por leadId, CNPJ normalizado ou nome.' },
      { bold: 'Aging alerts: ', text: 'Leads parados acima do limite configurado geram alertas visuais.' },
    ],
    complianceIntro: 'Controles do pipeline:',
    complianceItens: [
      'Cada movimentação gera LeadActivity com timestamp e responsável.',
      'Status do lead é a fonte de verdade para posição no funil.',
      'Acesso restrito a usuários autenticados com role admin.',
    ],
    governanca: [
      { bold: 'O Comercial ', text: 'é o dono do pipeline e responsável por mover leads e manter o funil atualizado.' },
      { bold: 'O Gestor ', text: 'monitora métricas, conversão e aging para otimizar o processo comercial.' },
      { bold: 'O Sistema ', text: 'garante registro automático de cada movimentação.' },
    ],
    raciRoles: ['Comercial', 'Gestor', 'Sistema'],
    raciActivities: [
      { name: 'Mover lead no pipeline', values: ['R', 'I', ''] },
      { name: 'Registrar movimentação', values: ['', '', 'R'] },
      { name: 'Monitorar métricas', values: ['C', 'R', ''] },
      { name: 'Alertas de aging', values: ['I', 'I', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 8. QUESTIONÁRIO DE REUNIÃO (MANUAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-008',
    nome: 'Captação via Questionário de Reunião (Preenchimento Interno)',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / Sistema',
    objetivo: 'Definir o fluxo de captação de leads a partir de reuniões presenciais ou remotas, onde o comercial preenche internamente os dados do cliente, assegurando:',
    objetivoItens: [
      'Captura estruturada de dados obtidos em reuniões.',
      'Criação automática de Lead ao salvar questionário.',
      'Duas variantes: Questionário Completo (5 abas) e Questionário PIX (3 abas).',
    ],
    escopoInclui: [
      'Preenchimento do QuestionarioReuniao (5 abas) ou QuestionarioReuniaoPix (3 abas).',
      'Criação de InternalCommercialQuestionnaire.',
      'Criação automática de Lead vinculado.',
      'Criação de LeadActivity.',
    ],
    escopoNaoInclui: [
      'Processamento por IA de notas de reunião (ver Processo Robô IA).',
      'Preenchimento pelo cliente (ver Processo Questionário Público).',
    ],
    steps: [
      { id: '01', resp: 'Comercial', atividade: 'Realiza reunião com cliente (presencial ou remota)', decisao: '', gate: '', sla: '', saida: 'Informações coletadas (anotações, dados verbais)', proximo: '02' },
      { id: '02', resp: 'Comercial', atividade: 'Acessa QuestionarioReuniao ou QuestionarioReuniaoPix', decisao: 'Tipo: Completo (5 abas) ou PIX (3 abas)', gate: '', sla: '', saida: 'Formulário aberto para preenchimento', proximo: '03' },
      { id: '03', resp: 'Comercial', atividade: 'Preenche abas: Dados Básicos, Negócio, Volume, Taxas Atuais, Desafios', decisao: '', gate: '', sla: '', saida: 'Formulário completo com dados da reunião', proximo: '04' },
      { id: '04', resp: 'Comercial', atividade: 'Clica "Salvar"', decisao: '', gate: 'G1', sla: '', saida: 'InternalCommercialQuestionnaire criado', proximo: '05' },
      { id: '05', resp: 'Sistema', atividade: 'Cria Lead automaticamente com dados extraídos do questionário', decisao: '', gate: '', sla: 'Imediato', saida: 'Lead criado + LeadActivity "questionário_reunião"', proximo: '06' },
      { id: '06', resp: 'Sistema', atividade: 'Lead aparece em QuestionariosLeads (aba Reunião) e PipelineComercial', decisao: '', gate: '', sla: 'Imediato', saida: 'Lead visível no backoffice', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Preenchimento interno: ', text: 'Somente o comercial preenche — o cliente não tem acesso a este formulário.' },
      { bold: '5 abas completas: ', text: 'Dados Básicos (empresa+contato), Detalhes do Negócio, Volume, Taxas Atuais (comparação), Desafios.' },
      { bold: 'Lead automático: ', text: 'Ao salvar, o sistema cria Lead automaticamente com os dados preenchidos.' },
      { bold: 'Botões seletores: ', text: 'Formulário usa botões em vez de dropdowns para seleção rápida durante a reunião.' },
    ],
    complianceIntro: 'Controles internos:',
    complianceItens: [
      'Questionário interno não é acessível por cliente.',
      'Dados preenchidos pelo comercial — responsabilidade de veracidade é do comercial.',
      'LeadActivity registra origem "questionário_reunião" para rastreabilidade.',
    ],
    governanca: [
      { bold: 'O Comercial ', text: 'é o único ator que preenche e é responsável pela qualidade dos dados.' },
      { bold: 'O Sistema ', text: 'garante criação automática de Lead e registro de atividade.' },
    ],
    raciRoles: ['Comercial', 'Sistema'],
    raciActivities: [
      { name: 'Realizar reunião', values: ['R', ''] },
      { name: 'Preencher questionário', values: ['R', ''] },
      { name: 'Criar Lead', values: ['', 'R'] },
      { name: 'Criar LeadActivity', values: ['', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 9. PROCESSAMENTO POR IA (ROBÔ)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-009',
    nome: 'Processamento de Notas de Reunião por IA (Robô)',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / IA / Sistema',
    objetivo: 'Definir o fluxo de extração automática de dados estruturados a partir de texto livre (notas de reunião, transcrições, e-mails) usando IA, assegurando:',
    objetivoItens: [
      'Aceitação de texto desestruturado em qualquer formato.',
      'Extração automática de 15+ campos via InvokeLLM.',
      'Revisão humana obrigatória antes de salvar.',
      'Criação de Lead marcado como origemIA=true.',
    ],
    escopoInclui: [
      'Colagem de texto livre no ProcessMeetingNotes.',
      'Processamento por InvokeLLM (backend processMeetingNotes).',
      'Exibição de formulário pré-preenchido para revisão.',
      'Salvamento e criação de Lead.',
    ],
    escopoNaoInclui: [
      'Preenchimento manual pelo comercial (ver Processo Questionário de Reunião).',
      'Análise automática do Lead por PRISCILA (acontece após criação do Lead).',
    ],
    steps: [
      { id: '01', resp: 'Comercial', atividade: 'Acessa ProcessMeetingNotes e cola texto bruto de anotações', decisao: '', gate: '', sla: '', saida: 'Texto colado no campo de entrada', proximo: '02' },
      { id: '02', resp: 'Comercial', atividade: 'Clica "Processar com IA"', decisao: '', gate: '', sla: '', saida: 'Requisição enviada ao backend', proximo: '03' },
      { id: '03', resp: 'IA (LLM)', atividade: 'InvokeLLM analisa texto e extrai dados estruturados (JSON)', decisao: 'Texto suficiente para extração?', gate: 'G1', sla: '< 30s', saida: 'JSON com 15+ campos: empresa, CNPJ, contato, TPV, taxas, desafios', proximo: '04' },
      { id: '04', resp: 'Sistema', atividade: 'Exibe formulário pré-preenchido (QuestionarioReuniao modo edição)', decisao: '', gate: '', sla: 'Imediato', saida: 'Formulário com dados extraídos pela IA', proximo: '05' },
      { id: '05', resp: 'Comercial', atividade: 'Revisa, corrige e complementa dados extraídos', decisao: 'Dados corretos após revisão?', gate: 'G2', sla: '', saida: 'Formulário revisado e validado pelo comercial', proximo: '06' },
      { id: '06', resp: 'Comercial', atividade: 'Clica "Salvar"', decisao: '', gate: '', sla: '', saida: 'InternalCommercialQuestionnaire (origemIA=true) + Lead criado', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Revisão obrigatória: ', text: 'A IA pré-preenche, mas o comercial DEVE revisar antes de salvar. Não há salvamento automático.' },
      { bold: 'origemIA flag: ', text: 'O questionário gerado é marcado com origemIA=true para rastreabilidade.' },
      { bold: 'Texto desestruturado: ', text: 'A IA aceita texto informal, com abreviações, mistura de idiomas e formato livre.' },
      { bold: 'response_json_schema: ', text: 'O LLM recebe schema JSON com todos os campos esperados para garantir estrutura.' },
    ],
    complianceIntro: 'Controles de qualidade:',
    complianceItens: [
      'IA não cria Lead sozinha — revisão humana obrigatória (human-in-the-loop).',
      'Flag origemIA=true garante rastreabilidade de dados gerados por IA.',
      'O comercial assume responsabilidade pelos dados ao clicar "Salvar".',
    ],
    governanca: [
      { bold: 'A IA ', text: 'atua como assistente: extrai dados mas não decide nem persiste.' },
      { bold: 'O Comercial ', text: 'é o revisor final e responsável pela qualidade dos dados salvos.' },
    ],
    raciRoles: ['Comercial', 'IA (LLM)', 'Sistema'],
    raciActivities: [
      { name: 'Colar notas', values: ['R', '', ''] },
      { name: 'Processar texto', values: ['', 'R', ''] },
      { name: 'Revisar dados', values: ['R', '', ''] },
      { name: 'Salvar e criar Lead', values: ['R', '', 'C'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 10. GESTÃO DE INTRODUCERS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-010',
    nome: 'Gestão de Introducers (Parceiros de Indicação)',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Parcerias / Comercial / Admin',
    objetivo: 'Definir o fluxo de cadastro, configuração e monitoramento de Introducers, assegurando:',
    objetivoItens: [
      'Cadastro completo com referralCode único.',
      'Configuração de taxas padrão por segmento para landing page.',
      'Ativação/desativação de landing pages personalizadas.',
      'Rastreabilidade de leads gerados por cada Introducer.',
      'Convite para portal do Introducer.',
    ],
    escopoInclui: [
      'CRUD completo de Introducers.',
      'Configuração de StandardRates por segmento.',
      'Ativação de landing page com slug único.',
      'Upload de logo da empresa.',
      'Convite para portal do Introducer (InviteIntroducerButton).',
      'Métricas: leads gerados, conversão, receita estimada.',
    ],
    escopoNaoInclui: [
      'Captação via landing page (ver Processo Landing Page).',
      'Comissões e pagamentos a Introducers.',
    ],
    steps: [
      { id: '01', resp: 'Admin', atividade: 'Acessa GestaoIntroducers e clica "Novo Introducer"', decisao: '', gate: '', sla: '', saida: 'IntroducerFormModal aberto', proximo: '02' },
      { id: '02', resp: 'Admin', atividade: 'Preenche dados: nome, tipo, CPF/CNPJ, referralCode (único), contato, comissão', decisao: 'referralCode único?', gate: 'G1', sla: '', saida: 'Dados preenchidos', proximo: '03' },
      { id: '03', resp: 'Admin', atividade: 'Configura taxas padrão por segmento (StandardRatesEditor)', decisao: '', gate: '', sla: '', saida: 'standardRates[] preenchido para N segmentos', proximo: '04' },
      { id: '04', resp: 'Admin', atividade: 'Define slug da landing page e ativa', decisao: '', gate: '', sla: '', saida: 'uniqueLandingPageSlug definido, landingPageActive=true', proximo: '05' },
      { id: '05', resp: 'Admin', atividade: 'Salva Introducer', decisao: '', gate: '', sla: '', saida: 'Introducer criado com todos os dados', proximo: '06' },
      { id: '06', resp: 'Admin', atividade: 'Opcionalmente convida para portal (InviteIntroducerButton)', decisao: 'Convite desejado?', gate: '', sla: '', saida: 'User criado com role=introducer + e-mail enviado', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'referralCode único: ', text: 'Cada Introducer deve ter referralCode único no sistema. Validado na criação.' },
      { bold: 'Slug único: ', text: 'O uniqueLandingPageSlug deve ser único para evitar conflitos de URL.' },
      { bold: 'Taxas por segmento: ', text: 'As taxas configuradas são exibidas na landing page do Introducer, mas NÃO determinam as taxas da proposta final.' },
      { bold: 'Portal do Introducer: ', text: 'O Introducer convidado acessa /IntroducerDashboard com visão restrita de seus leads.' },
    ],
    complianceIntro: 'Controles de parceria:',
    complianceItens: [
      'Apenas Admin pode criar e editar Introducers.',
      'referralCode e slug são validados como únicos.',
      'Portal do Introducer é restrito por role=introducer (RBAC).',
    ],
    governanca: [
      { bold: 'O Admin ', text: 'é o único responsável por cadastrar, configurar e ativar/desativar Introducers.' },
      { bold: 'O Introducer ', text: 'tem acesso restrito ao portal com dados apenas de seus leads indicados.' },
    ],
    raciRoles: ['Admin', 'Introducer', 'Sistema'],
    raciActivities: [
      { name: 'Cadastrar Introducer', values: ['R', '', ''] },
      { name: 'Configurar taxas', values: ['R', '', ''] },
      { name: 'Ativar landing page', values: ['R', '', ''] },
      { name: 'Convidar para portal', values: ['R', '', 'C'] },
      { name: 'Acessar portal', values: ['', 'R', ''] },
      { name: 'Validar unicidade', values: ['', '', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 11. LEAD PIX V4 (MERCHANT/INTERMEDIÁRIO)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-011',
    nome: 'Captação de Lead PIX v4 (Merchant Direto / Intermediário)',
    versao: '2.0.0',
    data: '02/04/2026',
    elaboradoPor: 'Pagsmile — Compliance & Operações',
    area: 'Comercial / Sistema / IA',
    objetivo: 'Definir o fluxo de captação de leads PIX v4 com perfilamento (Merchant Direto vs Intermediário), flags automáticas e scoring, assegurando:',
    objetivoItens: [
      'Questionário adaptativo baseado no perfil (merchant vs intermediário).',
      'Cálculo automático de 11 flags silenciosas para detecção de riscos.',
      'Score 0-100 com label de temperatura (Muito Quente, Quente, Morno, Frio).',
      'Protocolo PIX4-YYYY-NNNNN para rastreabilidade.',
    ],
    escopoInclui: [
      'Questionário PIX v4 (7 steps) com perguntas condicionais.',
      'Autocomplete CNPJ com 14+ campos.',
      'Cálculo de flags: YOUNG_COMPANY, PERSONAL_EMAIL, ACCOUNT_TERMINATED, HIGH_PIX_VOLUME_MEI, TPV_EXCEEDS_REVENUE, CNAE_SEGMENT_MISMATCH, etc.',
      'Score 0-100 com base 40 + bônus - penalidades.',
      'Criação de Lead com questionnaireData completo.',
    ],
    escopoNaoInclui: [
      'Proposta PIX (processo separado).',
      'Compliance PIX (processo separado).',
      'Risk Scoring v4 motor (executado no compliance).',
    ],
    steps: [
      { id: '01', resp: 'Cliente', atividade: 'Acessa LeadPixV4 e seleciona perfil: Merchant Direto ou Intermediário', decisao: 'Perfil determina perguntas condicionais', gate: '', sla: '', saida: 'Perfil selecionado (StepTipoNegocio)', proximo: '02' },
      { id: '02', resp: 'Cliente', atividade: 'Preenche CNPJ → autocomplete BrasilAPI (14+ campos)', decisao: 'Flags calculadas: YOUNG_COMPANY, SPECIAL_SITUATION, CNAE_MISMATCH', gate: '', sla: '', saida: 'Dados empresa + flags silenciosas', proximo: '03' },
      { id: '03', resp: 'Cliente', atividade: 'Preenche modelo de negócio PIX (condicional por perfil)', decisao: 'Merchant: cobrança, presença digital. Intermediário: qty merchants, split.', gate: '', sla: '', saida: 'Flags: ACCOUNT_TERMINATED, MEI_AS_INTERMEDIARY', proximo: '04' },
      { id: '04', resp: 'Cliente', atividade: 'Informa volume PIX (TPV, ticket médio, transações)', decisao: 'Flags: HIGH_PIX_VOLUME_MEI, TPV_EXCEEDS_REVENUE', gate: '', sla: '', saida: 'Volume + flags de volume', proximo: '05' },
      { id: '05', resp: 'Cliente', atividade: 'Seleciona serviços desejados (9 opções PIX) e dados complementares', decisao: '', gate: '', sla: '', saida: 'Serviços + situação atual + urgência', proximo: '06' },
      { id: '06', resp: 'Sistema', atividade: 'Calcula score final: base 40 + bônus (cargo, TPV, serviços) - penalidades (flags)', decisao: 'Score ≥ 80 → Muito Quente, ≥ 60 → Quente, ≥ 40 → Morno, < 40 → Frio', gate: '', sla: 'Imediato', saida: 'Score 0-100 + label + 11 flags', proximo: '07' },
      { id: '07', resp: 'Sistema', atividade: 'Cria Lead com protocolo PIX4-YYYY-NNNNN e questionnaireData completo', decisao: '', gate: '', sla: 'Imediato', saida: 'Lead criado (status=questionario_preenchido)', proximo: '08' },
      { id: '08', resp: 'Sistema', atividade: 'Dispara PRISCILA + Lead Qualifier + Notificação Slack', decisao: '', gate: '', sla: '< 60s', saida: 'IAs executadas + Slack notificado', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: '11 flags silenciosas: ', text: 'YOUNG_COMPANY, PERSONAL_EMAIL, SPECIAL_SITUATION, REGULATED_SECTOR, CNAE_SEGMENT_MISMATCH, ACCOUNT_TERMINATED, MEI_AS_INTERMEDIARY, INTERMEDIARY_WANTS_SPLIT, HIGH_PIX_VOLUME_MEI, TPV_EXCEEDS_REVENUE, HIGH_VOLUME_NO_ANTIFRAUD.' },
      { bold: 'Score base 40: ', text: 'Bônus: cargo executivo +10, TPV≥1M +15, ≥500k +10, ≥100k +5, múltiplos serviços +5, urgência alta +5. Penalidades: flags -5 a -15 cada.' },
      { bold: 'Perguntas condicionais: ', text: 'Intermediário vê perguntas adicionais sobre quantity merchants e split PIX.' },
      { bold: 'Protocolo PIX4: ', text: 'Formato PIX4-YYYY-NNNNN único para leads PIX v4.' },
    ],
    complianceIntro: 'Controles PIX v4:',
    complianceItens: [
      'Flags calculadas automaticamente sem intervenção humana (sem manipulação).',
      'Score transparente: base + bônus - penalidades = resultado final.',
      'Dados do CNPJ enriquecidos via BrasilAPI (fonte pública).',
      'Todas as flags e score persistidos em questionnaireData para auditoria.',
    ],
    governanca: [
      { bold: 'O Cliente ', text: 'preenche dados reais, flags são calculadas automaticamente sem seu conhecimento.' },
      { bold: 'O Sistema ', text: 'calcula flags e score sem interferência humana, garantindo objectividade.' },
      { bold: 'O Comercial ', text: 'é informado dos flags e score para decisão comercial.' },
    ],
    raciRoles: ['Cliente', 'Sistema/IA', 'Comercial'],
    raciActivities: [
      { name: 'Preencher questionário PIX v4', values: ['R', '', ''] },
      { name: 'Calcular flags e score', values: ['', 'R', ''] },
      { name: 'Criar Lead', values: ['', 'R', 'I'] },
      { name: 'Executar PRISCILA', values: ['', 'R', 'I'] },
      { name: 'Triar e contatar', values: ['', '', 'R'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 12. ALTERAÇÃO DE TARIFAS (DO PDF ORIGINAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'PROC-012',
    nome: 'Alteração de Tarifas',
    versao: '2.0.0',
    data: '30/12/2025',
    elaboradoPor: 'João Carlos Olimpio',
    area: 'Comercial / Financeiro / Account Management (AM) / Jurídico / Cliente',
    objetivo: 'Definir o fluxo TO BE (fase 1) para alteração de tarifas solicitada por clientes, assegurando:',
    objetivoItens: [
      'Formalização contratual obrigatória antes de qualquer execução.',
      'Segregação clara de responsabilidades (negociação, formalização, execução).',
      'Cumprimento dos SLAs definidos.',
      'Tratamento controlado de não assinatura, com bloqueio operacional.',
      'Rastreabilidade ponta a ponta, com evidência técnica e registro financeiro.',
    ],
    escopoInclui: [
      'Solicitação de alteração de tarifa pelo cliente.',
      'Negociação comercial.',
      'Confecção de Termo de Alteração.',
      'Coleta e controle de assinatura.',
      'Execução técnica da alteração ou bloqueio.',
      'Comunicação e registro financeiro.',
    ],
    escopoNaoInclui: [
      'Revisão de política global de preços.',
      'Concessões extraordinárias fora do contrato.',
      'Alterações retroativas de tarifas.',
    ],
    steps: [
      { id: '01', resp: 'Cliente → Comercial', atividade: 'Solicita alteração de tarifa', decisao: '', gate: '', sla: '', saida: 'Solicitação recebida (Feishu/e-mail/ticket)', proximo: '02' },
      { id: '02', resp: 'Comercial', atividade: 'Negocia nova tarifa', decisao: 'Sem acordo → Encerrar', gate: 'G0', sla: '', saida: 'Acordo registrado (minuta / e-mail de aceite)', proximo: '03' },
      { id: '03', resp: 'Comercial', atividade: 'Formaliza a alteração e informa Financeiro (ciência)', decisao: 'Financeiro não aprova; apenas registra', gate: '', sla: '', saida: 'Comunicação arquivada (Feishu + evidência)', proximo: '04' },
      { id: '04', resp: 'Comercial → Jurídico', atividade: 'Encaminha solicitação ao Jurídico informando possível bloqueio em caso de não assinatura', decisao: 'Obrigatório incluir: tarifa atual→nova, vigência pretendida, produto/serviço', gate: 'G1', sla: '1 DU', saida: 'Solicitação formal (ID/Protocolo) + aviso de possível bloqueio registrado', proximo: '05' },
      { id: '05', resp: 'Jurídico', atividade: 'Confecciona termo de alteração', decisao: '', gate: '', sla: '1 DU', saida: 'Termo pronto (versão controlada)', proximo: '06' },
      { id: '06', resp: 'Jurídico', atividade: 'Envia termo e inicia coleta de assinatura', decisao: 'Inicia contagem do prazo de assinatura', gate: 'G2', sla: '5 DU', saida: 'Termo enviado + comprovação de envio + status "Aguardando Assinatura"', proximo: '07' },
      { id: '07', resp: 'Cliente', atividade: 'Analisa e assina o termo', decisao: 'Não aceitou → justificar', gate: '', sla: '5 DU', saida: 'Termo assinado OU negativa formal', proximo: '08' },
      { id: '08', resp: 'Comercial', atividade: 'Valida status de assinatura', decisao: 'Se negativa → analisar motivo', gate: 'G3', sla: '1 DU', saida: 'Registro da validação (assinado / não assinado / pendente)', proximo: '09A ou 09B' },
      { id: '09A', resp: 'Comercial → AM', atividade: 'Se assinado: informa AM para alteração', decisao: 'Somente com termo assinado', gate: 'G4', sla: '', saida: 'Ordem formal para execução (ID/Protocolo)', proximo: '10A' },
      { id: '09B', resp: 'Comercial → AM', atividade: 'Se não assinado (prazo expirado): informa AM para bloqueio', decisao: 'Prazo 5 DU estourado ou recusa formal', gate: 'G4B', sla: '', saida: 'Ordem formal de bloqueio + evidência da recusa/prazo', proximo: '10B' },
      { id: '10A', resp: 'AM → Engenharia', atividade: 'Orquestra execução da alteração', decisao: 'Executar com dados finais e vigência', gate: 'G5', sla: '1 DU', saida: 'Ordem enviada + checklist completo', proximo: '11' },
      { id: '10B', resp: 'AM → Engenharia', atividade: 'Orquestra execução do bloqueio', decisao: 'Executar bloqueio e registrar motivo', gate: 'G5B', sla: '1 DU', saida: 'Ordem enviada + checklist completo', proximo: '11' },
      { id: '11', resp: 'Engenharia', atividade: 'Executa (alteração ou bloqueio) e valida', decisao: 'Falha → corrigir e retestar', gate: 'G6', sla: '', saida: 'Evidência técnica (print/log, data/hora, executor)', proximo: '12' },
      { id: '12', resp: 'Engenharia → Comercial/AM', atividade: 'Comunica execução', decisao: '', gate: '', sla: '', saida: 'Confirmação enviada (Feishu)', proximo: '13' },
      { id: '13', resp: 'Financeiro', atividade: 'Recebe conciliação já com alteração/bloqueio', decisao: '', gate: '', sla: '', saida: 'Registro/ciência (conciliação)', proximo: 'FIM' },
    ],
    regrasNegocio: [
      { bold: 'Nenhuma tarifa entra em vigor sem termo assinado.', text: '' },
      { bold: 'A vigência inicia exclusivamente ', text: 'após a coleta de todas as assinaturas.' },
      { bold: 'Bloqueio é opcional, ', text: 'não é regra contratual.' },
      { bold: 'Financeiro não aprova, ', text: 'apenas toma ciência e registra.' },
      { bold: 'Toda comunicação oficial ', text: 'ocorre via Feishu.' },
      { bold: 'Dashboards devem permitir ', text: 'separação clara de tarifas (antes/depois).' },
      { bold: 'AM é o único orquestrador ', text: 'da execução técnica.' },
      { bold: 'Engenharia executa ', text: 'somente mediante ordem formal do AM.' },
      { bold: 'A evidência mínima ', text: 'da execução é print/log do Dash com data/hora e usuário executor.' },
    ],
    complianceIntro: 'Segregação de funções garantida:',
    complianceItens: [
      { bold: 'Comercial: ', text: 'negociação e validação.' },
      { bold: 'Jurídico: ', text: 'formalização contratual.' },
      { bold: 'AM: ', text: 'execução operacional.' },
      { bold: 'Financeiro: ', text: 'ciência e registro.' },
      'Trilha de auditoria completa (quem / quando / o quê).',
      'Retenção mínima de evidências: 5 anos.',
      'Acesso aos registros restrito por perfil (RBAC).',
    ],
    governanca: [
      { bold: 'O Comercial ', text: 'é o dono do relacionamento e da decisão de encaminhar para alteração ou bloqueio.' },
      { bold: 'O Jurídico ', text: 'é o dono da formalização contratual, sem poder de execução.' },
      { bold: 'O AM ', text: 'é o único responsável pela execução operacional, garantindo segregação.' },
      { bold: 'O Financeiro ', text: 'atua exclusivamente como área de ciência e registro, sem poder de veto.' },
      { bold: 'O Cliente ', text: 'é responsável pela decisão final de aceitar ou não as novas condições.' },
    ],
    raciRoles: ['Cliente', 'Comercial', 'Jurídico', 'AM', 'Engenharia', 'Financeiro'],
    raciActivities: [
      { name: 'Solicitar alteração', values: ['R', 'I', '', '', '', ''] },
      { name: 'Negociar tarifa', values: ['C', 'R', '', '', '', ''] },
      { name: 'Informar Financeiro', values: ['', 'R', '', '', '', 'I'] },
      { name: 'Encaminhar Jurídico', values: ['', 'R', 'I', '', '', ''] },
      { name: 'Confeccionar termo', values: ['', '', 'R', '', '', ''] },
      { name: 'Coletar assinatura', values: ['R', 'I', 'R', '', '', ''] },
      { name: 'Validar assinatura', values: ['', 'R', '', '', '', ''] },
      { name: 'Orquestrar execução', values: ['', '', '', 'R', 'I', ''] },
      { name: 'Executar alteração/bloqueio', values: ['', '', '', 'I', 'R', ''] },
      { name: 'Comunicar execução', values: ['', 'I', '', 'I', 'R', ''] },
      { name: 'Registrar conciliação', values: ['', '', '', '', '', 'R'] },
    ],
  },
];