// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  SEED COMPLETO DO CATÁLOGO GLOBAL                                        ║
// ║  Consolida TODAS as informações dos 2 arquivos de referência:           ║
// ║   1) "Pagsmile Pricing Proposal - Roblox.pdf" (preços públicos)         ║
// ║   2) "GLOBAL PAYMENTS PUBLIC VERSION.xlsx" (operacional/compliance)     ║
// ║                                                                          ║
// ║  Popula:                                                                 ║
// ║   - GlobalCountryChannel: 1 linha por país × provider × método          ║
// ║   - GlobalCountryFee: impostos e retenções por país                     ║
// ║                                                                          ║
// ║  Brasil é DESCONSIDERADO conforme decisão do produto (fluxo separado).  ║
// ║  Admin-only. Limpa registros existentes antes de inserir.               ║
// ╚══════════════════════════════════════════════════════════════════════════╝

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// ═══════════════════════════════════════════════════════════════════════════
// 1) CANAIS (GlobalCountryChannel)
// Cada linha = país × provider × método. Mistura dados do XLSX (operacional)
// + PDF Roblox (rates default público). Provider = confidencial (interno).
// ═══════════════════════════════════════════════════════════════════════════

const CHANNELS = [
  // ────────── ARGENTINA ──────────
  { country: 'AR', country_name: 'Argentina', region: 'LATAM', provider: 'PRISMA', payment_method: 'Credit / Debit Card', method_category: 'cards', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Visa, Mastercard, AMEX, Cabal', transaction_limits: "Tied to bank authorization", confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'MID', allowed_hr_industries: ['sport_betting', 'casino'], regulatory_requirements: 'Casino, Betting and Microcredit MUST HAVE local license', default_payin_rate_pct: 3.5, default_payin_fixed: 0, default_payin_fixed_currency: 'ARS', is_active: true },
  { country: 'AR', country_name: 'Argentina', region: 'LATAM', provider: 'RAPIPAGO', payment_method: 'Cash (RapiPago - Pago Fácil)', method_category: 'cash', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: '10,000+ Payment locations', transaction_limits: '30 ~ 5,000,000 ARS', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'HR Merchants', allowed_hr_industries: ['casino', 'sport_betting', 'forex', 'crypto'], regulatory_requirements: 'Casino, Betting and Microcredit SHOULD HAVE local license', default_payin_rate_pct: 5.5, default_payin_fixed: 0, default_payin_fixed_currency: 'ARS', is_active: true },
  { country: 'AR', country_name: 'Argentina', region: 'LATAM', provider: 'KHIPU', payment_method: 'Bank Transfer (Gateway)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Galicia, Santander, BBVA, Macro, Supervielle, ICBC, Ciudad, Nación, Province, Patagonia, Hipotecario, ITAÚ, HSBC, Mercado Pago', transaction_limits: '1 ~ 1,257,000 ARS', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'API', allowed_hr_industries: ['forex', 'crypto', 'casino', 'sport_betting', 'microcredit'], regulatory_requirements: 'Casino, Betting, Microcredit need local license. Adult Content prohibited.', default_payin_rate_pct: 5.5, default_payin_fixed: 0, default_payin_fixed_currency: 'ARS', is_active: true },
  { country: 'AR', country_name: 'Argentina', region: 'LATAM', provider: 'PAGOS360', payment_method: 'DEBIN (Instant Bank Transfer)', method_category: 'bank_transfer', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'All banks', transaction_limits: '1,750 ~ 5,000,000 ARS', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'Both (LR / HR)', allowed_hr_industries: ['forex', 'crypto', 'sport_betting', 'casino'], regulatory_requirements: 'Casino/Betting need local license. Microcredit and Adult Content prohibited.', default_payin_rate_pct: 2.3, default_payin_fixed: 0, default_payin_fixed_currency: 'ARS', is_active: true },
  { country: 'AR', country_name: 'Argentina', region: 'LATAM', provider: 'PAGOS360', payment_method: 'QR Code (Interoperable)', method_category: 'qr_code', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'All wallets (QR Interoperable)', transaction_limits: 'Per bank authorization', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 2, default_payin_fixed: 0, default_payin_fixed_currency: 'ARS', is_active: true },
  { country: 'AR', country_name: 'Argentina', region: 'LATAM', provider: 'BANK NETWORK', payment_method: 'Bank Transfer (Payout)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYOUT', collection_points: 'All Argentinian Banks', transaction_limits: '1 USD - No max', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2, default_payout_fixed: 1, default_payout_fixed_currency: 'USD', is_active: true },

  // ────────── MEXICO ──────────
  { country: 'MX', country_name: 'Mexico', region: 'LATAM', provider: 'KUSHKI', payment_method: 'Credit / Debit Card', method_category: 'cards', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Visa, MC, Carnet', transaction_limits: "Tied to bank authorization", confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'MID', allowed_hr_industries: ['forex', 'sport_betting', 'casino', 'microcredit', 'adult_content'], regulatory_requirements: 'Casino and Microcredit need CNVB authorization. Crypto prohibited.', default_payin_rate_pct: 3.5, default_payin_fixed: 0, default_payin_fixed_currency: 'MXN', is_active: true },
  { country: 'MX', country_name: 'Mexico', region: 'LATAM', provider: 'ETPAY', payment_method: 'SPEI (Bank Transfer)', method_category: 'bank_transfer', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'All SPEI participants', transaction_limits: '1 ~ 400,000 MXN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'HR Merchants', allowed_hr_industries: ['forex', 'sport_betting', 'casino', 'microcredit', 'crypto'], regulatory_requirements: 'Casino and Microcredit need CNVB authorization. Adult Content prohibited.', default_payin_rate_pct: 2, default_payin_fixed: 4, default_payin_fixed_currency: 'MXN', is_active: true },
  { country: 'MX', country_name: 'Mexico', region: 'LATAM', provider: 'ETPAY', payment_method: 'CoDi', method_category: 'bank_transfer', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'All banks (CoDi)', transaction_limits: '1 ~ 400,000 MXN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 2, default_payin_fixed: 4, default_payin_fixed_currency: 'MXN', is_active: true },
  { country: 'MX', country_name: 'Mexico', region: 'LATAM', provider: 'DIGITAL@FEMSA', payment_method: 'OXXO Pay (real time)', method_category: 'cash', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: '20,000+ OXXO stores', transaction_limits: '1 ~ 9,999 MXN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'HR Merchants', allowed_hr_industries: ['sport_betting', 'casino', 'forex'], regulatory_requirements: 'Casino/Microcredit need CNVB. Adult Content prohibited.', default_payin_rate_pct: 4, default_payin_fixed: 4, default_payin_fixed_currency: 'MXN', is_active: true },
  { country: 'MX', country_name: 'Mexico', region: 'LATAM', provider: 'DIGITAL@FEMSA', payment_method: 'OXXO', method_category: 'cash', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: '20,000+ OXXO stores', transaction_limits: '1 ~ 9,999 MXN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 3.5, default_payin_fixed: 4, default_payin_fixed_currency: 'MXN', is_active: true },
  { country: 'MX', country_name: 'Mexico', region: 'LATAM', provider: 'PAYCASH', payment_method: 'Cash (Walmart, 7Eleven, Soriana, etc.)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: '7-24, Walmart, Soriana, Roma, SamsClub, CircleK, CityClub, Bodega Aurrera, Extra, Farmacia del Ahorro, Kiosko, Calimax, Alianza, Financiera Bienestar, Abarrey, Afirme, BBVA, Santander, Banorte, etc.', transaction_limits: '1 ~ 9,999 MXN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', allowed_hr_industries: ['sport_betting', 'casino', 'microcredit'], regulatory_requirements: 'Crypto and Adult Content prohibited.', default_payin_rate_pct: 2.5, default_payin_fixed: 4, default_payin_fixed_currency: 'MXN', is_active: true },
  { country: 'MX', country_name: 'Mexico', region: 'LATAM', provider: 'TODITO', payment_method: 'E-wallet (Todito)', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Todito wallet', transaction_limits: '1 ~ 9,999 MXN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 3, default_payin_fixed: 4, default_payin_fixed_currency: 'MXN', is_active: true },
  { country: 'MX', country_name: 'Mexico', region: 'LATAM', provider: 'ETPAY', payment_method: 'SPEI (Bank Transfer Payout)', method_category: 'bank_transfer', integration_type: 'Via PSP', payin_or_payout: 'PAYOUT', collection_points: 'All SPEI participants', transaction_limits: '1 MXN - 200,000 MXN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2, default_payout_fixed: 4, default_payout_fixed_currency: 'MXN', default_payout_min_amount: 1, default_payout_max_amount: 200000, is_active: true },

  // ────────── COLOMBIA ──────────
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'KUSHKI', payment_method: 'Debit/Credit Card', method_category: 'cards', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Visa, MC', transaction_limits: "Tied to bank authorization", confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'MID', allowed_hr_industries: ['forex', 'sport_betting', 'casino', 'microcredit', 'crypto'], regulatory_requirements: 'Casino and Betting MUST HAVE COLJUEGOS license.', default_payin_rate_pct: 2, default_payin_fixed: 100, default_payin_fixed_currency: 'COP', is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'ACH', payment_method: 'PSE (Bank Transfer)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'All banks', transaction_limits: '1,000 ~ 20,000,000 COP', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'API', allowed_hr_industries: ['forex', 'sport_betting', 'casino', 'microcredit'], regulatory_requirements: 'Casino/Betting need COLJUEGOS. Adult Content and Crypto prohibited.', default_payin_rate_pct: 2.5, default_payin_fixed: 800, default_payin_fixed_currency: 'COP', is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'CASH NETWORK', payment_method: 'Cash (Efecty, Bancolombia, Su Red)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Efecty, Bancolombia, Corresponsal Bancolombia, Su Red', transaction_limits: 'Per channel', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 3, default_payin_fixed: 800, default_payin_fixed_currency: 'COP', is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'WALLET NETWORK', payment_method: 'E-wallet (Daviplata, Nequi, Rappipay, Movii, Dale!, Tpaga)', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Tpaga, Daviplata, Nequi, Rappipay, Movii, Dale!', transaction_limits: 'Per wallet', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 2.5, default_payin_fixed: 800, default_payin_fixed_currency: 'COP', is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'MOVII', payment_method: 'Bre-B (Key & QR)', method_category: 'qr_code', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'All banks', transaction_limits: '1,000 ~ 11,500,000 COP', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', allowed_hr_industries: ['forex', 'sport_betting', 'casino', 'microcredit', 'adult_content'], regulatory_requirements: 'Casino/Betting need COLJUEGOS. Crypto prohibited.', default_payin_rate_pct: 2, default_payin_fixed: 0, default_payin_fixed_currency: 'COP', is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'ACH', payment_method: 'ACH (Bank Transfer Payout)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYOUT', collection_points: 'All banks', transaction_limits: '1 COP - 20,000,000 COP', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2, default_payout_fixed: 2000, default_payout_fixed_currency: 'COP', is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'TPAGA', payment_method: 'Tpaga (eWallet Payout)', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYOUT', collection_points: 'Tpaga wallet', transaction_limits: '1 COP - 10,000,000 COP', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2, default_payout_fixed: 2000, default_payout_fixed_currency: 'COP', is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'NEQUI', payment_method: 'Transfiya (NEQUI & Bank Transfer)', method_category: 'bank_transfer', integration_type: 'Via PSP', payin_or_payout: 'PAYOUT', collection_points: 'NEQUI + banks (Transfiya)', transaction_limits: '1 COP - 2,000,000 COP', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 1, default_payout_fixed: 0, default_payout_fixed_currency: 'COP', default_payout_min_amount: 2000, is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'CASH NETWORK', payment_method: 'Cashout (Cash Payout)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYOUT', collection_points: 'Cash points', transaction_limits: 'Max 1,500,000 COP', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2, default_payout_fixed_currency: 'COP', default_payout_max_amount: 1500000, is_active: true },
  { country: 'CO', country_name: 'Colombia', region: 'LATAM', provider: 'MOVII', payment_method: 'Bre-B (Payout)', method_category: 'qr_code', integration_type: 'Direct', payin_or_payout: 'PAYOUT', collection_points: 'All banks (Bre-B)', transaction_limits: '1,000 COP - 11,550,000 COP', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2, default_payout_fixed: 0, default_payout_fixed_currency: 'COP', default_payout_min_amount: 2000, is_active: true },

  // ────────── CHILE ──────────
  { country: 'CL', country_name: 'Chile', region: 'LATAM', provider: 'KUSHKI', payment_method: 'Webpay (Local debit & credit card)', method_category: 'cards', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Visa, MC, Amex, Diners, RedCompra (all banks)', transaction_limits: "Tied to bank authorization", confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'MID', allowed_hr_industries: ['forex', 'crypto', 'sport_betting', 'casino'], regulatory_requirements: 'Microcredits and Adult Content prohibited.', default_payin_rate_pct: 2.5, default_payin_fixed: 0, default_payin_fixed_currency: 'CLP', is_active: true },
  { country: 'CL', country_name: 'Chile', region: 'LATAM', provider: 'ETPAY', payment_method: 'Direct Bank Transfer (Gateway)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Banco Estado, Banco de Chile, Scotiabank, Santander, BCI, ITAU, Banco Ripley, Coopeuch, Banco Falabella, Banco BICE, Banco Consorcio, Banco Security, HITES, TAPP', transaction_limits: 'Per bank limits', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', allowed_hr_industries: ['forex', 'sport_betting', 'casino', 'adult_content'], regulatory_requirements: 'Microcredits and Crypto prohibited.', default_payin_rate_pct: 2.5, default_payin_fixed: 0, default_payin_fixed_currency: 'CLP', is_active: true },
  { country: 'CL', country_name: 'Chile', region: 'LATAM', provider: 'KHIPU', payment_method: 'Khipu (Bank Transfer)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'All Chilean banks', transaction_limits: 'Per bank', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 2.5, default_payin_fixed: 0, default_payin_fixed_currency: 'CLP', is_active: true },
  { country: 'CL', country_name: 'Chile', region: 'LATAM', provider: 'KLAP', payment_method: 'Cash (Klap Multicaja / Pago46)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Klap Multicaja, Pago46', transaction_limits: 'Per point', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 3, default_payin_fixed: 500, default_payin_fixed_currency: 'CLP', is_active: true },
  { country: 'CL', country_name: 'Chile', region: 'LATAM', provider: 'MACH', payment_method: 'eWallet (MACH, Vita Wallet)', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'MACH, Vita Wallet', transaction_limits: 'Per wallet', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 2.5, default_payin_fixed: 0, default_payin_fixed_currency: 'CLP', is_active: true },
  { country: 'CL', country_name: 'Chile', region: 'LATAM', provider: 'CHEK', payment_method: 'eWallet (Chek)', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Chek', transaction_limits: 'Per wallet', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 2.5, default_payin_fixed: 0, default_payin_fixed_currency: 'CLP', is_active: true },
  { country: 'CL', country_name: 'Chile', region: 'LATAM', provider: 'VITA WALLET', payment_method: 'Vita Wallet (Payout)', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYOUT', collection_points: 'Vita Wallet', transaction_limits: '800 CLP - 8,000,000 CLP', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2, default_payout_fixed: 0, default_payout_fixed_currency: 'CLP', default_payout_min_amount: 800, default_payout_max_amount: 8000000, is_active: true },
  { country: 'CL', country_name: 'Chile', region: 'LATAM', provider: 'BANK NETWORK', payment_method: 'Bank Transfer (Payout)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYOUT', collection_points: 'All Chilean banks', transaction_limits: '350 CLP - No max', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2.5, default_payout_fixed: 0, default_payout_fixed_currency: 'CLP', default_payout_min_amount: 350, is_active: true },

  // ────────── PERU ──────────
  { country: 'PE', country_name: 'Peru', region: 'LATAM', provider: 'IZIPAY', payment_method: 'Credit / Debit Card', method_category: 'cards', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Visa, MC, Amex', transaction_limits: "Tied to bank authorization", confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'MID', allowed_hr_industries: ['forex', 'sport_betting', 'casino'], regulatory_requirements: 'Casino/Betting need MINCETUR. Microcredit, Crypto, Adult Content prohibited.', default_payin_rate_pct: 3, default_payin_fixed: 0, default_payin_fixed_currency: 'PEN', default_payin_min: 4, is_active: true },
  { country: 'PE', country_name: 'Peru', region: 'LATAM', provider: 'IZIPAY', payment_method: 'QR Code (Yape, Plin, Tunki)', method_category: 'qr_code', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Yape, Plin, Tunki', transaction_limits: '1 ~ 500 PEN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'BACK UP', default_payin_rate_pct: 4, default_payin_fixed: 0, default_payin_fixed_currency: 'PEN', default_payin_min: 4, is_active: true },
  { country: 'PE', country_name: 'Peru', region: 'LATAM', provider: 'INTERBANK', payment_method: 'Bank Transfer (Deposit)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'BCP, BBVA, Interbank, Scotiabank', transaction_limits: '1 ~ 30,000 PEN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', allowed_hr_industries: ['forex', 'sport_betting', 'casino', 'microcredit'], regulatory_requirements: 'Casino/Betting need MINCETUR. Crypto and Adult Content prohibited.', default_payin_rate_pct: 3, default_payin_fixed: 4, default_payin_fixed_currency: 'PEN', is_active: true },
  { country: 'PE', country_name: 'Peru', region: 'LATAM', provider: 'CASH NETWORK', payment_method: 'Cash (BCP, BBVA, Interbank, Scotiabank, Kasnet, Tambo)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Agentes BCP, BBVA, Interbank, Scotiabank, Kasnet, Tambo', transaction_limits: 'Per agent', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 3, default_payin_fixed: 4, default_payin_fixed_currency: 'PEN', is_active: true },
  { country: 'PE', country_name: 'Peru', region: 'LATAM', provider: 'WALLET NETWORK', payment_method: 'E-Wallets / QR (Yape, izipayYA, Plin, Ligo, Agora Pay, Kontigo, Interbank, BBVA, Scotiabank, Pago Efectivo)', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Yape, izipayYA (Tunki), Plin, Ligo, Agora Pay, Kontigo, Interbank, BBVA, Scotiabank, Pago Efectivo', transaction_limits: 'Per wallet', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 4, default_payin_fixed: 0, default_payin_fixed_currency: 'PEN', default_payin_min: 4, is_active: true },
  { country: 'PE', country_name: 'Peru', region: 'LATAM', provider: 'BANK NETWORK', payment_method: 'Bank Transfer (Payout)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYOUT', collection_points: 'All Peruvian banks', transaction_limits: '4 PEN - 35,000 PEN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2.5, default_payout_fixed: 0, default_payout_fixed_currency: 'PEN', default_payout_min_amount: 4, default_payout_max_amount: 35000, is_active: true },
  { country: 'PE', country_name: 'Peru', region: 'LATAM', provider: 'WALLET NETWORK', payment_method: 'QR Payment (Payout)', method_category: 'qr_code', integration_type: 'Via PSP', payin_or_payout: 'PAYOUT', collection_points: 'QR network', transaction_limits: '4 PEN - No max', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2.5, default_payout_fixed: 0, default_payout_fixed_currency: 'PEN', default_payout_min_amount: 4, is_active: true },

  // ────────── ECUADOR ──────────
  { country: 'EC', country_name: 'Ecuador', region: 'LATAM', provider: 'KUSHKI', payment_method: 'Credit Card', method_category: 'cards', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Visa, MasterCard, AMEX, Alia (local card)', transaction_limits: '1 ~ 2,500 USD', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'MID', allowed_hr_industries: ['microcredit', 'adult_content'], regulatory_requirements: 'Casino, Betting and Forex prohibited. Microcredit needs local license.', default_payin_rate_pct: 4, default_payin_fixed: 0, default_payin_fixed_currency: 'USD', default_payin_min: 0.7, is_active: true },
  { country: 'EC', country_name: 'Ecuador', region: 'LATAM', provider: 'KUSHKI', payment_method: 'Bank Transfer', method_category: 'bank_transfer', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Banco Pichincha, Banco Guayaquil', transaction_limits: '1 ~ 10,000 USD', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'BACK UP', allowed_hr_industries: ['sport_betting', 'casino', 'forex'], default_payin_rate_pct: 3, default_payin_fixed: 1.6, default_payin_fixed_currency: 'USD', is_active: true },
  { country: 'EC', country_name: 'Ecuador', region: 'LATAM', provider: 'PAYVALIDA', payment_method: 'Bank Transfer (All Banks)', method_category: 'bank_transfer', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'All Ecuadorian Banks', transaction_limits: '1 ~ 10,000 USD', confirmation_time: '1H', operational_status: 'ONLINE', usage_status: 'BACK UP', requires_onboarding: true, onboarding_type: 'Both (LR / HR), API', allowed_hr_industries: ['forex', 'crypto', 'microcredit'], regulatory_requirements: 'Casino, Betting, Adult Content prohibited. Microcredit needs local license. Full KYC required for onboarding.', default_payin_rate_pct: 3, default_payin_fixed: 1.6, default_payin_fixed_currency: 'USD', is_active: true },
  { country: 'EC', country_name: 'Ecuador', region: 'LATAM', provider: 'CASH NETWORK', payment_method: 'Cash (Western Union, Farmacias, etc.)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Western Union, Farmacias 911, Mi Comisariato, Supermercados Tia, Zona Pago, Rianxeira, Farmacias Pharmacys, Farmacias Medicity, Farmacias Económicas, Mi Negocio Efectivo, La 29, Mushuc Runa, Banco Codesarrollo, Mutualista Pichincha, Cooperco, SF, CNT', transaction_limits: '1 ~ 300 USD', confirmation_time: '1H', operational_status: 'ONLINE', usage_status: 'BACK UP', default_payin_rate_pct: 3, default_payin_fixed: 1.6, default_payin_fixed_currency: 'USD', is_active: true },
  { country: 'EC', country_name: 'Ecuador', region: 'LATAM', provider: 'BANK NETWORK', payment_method: 'Bank Transfer (Payout)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYOUT', collection_points: 'All Ecuadorian banks', transaction_limits: '1 USD - No max', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 2.5, default_payout_fixed: 0.8, default_payout_fixed_currency: 'USD', default_payout_min_amount: 1, is_active: true },

  // ────────── COSTA RICA ──────────
  { country: 'CR', country_name: 'Costa Rica', region: 'CENTRAL_AMERICA', provider: 'ONVO', payment_method: 'Credit / Debit Card', method_category: 'cards', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Visa, Mastercard, AMEX', transaction_limits: '500 ~ 1,000,000 CRC', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', regulatory_requirements: 'Microcredits, Crypto and Adult Content prohibited.', default_payin_rate_pct: 4, default_payin_fixed: 0, default_payin_fixed_currency: 'USD', default_payin_min: 1.3, is_active: true },
  { country: 'CR', country_name: 'Costa Rica', region: 'CENTRAL_AMERICA', provider: 'BANK NETWORK', payment_method: 'Bank Transfer (Banco Nacional)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Banco Nacional', transaction_limits: 'Per bank', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 4, default_payin_fixed: 0, default_payin_fixed_currency: 'USD', default_payin_min: 1.3, is_active: true },
  { country: 'CR', country_name: 'Costa Rica', region: 'CENTRAL_AMERICA', provider: 'PAYCASH', payment_method: 'Cash (Banco Nacional, Payser, Puntos Hey)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Puntos Hey, Payser, Banco Nacional, Banco Popular, Banco Promerica, tiendas Ekono', transaction_limits: '1,000 ~ 190,000 CRC', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', allowed_hr_industries: ['sport_betting', 'casino'], regulatory_requirements: 'Microcredits, Crypto, FOREX, Adult Content prohibited.', default_payin_rate_pct: 4, default_payin_fixed: 0, default_payin_fixed_currency: 'USD', default_payin_min: 1.3, is_active: true },

  // ────────── PARAGUAY ──────────
  { country: 'PY', country_name: 'Paraguay', region: 'LATAM', provider: 'BANK NETWORK', payment_method: 'Bank Transfer', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'BCP, Vision Banco SAECA, Banco Regional SAECA, Sudameris Bank, Banco Basa, Ministerio de Hacienda, Bancop', transaction_limits: 'Per bank', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 5.5, default_payin_fixed: 0, default_payin_fixed_currency: 'PYG', is_active: true },

  // ────────── URUGUAY ──────────
  { country: 'UY', country_name: 'Uruguay', region: 'LATAM', provider: 'MORE PAYMENTS (XB)', payment_method: 'Cash (Redpagos)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'RedPagos physical Points only (no app)', transaction_limits: '40 ~ 1,000,000 UYU', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'HR Merchants', allowed_hr_industries: ['forex', 'crypto', 'sport_betting', 'casino'], regulatory_requirements: 'Microcredit and Adult Content prohibited.', default_payin_rate_pct: 2.7, default_payin_fixed: 0, default_payin_fixed_currency: 'UYU', is_active: true },
  { country: 'UY', country_name: 'Uruguay', region: 'LATAM', provider: 'BANK NETWORK', payment_method: 'Bank Transfer (Payout)', method_category: 'bank_transfer', integration_type: 'Via PSP', payin_or_payout: 'PAYOUT', collection_points: 'BROU, Banco Bandes, ITAU, Scotiabank, Banco Santander, BBVA, HSBC, Banco Heritage, Banco Nacion, BANPRO, FORTEX, Redpagos, OCA BLUE, Banco Hipotecario', transaction_limits: 'Per bank', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payout_rate_pct: 1, default_payout_fixed: 0, default_payout_fixed_currency: 'USD', default_payout_min_amount: 1, is_active: true },

  // ────────── BOLIVIA ──────────
  { country: 'BO', country_name: 'Bolivia', region: 'LATAM', provider: 'SINTESIS / PAGOSNET', payment_method: 'QR Code', method_category: 'qr_code', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'All wallets and bank apps', transaction_limits: '1 ~ 69,000 BOB', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'HR Merchants', allowed_hr_industries: ['crypto', 'forex'], regulatory_requirements: 'Casino, Betting, Microcredits, Adult Content prohibited.', default_payin_rate_pct: 5.5, default_payin_fixed: 0, default_payin_fixed_currency: 'BOB', is_active: true },
  { country: 'BO', country_name: 'Bolivia', region: 'LATAM', provider: 'BANK NETWORK', payment_method: 'Bank Transfer', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Banco Mercantil, Banco Nacional de Bolivia, Banco de Crédito de Bolivia, Banco Do Brasil, Banco BISA, Banco Unión, Banco Económico, Banco Solidario, Banco Granadero', transaction_limits: 'Per bank', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 5.5, default_payin_fixed: 0, default_payin_fixed_currency: 'BOB', is_active: true },

  // ────────── EL SALVADOR ──────────
  { country: 'SV', country_name: 'El Salvador', region: 'CENTRAL_AMERICA', provider: 'PAYCASH', payment_method: 'Cash', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Punto Express, Tiendas Galo, Fedecaces, Fedecrece, Superselectos, AirPark, Farmacias Economicas, Pago724, Credicomer, Integral, El Gallo mas Gallo', transaction_limits: 'Per point', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', default_payin_rate_pct: 3, default_payin_fixed: 0, default_payin_fixed_currency: 'USD', default_payin_min: 1, is_active: true },

  // ────────── GUATEMALA ──────────
  { country: 'GT', country_name: 'Guatemala', region: 'CENTRAL_AMERICA', provider: 'PAYCASH', payment_method: 'Cash (Akisi, Super24, BAM, Banco G&T Continental)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Puntos BAM 2000+, Akisi, Super24, Banco G&T Continental', transaction_limits: '12 ~ 7,500 GTQ', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', allowed_hr_industries: ['sport_betting', 'casino'], regulatory_requirements: 'Crypto, Forex and Adult Content prohibited.', default_payin_rate_pct: 3, default_payin_fixed: 0, default_payin_fixed_currency: 'USD', default_payin_min: 1, is_active: true },

  // ────────── PANAMA ──────────
  { country: 'PA', country_name: 'Panama', region: 'CENTRAL_AMERICA', provider: 'CASH NETWORK', payment_method: 'Cash (Western Union, El Machetazo, Super Xtra, Punto Pago)', method_category: 'cash', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Western Union 200+, El Machetazo, Super Xtra, Punto Pago', transaction_limits: '1 ~ 200 USD', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', allowed_hr_industries: ['sport_betting', 'casino'], regulatory_requirements: 'Forex Trading and Crypto merchants not supported.', default_payin_rate_pct: 3, default_payin_fixed: 0, default_payin_fixed_currency: 'USD', default_payin_min: 1, is_active: true },

  // ────────── ASIA (resumo da planilha — Alipay+, KKP, TrueMoney, etc.) ──────────
  { country: 'KR', country_name: 'South Korea', region: 'APAC', provider: 'ALIPAY+', payment_method: 'Kakao Pay', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Kakao Pay wallet', transaction_limits: '1 KRW - 2,000,000 KRW', confirmation_time: 'Real time', operational_status: 'TESTING', usage_status: 'PRIMARY', comments: 'Under Development. Recurring: Yes. Settlement: KRW. KKP cannot support H5 due to local compliance.', is_active: true },
  { country: 'TH', country_name: 'Thailand', region: 'APAC', provider: 'ALIPAY+', payment_method: 'TrueMoney', method_category: 'wallet', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'TrueMoney wallet', transaction_limits: '1 THB - 500,000 THB', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', comments: 'Recurring: Yes. Settlement: THB. TMN does NOT support H5 cashier checkout (only desktop or app).', is_active: true },

  // ────────── AFRICA ──────────
  { country: 'NG', country_name: 'Nigeria', region: 'AFRICA', provider: 'KORAPAY', payment_method: 'Bank Transfer + Debit Cards', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Wema Bank, Sterling Bank, Providus Bank, Mastercard, VISA, Verve', transaction_limits: '100 NGN - 10,000,000 NGN', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, onboarding_type: 'MID', allowed_hr_industries: ['forex', 'casino', 'sport_betting', 'crypto'], regulatory_requirements: 'Separate account and pricing for low vs high risk merchants.', comments: 'Must onboard merchant with channel.', is_active: true },
  { country: 'NG', country_name: 'Nigeria', region: 'AFRICA', provider: 'KORAPAY', payment_method: 'Bank Transfer (Payout)', method_category: 'bank_transfer', integration_type: 'Direct', payin_or_payout: 'PAYOUT', collection_points: 'All Nigerian banks', transaction_limits: '100 NGN - 10,000,000 NGN (daily 100,000,000 NGN)', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', is_active: true },
  { country: 'KE', country_name: 'Kenya', region: 'AFRICA', provider: 'KORAPAY', payment_method: 'Mobile Money (M-Pesa, Airtel, Equitel)', method_category: 'wallet', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'Mpesa, Airtel, Equitel', transaction_limits: '10 KES - 250,000 KES', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, allowed_hr_industries: ['forex', 'casino', 'sport_betting', 'crypto'], regulatory_requirements: 'Separate account/pricing low vs high risk.', is_active: true },
  { country: 'GH', country_name: 'Ghana', region: 'AFRICA', provider: 'KORAPAY', payment_method: 'Mobile Money (MTN Momo, Airtel Tigo)', method_category: 'wallet', integration_type: 'Direct', payin_or_payout: 'PAYIN', collection_points: 'MTN Momo, Airtel Tigo', transaction_limits: '10 GHS - 25,000 GHS', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', requires_onboarding: true, allowed_hr_industries: ['forex', 'casino', 'sport_betting', 'crypto'], is_active: true },

  // ────────── MIDDLE EAST ──────────
  { country: 'SA', country_name: 'Saudi Arabia', region: 'MEA', provider: 'PAYERMAX', payment_method: 'MADA (Debit Cards)', method_category: 'cards', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'MADA network', transaction_limits: 'SAR 0.1 minimum', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', comments: 'Settlement: T+2 weeks, USD, min 1000 USD. FX: XE.COM+2.5%. Chargeback: 10 USD/TRX. Refund: 0 USD.', is_active: true },
  { country: 'SA', country_name: 'Saudi Arabia', region: 'MEA', provider: 'PAYERMAX', payment_method: 'Local Credit Cards (VISA/MC)', method_category: 'cards', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'VISA, Mastercard', transaction_limits: 'SAR 0.1 minimum', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', comments: 'Settlement: T+2 weeks.', is_active: true },
  { country: 'AE', country_name: 'UAE', region: 'MEA', provider: 'PAYERMAX', payment_method: 'Carrier Billing (Etisalat)', method_category: 'carrier_billing', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Etisalat', transaction_limits: 'AED 1 - AED 40', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', comments: 'Settlement: T+2 months. FX: XE.COM+2.5%.', is_active: true },
  { country: 'AE', country_name: 'UAE', region: 'MEA', provider: 'PAYERMAX', payment_method: 'Local Credit Cards (VISA/MC)', method_category: 'cards', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'VISA, Mastercard', transaction_limits: 'AED 0.1 minimum', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', comments: 'Settlement: T+2 weeks.', is_active: true },

  // ────────── TURKEY ──────────
  { country: 'TR', country_name: 'Turkey', region: 'TURKEY', provider: 'PAYTR / PAYNET / PAYBROTHERS / GPAY / CODASHOP', payment_method: 'Local Cards + Bank Transfer', method_category: 'cards', integration_type: 'Via PSP', payin_or_payout: 'PAYIN', collection_points: 'Paytr, Paynet, Paybrothers, gpay, Codashop', transaction_limits: 'Per provider', confirmation_time: 'Real time', operational_status: 'ONLINE', usage_status: 'PRIMARY', is_active: true },
];

// ═══════════════════════════════════════════════════════════════════════════
// 2) IMPOSTOS / RETENÇÕES (GlobalCountryFee)
// Atualiza o seed atual com TODAS as taxas do PDF + complementos da planilha.
// ═══════════════════════════════════════════════════════════════════════════

const FEES = [
  // Argentina
  { country: 'AR', country_name: 'Argentina', tax_type: 'VAT', tax_code: 'VAT', percentage: 21, applies_to: 'processing_fee', label_en: 'VAT: 21% of the processing fee', label_pt: 'IVA: 21% sobre a taxa de processamento', label_zh: '增值税:处理费的 21%' },
  { country: 'AR', country_name: 'Argentina', tax_type: 'GMF', tax_code: 'GMF', percentage: 0.6, applies_to: 'total_amount', label_en: 'GMF: 0.6% applied to the total deposit amount', label_pt: 'GMF: 0,6% sobre o valor total do depósito', label_zh: 'GMF:存款总额的 0.6%' },

  // Mexico
  { country: 'MX', country_name: 'Mexico', tax_type: 'VAT', tax_code: 'VAT', percentage: 16, applies_to: 'processing_fee', label_en: 'VAT: 16% of the processing fee', label_pt: 'IVA: 16% sobre a taxa de processamento', label_zh: '增值税:处理费的 16%' },

  // Colombia
  { country: 'CO', country_name: 'Colombia', tax_type: 'VAT', tax_code: 'VAT', percentage: 19, applies_to: 'processing_fee', label_en: 'VAT: 19% of the processing fee', label_pt: 'IVA: 19% sobre a taxa de processamento', label_zh: '增值税:处理费的 19%' },

  // Chile
  { country: 'CL', country_name: 'Chile', tax_type: 'VAT', tax_code: 'VAT', percentage: 19, applies_to: 'processing_fee', label_en: 'VAT: 19% of the processing fee', label_pt: 'IVA: 19% sobre a taxa de processamento', label_zh: '增值税:处理费的 19%' },

  // Peru
  { country: 'PE', country_name: 'Peru', tax_type: 'VAT', tax_code: 'VAT', percentage: 18, applies_to: 'processing_fee', label_en: 'VAT: 18% of the processing fee', label_pt: 'IVA: 18% sobre a taxa de processamento', label_zh: '增值税:处理费的 18%' },

  // Ecuador
  { country: 'EC', country_name: 'Ecuador', tax_type: 'Withholding', tax_code: 'WH', percentage: 5, applies_to: 'settlement', label_en: '5% withholding tax applied at settlement', label_pt: 'Retenção de 5% aplicada no settlement', label_zh: '结算时扣除 5% 预扣税' },

  // Costa Rica
  { country: 'CR', country_name: 'Costa Rica', tax_type: 'VAT', tax_code: 'VAT', percentage: 13, applies_to: 'processing_fee', label_en: 'VAT: 13% of the processing fee', label_pt: 'IVA: 13% sobre a taxa de processamento', label_zh: '增值税:处理费的 13%' },

  // Bolivia
  { country: 'BO', country_name: 'Bolivia', tax_type: 'VAT', tax_code: 'VAT', percentage: 13, applies_to: 'processing_fee', label_en: 'VAT: 13% of the processing fee', label_pt: 'IVA: 13% sobre a taxa de processamento', label_zh: '增值税:处理费的 13%' },

  // El Salvador
  { country: 'SV', country_name: 'El Salvador', tax_type: 'VAT', tax_code: 'VAT', percentage: 13, applies_to: 'processing_fee', label_en: 'VAT: 13% of the processing fee', label_pt: 'IVA: 13% sobre a taxa de processamento', label_zh: '增值税:处理费的 13%' },

  // Guatemala
  { country: 'GT', country_name: 'Guatemala', tax_type: 'VAT', tax_code: 'VAT', percentage: 12, applies_to: 'processing_fee', label_en: 'VAT: 12% of the processing fee', label_pt: 'IVA: 12% sobre a taxa de processamento', label_zh: '增值税:处理费的 12%' },

  // Panama
  { country: 'PA', country_name: 'Panama', tax_type: 'VAT', tax_code: 'VAT', percentage: 7, applies_to: 'processing_fee', label_en: 'VAT: 7% of the processing fee', label_pt: 'IVA: 7% sobre a taxa de processamento', label_zh: '增值税:处理费的 7%' },

  // Paraguay
  { country: 'PY', country_name: 'Paraguay', tax_type: 'VAT', tax_code: 'VAT', percentage: 10, applies_to: 'processing_fee', label_en: 'VAT: 10% of the processing fee', label_pt: 'IVA: 10% sobre a taxa de processamento', label_zh: '增值税:处理费的 10%' },

  // Uruguay
  { country: 'UY', country_name: 'Uruguay', tax_type: 'VAT', tax_code: 'VAT', percentage: 21, applies_to: 'processing_fee', label_en: 'VAT: 21% of the processing fee', label_pt: 'IVA: 21% sobre a taxa de processamento', label_zh: '增值税:处理费的 21%' },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Forbidden: admin only' }, { status: 403 });
    }

    // Limpa registros existentes (channels + fees) — em lotes pra não bater limite.
    const existingChannels = await base44.asServiceRole.entities.GlobalCountryChannel.list('-created_date', 5000);
    for (const c of existingChannels) await base44.asServiceRole.entities.GlobalCountryChannel.delete(c.id);

    const existingFees = await base44.asServiceRole.entities.GlobalCountryFee.list('-created_date', 500);
    for (const f of existingFees) await base44.asServiceRole.entities.GlobalCountryFee.delete(f.id);

    // Insere novos.
    const channelsTagged = CHANNELS.map(c => ({
      ...c,
      imported_from: `seedGlobalCatalogComplete @ ${new Date().toISOString()}`,
    }));
    const feesTagged = FEES.map(f => ({ ...f, is_active: true }));

    await base44.asServiceRole.entities.GlobalCountryChannel.bulkCreate(channelsTagged);
    await base44.asServiceRole.entities.GlobalCountryFee.bulkCreate(feesTagged);

    return Response.json({
      success: true,
      channels_inserted: channelsTagged.length,
      fees_inserted: feesTagged.length,
      countries_covered: Array.from(new Set(channelsTagged.map(c => c.country))).sort(),
    });
  } catch (e) {
    console.error('seedGlobalCatalogComplete error:', e);
    return Response.json({ error: e.message }, { status: 500 });
  }
});