import React from 'react';
import { ClauseTitle, P } from './ContratoStyles';

export default function ContratoClausulas15a27() {
  return (
    <>
      <ClauseTitle>CLÁUSULA DÉCIMA QUINTA - DO COMPROMISSO ANTICORRUPÇÃO E DE PREVENÇÃO À LAVAGEM DE DINHEIRO</ClauseTitle>
      <P>15.1. As PARTES declaram e garantem, de forma recíproca, que cumprem e continuarão a cumprir, durante toda a vigência deste contrato, todas as leis, regulamentos e normas aplicáveis ao combate à corrupção, ao suborno, à lavagem de dinheiro e ao financiamento do terrorismo (PLD/FT). Isso inclui, mas não se limita à, a Lei nº 12.846/2013 (Lei Anticorrupção) e a Lei nº 9.613/98 (Lei de Lavagem de Dinheiro). A PAGSMILE, em cumprimento de seus deveres regulatórios, comunicará ao Conselho de Controle de Atividades Financeiras (COAF), ao Banco Central do Brasil, ou a outros órgãos que a legislação determinar, todas as operações que possam configurar indícios dos crimes previstos na referida legislação.</P>
      <P>15.2. As PARTES se comprometem, de forma irrevogável, a não praticar, autorizar, prometer ou oferecer, seja de forma direta ou indireta, por meio de seus representantes, prepostos ou quaisquer terceiros agindo em seu nome, qualquer ato que constitua corrupção, suborno ou lavagem de dinheiro, visando obter vantagem indevida para si ou para outrem no âmbito da relação comercial estabelecida por este Contrato ou fora dele.</P>
      <P>15.3. A PAGSMILE reserva-se o direito de rescindir este Contrato Master de forma imediata, por justa causa, sem prejuízo da cobrança de perdas e danos, caso tome conhecimento, por meios idôneos, que o CONTRATANTE, seus sócios, administradores, representantes legais ou terceiros a ele relacionados praticaram atos que violem as normas de anticorrupção e de PLD/FT, especialmente se tais atos tiverem qualquer conexão com os serviços prestados pela PAGSMILE.</P>

      <ClauseTitle>CLÁUSULA DÉCIMA SEXTA - DA RESPONSABILIDADE POR FRAUDES E ATIVIDADES ILÍCITAS</ClauseTitle>
      <P>16.1. O CONTRATANTE assume a responsabilidade civil e financeira integral por quaisquer fraudes, golpes ou atividades ilícitas, quando ficar comprovado, mediante o devido processo de apuração previsto na Cláusula 10.3, que tais eventos se originaram por sua conduta dolosa, por culpa grave, ou que foram negligentemente facilitados por falhas em seus processos operacionais e de segurança. A responsabilidade abrange todas as atividades listadas no Anexo III - Atividades Proibidas, e inclui, de forma exemplificativa, fraudes financeiras como o uso de dados falsos ou cartões clonados; golpes contra consumidores, como a venda de produtos inexistentes ou esquemas de pirâmide; a operação de atividades de apostas não regulamentadas; a prática de lavagem de dinheiro ou financiamento ao terrorismo; a violação de sanções econômicas; a utilização da plataforma para quaisquer atividades criminosas tipificadas em lei; e a violação de direitos de propriedade intelectual.</P>
      <P>16.2. Ao identificar, por meio de seus sistemas de monitoramento ou por denúncia fundamentada, a ocorrência de qualquer das atividades previstas no item 16.1 ou no Anexo III - Atividades Proibidas, a PAGSMILE poderá adotar, a seu exclusivo critério e de forma imediata, as seguintes medidas: suspender preventivamente todas as operações e serviços do CONTRATANTE para aprofundamento da verificação dos fatos; e, caso a gravidade da conduta seja confirmada, rescindir o presente Contrato por justa causa, aplicando as penalidades contratuais e legais cabíveis, sem prejuízo da comunicação dos fatos às autoridades competentes.</P>
      <P>16.3. A responsabilidade financeira do CONTRATANTE, nos casos de fraude e atividades ilícitas, será limitada aos danos materiais diretos e efetivamente comprovados que foram causados à PAGSMILE ou a terceiros em decorrência da conduta imputável ao CONTRATANTE. Ficam expressamente excluídos da apuração da responsabilidade os danos indiretos, lucros cessantes, perda de oportunidade ou danos de natureza hipotética. O montante total da responsabilização do CONTRATANTE, por evento ou série de eventos correlatos, não excederá o limite máximo correspondente a 24 (vinte e quatro) vezes o valor da receita média mensal líquida paga pelo CONTRATANTE à PAGSMILE nos últimos 6 (seis) meses de operação.</P>
      <P>16.4. A responsabilidade do CONTRATANTE pelas consequências de atos fraudulentos ou ilícitos praticados durante a vigência do contrato subsistirá mesmo após a sua extinção. Esta responsabilidade pós-contratual terá um prazo de duração de 36 (trinta e seis) meses, contados a partir da data de término ou rescisão do Contrato, e estará estritamente limitada aos eventos danosos que comprovadamente ocorreram durante a vigência da relação contratual, respeitados os limites e condições estabelecidos na cláusula 16.3.</P>

      <ClauseTitle>CLÁUSULA DÉCIMA SÉTIMA - DA COOPERAÇÃO COM AUTORIDADES PÚBLICAS</ClauseTitle>
      <P>17.1. As PARTES reconhecem seu dever cívico e legal de colaborar com a administração da justiça e com a fiscalização do sistema financeiro, comprometendo-se a cooperar de forma plena, diligente e integral com todas as autoridades competentes que, no exercício de suas atribuições legais, solicitem informações ou providências. Este compromisso de cooperação abrange, de forma exemplificativa, o Banco Central do Brasil, o Ministério Público Federal e Estadual, as Polícias Federal e Civil, a Secretaria da Receita Federal do Brasil, o Conselho de Controle de Atividades Financeiras (COAF) e os órgãos de defesa do consumidor, como o Procon.</P>
      <P>17.2. Na hipótese de recebimento de uma requisição formal de informações por parte de uma autoridade competente, a PARTE notificada se compromete a fornecer os dados e documentos solicitados dentro do prazo legal estipulado, independentemente de a requisição implicar a quebra de sigilo bancário, fiscal ou de dados, desde que a ordem esteja devidamente fundamentada e emane de autoridade com poderes para tanto. A PARTE notificará a outra sobre a existência da requisição, salvo se houver vedação legal ou judicial para tal comunicação.</P>
      <P>17.3. O CONTRATANTE, ao aderir a este Contrato, autoriza expressamente a PAGSMILE a reportar, por iniciativa própria e sem necessidade de consentimento prévio, quaisquer operações ou atividades que sejam consideradas suspeitas de acordo com os critérios estabelecidos na legislação e regulamentação de Prevenção à Lavagem de Dinheiro e Financiamento do Terrorismo (PLD/FT). Este reporte será feito aos órgãos competentes, como o COAF, em cumprimento a um dever legal imposto à PAGSMILE como instituição de pagamento.</P>

      <ClauseTitle>CLÁUSULA DÉCIMA OITAVA - DA RESPONSABILIZAÇÃO POR PENALIDADES E PREJUÍZOS</ClauseTitle>
      <P>18.1. O CONTRATANTE assume a responsabilidade objetiva de indenizar e manter a PAGSMILE indene de quaisquer penalidades, multas, sanções, intercorrências, custos, despesas ou prejuízos de qualquer natureza que a PAGSMILE venha a sofrer e que sejam diretamente decorrentes de conduta dolosa ou culposa do CONTRATANTE em suas operações, ou do descumprimento de suas obrigações contratuais. A responsabilidade abrange, exemplificativamente, multas impostas por Bandeiras, Adquirentes ou órgãos reguladores; penalidades por excesso de Chargeback; sanções por falhas de compliance em PLD/FT ou LGPD; custos com investigações e auditorias; despesas legais e honorários advocatícios em defesas administrativas ou judiciais; prejuízos decorrentes de bloqueios ou suspensões impostos por terceiros; danos à reputação da PAGSMILE; e qualquer outra intercorrência relacionada à atividade do CONTRATANTE.</P>
      <P>18.2. Uma vez apurado e quantificado o prejuízo sofrido pela PAGSMILE, conforme o procedimento aplicável, o CONTRATANTE se obriga a realizar o reembolso integral dos valores despendidos ou perdidos, no prazo máximo de 5 (cinco) dias úteis após o recebimento de notificação escrita e detalhada enviada pela PAGSMILE, que deverá ser acompanhada da documentação comprobatória correspondente.</P>
      <P>18.3. Para garantir a efetividade do reembolso, a PAGSMILE fica autorizada a compensar, de forma automática e independentemente de notificação prévia específica para o ato de compensação, os valores devidos pelo CONTRATANTE a este título com quaisquer saldos disponíveis na Plataforma PAGSMILE e/ou na Conta de Pagamento do CONTRATANTE.</P>
      <P>18.4. Caso os saldos disponíveis na plataforma ou na conta sejam insuficientes para a cobertura integral dos valores devidos, o CONTRATANTE deverá complementar o pagamento da diferença no prazo estipulado no item 18.2. O não pagamento no prazo sujeitará o CONTRATANTE à incidência de multa de 2% (dois por cento) sobre o saldo devedor e juros de mora de 1% (um por cento) ao mês, calculados pro rata die, sem prejuízo de outras medidas cabíveis.</P>
      <P>18.5. A obrigação de responsabilização e reembolso prevista nesta cláusula subsistirá mesmo após o término ou a rescisão do Contrato Master, pelo período de 24 (vinte e quatro) meses, e estará limitada aos eventos que ocorreram durante a vigência do Contrato e cuja responsabilidade, por dolo ou culpa, seja comprovadamente imputável ao CONTRATANTE, observada a extensão do dano efetivamente demonstrado.</P>

      <ClauseTitle>CLÁUSULA DÉCIMA NONA - DO DIREITO DE AUDITORIA E INVESTIGAÇÃO</ClauseTitle>
      <P>19.1. A PAGSMILE terá o direito, mas não a obrigação, de realizar investigações, diligências e auditorias nas operações e nos procedimentos internos do CONTRATANTE, sempre que houver suspeita fundamentada de fraude, violação contratual ou descumprimento de normas regulatórias. Tais situações incluem, sem limitação: a existência de picos de transações suspeitas; o recebimento de denúncias ou alertas de risco de parceiros; a solicitação de uma autoridade competente; ou a identificação de atividades inconsistentes com o perfil do CONTRATANTE.</P>
      <P>19.2. Para a realização da auditoria ou investigação, o CONTRATANTE deverá disponibilizar à PAGSMILE ou a seus auditores designados, mediante notificação prévia com antecedência razoável, acesso a documentos, registros e informações estritamente relacionados ao escopo específico da apuração. O CONTRATANTE se compromete a cooperar plenamente com o processo, fornecendo todas as informações pertinentes de forma ágil e transparente.</P>
      <P>19.3. Os custos diretos da auditoria ou investigação, como honorários de peritos ou auditores externos, serão, em regra, suportados pela PAGSMILE. No entanto, caso o procedimento venha a identificar e comprovar a ocorrência de irregularidades graves, fraudes ou violações dolosas do Contrato que justificaram a diligência, o CONTRATANTE será responsável pelo ressarcimento integral dos custos razoáveis e comprovados incorridos pela PAGSMILE na condução da investigação, autorizando desde já a compensação de tais valores com os saldos mantidos em sua Conta de Pagamento.</P>

      <ClauseTitle>CLÁUSULA VIGÉSIMA - DA PROPRIEDADE INTELECTUAL</ClauseTitle>
      <P>20.1. A PAGSMILE declara ser a única e exclusiva titular de todos os direitos de propriedade intelectual relacionados à Plataforma PAGSMILE, ao aplicativo para celular, aos softwares, APIs, documentações, marcas, logotipos, e a qualquer outro material, tecnologia ou criação desenvolvida ou disponibilizada pela PAGSMILE no âmbito da prestação dos serviços. Isso inclui, mas não se limita a, direitos autorais, patentes, marcas, desenhos industriais, segredos comerciais e know-how.</P>
      <P>20.2. O presente Contrato concede ao CONTRATANTE, em caráter pessoal, não exclusivo, intransferível e revogável, uma licença de uso dos serviços e da plataforma da PAGSMILE. Esta licença está estritamente limitada ao uso das funcionalidades contratadas, para os fins previstos neste instrumento, e perdurará apenas durante a vigência do Contrato. Fica vedada ao CONTRATANTE qualquer forma de engenharia reversa, descompilação, cópia, modificação, sublicenciamento ou transferência dos direitos de uso a terceiros.</P>
      <P>20.3. O CONTRATANTE assume total responsabilidade por quaisquer perdas, danos ou custos, incluindo honorários advocatícios, que a PAGSMILE venha a sofrer em decorrência de reclamações de terceiros baseadas na alegação de que o conteúdo, as marcas, os produtos ou os serviços ofertados pelo CONTRATANTE em sua própria plataforma violam direitos de propriedade intelectual de outrem. O CONTRATANTE se compromete a indenizar e manter a PAGSMILE indene de tais reclamações.</P>
      <P>20.4. Fica estabelecido entre as PARTES que toda e qualquer propriedade intelectual, incluindo, mas não se limitando a, softwares, algoritmos, metodologias, processos ou qualquer outra criação intelectual, que seja desenvolvida, concebida ou aprimorada no âmbito da parceria estabelecida por este Contrato, ainda que de forma conjunta ou em decorrência de sugestões ou necessidades do CONTRATANTE, será de propriedade única e exclusiva da PAGSMILE. A PAGSMILE terá o direito irrestrito de registrar, utilizar, ceder, licenciar e explorar comercialmente tal propriedade intelectual como melhor lhe aprouver, sem que seja devida qualquer remuneração, royalty ou contrapartida ao CONTRATANTE.</P>

      <ClauseTitle>CLÁUSULA VIGÉSIMA PRIMEIRA - DO BLOQUEIO E DA SUSPENSÃO DE SERVIÇOS</ClauseTitle>
      <P>21.1. A PAGSMILE poderá, e em alguns casos deverá, proceder ao bloqueio imediato da conta e à suspensão de todos os serviços prestados ao CONTRATANTE, sem a necessidade de notificação prévia, na ocorrência de hipóteses objetivas que indiquem risco grave e iminente à segurança do sistema financeiro ou a terceiros. Tais hipóteses incluem: a detecção de transações com características evidentes e inequívocas de lavagem de dinheiro; a identificação de padrões que se amoldem ao financiamento ao terrorismo; o processamento comprovado de transações relacionadas a atividades criminosas; a utilização confirmada da plataforma para a aplicação de golpes contra consumidores; a manutenção de um score de risco superior a 95% (noventa e cinco por cento) por mais de 48 horas; o recebimento de uma determinação expressa de bloqueio por parte de autoridades judiciais ou administrativas competentes; a confirmação de que a segurança da conta foi comprometida por ação ou omissão do CONTRATANTE; o fornecimento comprovado de informações cadastrais falsas ou documentos fraudulentos no processo de credenciamento ou atualização; ou a identificação de qualquer atividade listada como proibida no Anexo III.</P>
      <P>21.2. Após a efetivação de um bloqueio, o CONTRATANTE poderá solicitar o desbloqueio mediante a apresentação de justificativas e documentos que comprovem a regularidade de sua situação ou a legitimidade das operações questionadas. A PAGSMILE se compromete a analisar os pedidos de desbloqueio com a devida celeridade, em um prazo de até 10 (dez) dias úteis, garantindo ao CONTRATANTE o direito de apresentar sua defesa e seus esclarecimentos, em conformidade com o procedimento de apuração previsto neste contrato.</P>

      <ClauseTitle>CLÁUSULA VIGÉSIMA SEGUNDA - DA LIMITAÇÃO DE RESPONSABILIDADE</ClauseTitle>
      <P>22.1. A responsabilidade da PAGSMILE está adstrita à prestação dos serviços de tecnologia e pagamento nos termos deste Contrato. Desta forma, a PAGSMILE não será, em nenhuma hipótese, responsável por eventos que fujam ao seu controle direto e que sejam inerentes à complexidade do ecossistema de pagamentos. Isso inclui, especificamente: as decisões de aprovação ou recusa de transações tomadas por adquirentes, bandeiras ou bancos emissores, com base em suas próprias políticas de risco; as alterações unilaterais nas regras, regulamentos ou políticas operacionais de terceiros integrantes do arranjo de pagamento; a indisponibilidade ou lentidão de redes de telecomunicações públicas ou privadas; as falhas de segurança ou operacionais que ocorram exclusivamente nos sistemas, servidores ou ambiente tecnológico do CONTRATANTE ou de terceiros por ele contratados; os atos de império de autoridades governamentais que afetem a prestação dos serviços; as decisões judiciais que imponham restrições ou bloqueios às operações; e as fraudes que sejam originadas e consumadas exclusivamente no ambiente do CONTRATANTE, sem que haja falha de segurança comprovada na plataforma PAGSMILE.</P>
      <P>22.2. Em nenhuma circunstância a responsabilidade total da PAGSMILE por quaisquer danos diretos decorrentes deste Contrato excederá o valor total das taxas pagas pelo CONTRATANTE à PAGSMILE nos 6 (seis) meses anteriores ao evento que deu causa ao dano. Fica expressamente acordado que a PAGSMILE não será responsável, sob qualquer hipótese, por lucros cessantes, perda de receita, perda de dados, interrupção de negócios, ou por quaisquer danos indiretos, especiais, incidentais, consequenciais ou punitivos, ainda que tenha sido avisada da possibilidade de tais danos.</P>

      <ClauseTitle>CLÁUSULA VIGÉSIMA TERCEIRA - DAS OBRIGAÇÕES FISCAIS E TRIBUTÁRIAS</ClauseTitle>
      <P>23.1. Cada PARTE será exclusiva e individualmente responsável pelo cumprimento de todas as suas obrigações fiscais e pelo recolhimento dos tributos que incidam ou venham a incidir sobre suas respectivas atividades no âmbito deste Contrato. A PAGSMILE arcará com o ônus decorrente da incidência de todos os emolumentos, taxas e impostos federais, estaduais e municipais, bem como as contribuições sociais, previdenciárias e fundiárias, que eventualmente decorram diretamente da prestação de seus serviços aqui contratados.</P>
      <P>23.2. A PAGSMILE responsabilizar-se-á pelo cumprimento de todas as exigências das repartições competentes em razão de suas obrigações tributárias, arcando de imediato com toda e qualquer despesa, tanto no que se refere à defesa, quanto em relação aos ônus decorrentes de eventuais condenações em processos administrativos ou judiciais de natureza fiscal movidos contra si. Caso o poder público, por qualquer motivo, acione diretamente o CONTRATANTE para exigir um tributo de responsabilidade da PAGSMILE, esta se compromete a assumir a defesa e a arcar com todos os custos, mantendo o CONTRATANTE integralmente indene.</P>

      <ClauseTitle>CLÁUSULA VIGÉSIMA QUARTA - DA OBRIGAÇÃO DE NÃO SOLICITAÇÃO (NON-SOLICITATION)</ClauseTitle>
      <P>24.1. Durante toda a vigência do presente Contrato Master e por um período subsequente de 24 (vinte e quatro) meses após o seu término ou rescisão, por qualquer motivo, o CONTRATANTE assume a obrigação de não abordar, aliciar, contratar ou tentar contratar, seja de forma direta ou indireta, por si ou por intermédio de terceiros, bem como de não induzir, solicitar ou encorajar a rescisão do vínculo profissional de qualquer empregado, prestador de serviço, executivo ou colaborador que ocupe ou tenha ocupado uma posição chave na estrutura da PAGSMILE. Esta vedação aplica-se apenas aos profissionais com os quais o CONTRATANTE tenha tido contato direto em razão da execução deste contrato. A obrigação não será aplicável caso a contratação ocorra em resposta a uma oferta pública de emprego (anúncio geral) e sem aliciamento direto, ou mediante autorização prévia e expressa da PAGSMILE.</P>
      <P>24.2. A violação da obrigação de não solicitação estabelecida nesta Cláusula sujeitará o CONTRATANTE ao pagamento de uma multa de natureza não ressarcitória e não compensatória, fixada no valor de R$ 150.000,00 (cento e cinquenta mil reais) por cada profissional contratado em violação a este dispositivo. O pagamento desta multa não exclui o direito da PAGSMILE de pleitear, em via judicial ou arbitral, a reparação por eventuais perdas e danos adicionais que comprovadamente venha a sofrer em decorrência da referida violação.</P>

      <ClauseTitle>CLÁUSULA VIGÉSIMA QUINTA - DO CASO FORTUITO E DA FORÇA MAIOR</ClauseTitle>
      <P>25.1. Nenhuma das PARTES será responsabilizada pelo inadimplemento de suas obrigações se este decorrer diretamente de um evento de caso fortuito ou força maior, nos termos do artigo 393 do Código Civil, entendido como o evento necessário, cujos efeitos não era possível evitar ou impedir. Para os fins deste Contrato, consideram-se como tais eventos, de forma exemplificativa: pandemias ou emergências sanitárias de larga escala, formalmente declaradas pela Organização Mundial da Saúde (OMS); ataques cibernéticos massivos e coordenados que afetem a integridade do sistema financeiro nacional; falhas sistêmicas generalizadas do Sistema de Pagamentos Brasileiro (SPB); alterações regulatórias supervenientes que tornem a prestação dos serviços objetivamente impossível; decisões judiciais ou administrativas de efeito geral que suspendam as atividades do setor; eventos climáticos extremos de grande magnitude que afetem a infraestrutura crítica de energia ou telecomunicações do país; estado de guerra, atos de terrorismo ou comoção civil generalizada; e greves gerais que paralisem o sistema bancário nacional.</P>
      <P>25.2. Se o evento de força maior ou caso fortuito e seus efeitos perdurarem por um período contínuo superior a 90 (noventa) dias, tornando a execução do Contrato ou de um Módulo específico inviável, qualquer uma das PARTES poderá optar por rescindir o Contrato Master ou o Módulo afetado, sem a imposição de qualquer ônus, multa ou penalidade. A rescisão deverá ser comunicada por escrito à outra PARTE, com uma antecedência mínima de 30 (trinta) dias.</P>

      <ClauseTitle>CLÁUSULA VIGÉSIMA SEXTA - DAS DISPOSIÇÕES GERAIS</ClauseTitle>
      <P>26.1. O presente Contrato Master, juntamente com todos os seus Anexos, que são parte integrante e indissociável deste, constitui o acordo integral e completo de vontades entre as PARTES. Este instrumento substitui e revoga todos e quaisquer acordos, entendimentos, negociações ou propostas anteriores, sejam eles verbais ou escritos, que versem sobre o mesmo objeto.</P>
      <P>26.2. Todas as notificações, comunicações, solicitações ou outros avisos requeridos ou permitidos por este Contrato deverão ser feitos por escrito e serão considerados devidamente entregues quando enviados por e-mail com confirmação de leitura para os endereços eletrônicos designados pelas PARTES no Quadro-Resumo, ou por carta registrada com aviso de recebimento para os endereços físicos ali constantes. As PARTES comprometem-se a manter seus dados de contato sempre atualizados, sob pena de serem consideradas válidas as comunicações enviadas para os últimos endereços informados.</P>
      <P>26.3. Este Contrato Master será interpretado e regido em todos os seus aspectos pelas leis da República Federativa do Brasil, sendo a legislação brasileira a única aplicável para dirimir qualquer questão ou controvérsia oriunda deste instrumento.</P>
      <P>26.4. Fica reiterado que os Anexos formam um corpo único com este Contrato Master. Em caso de conflito entre uma disposição contida no corpo principal do contrato e uma disposição específica de um Anexo, prevalecerá a norma do Anexo, por ser especial em relação ao módulo de serviço que regula.</P>

      <ClauseTitle>CLÁUSULA VIGÉSIMA SÉTIMA - DO FORO</ClauseTitle>
      <P>27.1. Para a solução de quaisquer controvérsias, litígios ou demandas judiciais decorrentes deste Contrato Master ou de seus Anexos, as PARTES elegem, de comum acordo, o Foro Central da Comarca da Capital do Estado de São Paulo. As PARTES renunciam expressamente a qualquer outro foro, por mais privilegiado que seja ou venha a ser, sem prejuízo da faculdade legal de o CONTRATANTE, quando a lei assim o permitir em hipóteses específicas, optar pelo foro de seu domicílio.</P>
    </>
  );
}