import React from 'react';
import { ClauseTitle, P } from './ContratoStyles';

export default function ContratoClausulas1a4() {
  return (
    <>
      <ClauseTitle>CLÁUSULA PRIMEIRA - DO OBJETO CONTRATUAL E DOS MÓDULOS DE SERVIÇO</ClauseTitle>

      <P>1.1. O presente Contrato Master tem por objeto a prestação de serviços de Gateway, Orquestrador de Pagamento, API PIX e API Cartão para Transações Financeiras com Solução Antifraude, bem como os serviços de Abertura e Manutenção de Conta de Pagamento pela PIN BANK ao CONTRATANTE. A prestação de serviços será regida pelas condições gerais e específicas detalhadas no corpo deste instrumento e nos seus anexos, que, em conjunto, formam a integralidade do acordo de vontades entre as PARTES. A estrutura de serviços é modular, permitindo ao CONTRATANTE a seleção de funcionalidades conforme sua necessidade operacional e estratégica, consolidando em um único instrumento jurídico a relação de parceria tecnológica e financeira.</P>

      <P>1.2. Os serviços objeto deste Contrato Master serão pormenorizados em anexos específicos, denominados Módulos de Serviço, os quais são partes integrantes e inseparáveis deste instrumento para todos os fins de direito. A estrutura modular compreende, de forma não exaustiva, o detalhamento dos serviços de processamento de transações financeiras com solução antifraude, incluindo roteamento inteligente de transações, tokenização e ferramentas de prevenção a fraudes, consignado no Anexo I-A – Módulo Subadquirência / Gateway / Orquestrador / API Cartão / Antifraude. Adicionalmente, o instrumento contempla os serviços de abertura e manutenção de conta de pagamento digital, gestão de saldos, transferências e liquidação de recebíveis, especificados no Anexo I-B – Módulo Conta (Conta de Pagamento / Conta Liquidação). De igual modo, os serviços de API Pix para fins de cobrança, permitindo a geração de QR Codes e a conciliação automática de pagamentos instantâneos, estão detalhados no Anexo I-C – Módulo Cobrança Pix (API Pix para cobrança). As PARTES reconhecem que outros módulos poderão ser desenvolvidos e ofertados pela PIN BANK, os quais, se contratados pelo CONTRATANTE, serão formalizados por meio de Anexo específico, que aderirá aos termos e condições deste Contrato Master.</P>

      <P>1.3. A contratação de qualquer módulo de serviço, seja no ato da assinatura deste instrumento ou em momento posterior, implica na aceitação plena, irrestrita e irrevogável de todas as condições estabelecidas no corpo deste Contrato Master, no Anexo específico do módulo contratado e nos demais Anexos aplicáveis. O conjunto de documentos forma um todo unitário e coeso, devendo suas cláusulas serem interpretadas de forma sistemática, onde os Anexos complementam, detalham e especificam as obrigações e direitos gerais das PARTES, prevalecendo a norma específica sobre a geral em caso de aparente conflito.</P>

      <P>1.4. Caso o CONTRATANTE venha a solicitar a execução de projetos, desenvolvimentos customizados ou integrações tecnológicas que transcendam o escopo padrão dos serviços ofertados e que, por sua natureza, exijam a alocação de recursos e a realização de investimentos significativos por parte da PIN BANK, tais demandas somente serão conhecidas, analisadas e, se for o caso, executadas, mediante a formalização de comum acordo entre as PARTES. Essa formalização se dará por meio de aditivo contratual específico ou proposta comercial detalhada, que deverá descrever exaustivamente o escopo do projeto, os cronogramas de execução, os critérios de aceitação e os custos adicionais ou modelos de remuneração aplicáveis, garantindo assim a viabilidade técnica e econômica da empreitada e o perfeito alinhamento de expectativas entre os contraentes.</P>

      <ClauseTitle>CLÁUSULA SEGUNDA - DA VIGÊNCIA, RENOVAÇÃO E CONDIÇÕES DE PERMANÊNCIA</ClauseTitle>

      <P>2.1. O presente Contrato Master entrará em vigor na data de sua assinatura, permanecendo válido e eficaz pelo prazo de 24 (vinte e quatro) meses. Ao término deste período inicial, o contrato será renovado automaticamente por até 3 (três) períodos consecutivos e idênticos, de 24 (vinte e quatro) meses cada, alcançando uma vigência máxima potencial de 48 (quarenta e oito) meses, salvo se qualquer das PARTES manifestar sua intenção em contrário, nos termos da cláusula 2.3. A renovação automática visa garantir a continuidade dos serviços e a estabilidade da relação comercial, pressupondo a manutenção das condições de equilíbrio contratual e o adimplemento das obrigações por ambas as PARTES.</P>

      <P>2.2. Exaurido o período máximo de vigência do Contrato Master, incluindo o prazo inicial e todas as renovações automáticas possíveis, a continuidade da prestação de serviços dependerá de renegociação expressa das condições comerciais e contratuais. Tal renegociação deverá ser formalizada por meio da celebração de um novo instrumento contratual ou de um aditivo específico, que reflita o consenso das PARTES sobre os novos termos da relação jurídica, não se aplicando, em nenhuma hipótese, a prorrogação tácita ou por prazo indeterminado após o esgotamento do prazo máximo estipulado.</P>

      <P>2.3. Qualquer uma das PARTES poderá exercer o direito de denunciar a renovação automática do Contrato Master, obstando a prorrogação do período de vigência. Para tanto, a PARTE interessada deverá notificar a outra, de forma inequívoca e por escrito, com uma antecedência mínima de 60 (sessenta) dias em relação à data prevista para o término do período de vigência em curso. O exercício tempestivo deste direito de não renovação não acarretará a imposição de quaisquer multas, penalidades ou ônus para a PARTE denunciante, constituindo-se em prerrogativa contratual para a reavaliação da continuidade da parceria.</P>

      <P>2.4. A PIN BANK reserva-se o direito de condicionar as renovações automáticas do Contrato Master e/ou dos Módulos de Serviço a um processo de reavaliação cadastral e de risco do CONTRATANTE. Tal processo poderá incluir, mas não se limitará a, a solicitação de atualização da documentação societária, contábil e de representação legal do CONTRATANTE, uma nova análise de seu perfil de risco de crédito e operacional, com especial atenção ao histórico de fraudes e chargebacks, e a verificação de sua capacidade de adequação a novas exigências regulatórias impostas pelo Banco Central do Brasil ou por outras autoridades competentes que venham a impactar a prestação dos serviços.</P>

      <P>2.5. Para fins de clareza e controle, a vigência específica de cada Módulo de Serviço contratado será computada individualmente, iniciando-se a partir da data de sua efetiva ativação e disponibilização para uso pelo CONTRATANTE. Esta data de ativação será registrada nos sistemas de controle da PIN BANK, servindo como marco inicial para a contagem de quaisquer prazos ou obrigações específicas relacionadas ao respectivo Módulo, e será comunicada ao CONTRATANTE através dos canais de atendimento ou da própria plataforma.</P>

      <ClauseTitle>CLÁUSULA TERCEIRA - DA REMUNERAÇÃO, COMPENSAÇÃO E MECANISMOS DE AJUSTE</ClauseTitle>

      <P>3.1. A título de contraprestação pelos serviços objeto deste Contrato, o CONTRATANTE pagará à PIN BANK os valores estabelecidos nos Anexos II-A (Remuneração Módulo Subadquirência) e II-B (Tarifas Módulo Conta e Cobrança Pix), conforme os módulos efetivamente contratados. O CONTRATANTE, neste ato, autoriza expressa e irrevogavelmente a PIN BANK a realizar a dedução automática da remuneração devida diretamente dos valores transacionados pelo CONTRATANTE e processados através da Plataforma PIN BANK e/ou dos saldos mantidos em sua Conta de Pagamento. Esta sistemática de dedução na fonte constitui condição essencial do negócio, garantindo a agilidade e a segurança no acerto de contas entre as PARTES.</P>

      <P>3.2. O CONTRATANTE reconhece e outorga à PIN BANK o direito amplo e irrestrito de compensar quaisquer valores que lhe sejam devidos com os créditos a serem repassados ao CONTRATANTE ou com os saldos disponíveis em sua Conta de Pagamento. Esta autorização de compensação abrange, de forma exemplificativa, taxas de serviço, multas contratuais, indenizações por perdas e danos, valores decorrentes de Chargeback e seus custos associados, estornos, tarifas de manutenção de conta, débitos originados de fraudes comprovadas ou falhas operacionais imputáveis ao CONTRATANTE, e quaisquer outros débitos previstos neste instrumento ou seus Anexos, constituindo-se em um mecanismo de garantia e liquidação de obrigações.</P>

      <P>3.3. Na hipótese de o volume de Transações processadas ou o saldo disponível na Conta de Pagamento do CONTRATANTE se mostrarem insuficientes para a cobertura integral dos débitos devidos à PIN BANK, o CONTRATANTE obriga-se a efetuar o pagamento da diferença apurada no prazo máximo de 5 (cinco) dias úteis, contados a partir do recebimento de notificação formal enviada pela PIN BANK. A inobservância deste prazo constituirá o CONTRATANTE em mora, sujeitando-o à incidência de multa moratória de 2% (dois por cento) sobre o valor do débito, acrescido de juros de 1% (um por cento) ao mês, calculados pro rata die desde a data do vencimento até a data do efetivo pagamento, sem prejuízo da adoção, pela PIN BANK, de outras medidas contratuais e legais cabíveis, incluindo a suspensão dos serviços e a cobrança judicial ou extrajudicial do débito.</P>

      <P>3.4. Em situações de alteração significativa e comprovada do cenário macroeconômico, que impactem de forma substancial o equilíbrio econômico-financeiro deste Contrato, a PIN BANK poderá invocar a prerrogativa de solicitar um reajuste emergencial das taxas e tarifas. Consideram-se como gatilhos para tal solicitação, de forma exemplificativa, a inflação acumulada, medida por índice oficial, superior a 15% (quinze por cento) em um período de 12 (doze) meses, a variação da taxa SELIC em mais de 3 (três) pontos percentuais em um semestre, ou a declaração de crise sistêmica por autoridade econômica governamental. A PIN BANK deverá apresentar justificativa técnica e econômica detalhada, abrindo-se um prazo de 30 (trinta) dias para negociação amigável entre as PARTES. Na ausência de acordo neste prazo, a PIN BANK poderá rescindir o Contrato Master sem a imposição de ônus, mediante aviso prévio de 30 (trinta) dias.</P>

      <P>3.5. Com o fito de ampliar as garantias de adimplemento das obrigações financeiras do CONTRATANTE, este autoriza expressamente a PIN BANK a realizar a compensação de seus débitos não apenas com seus próprios créditos, mas também com valores a receber de outras entidades. Esta autorização estende-se, primeiramente, a outras empresas que comprovadamente pertençam ao mesmo grupo econômico do CONTRATANTE, mediante análise de documentos societários. Em segundo lugar, abrange dívidas de sócios que detenham participação societária superior a 25% (vinte e cinco por cento) no capital social do CONTRATANTE. Por fim, inclui obrigações de empresas coligadas ou controladas pelo CONTRATANTE, conforme as definições estabelecidas na legislação societária vigente, configurando uma garantia fidejussória ampla.</P>

      <P>3.6. Em cenários de elevação significativa e comprovada do perfil de risco do CONTRATANTE, identificados por meio dos sistemas de monitoramento da PIN BANK, esta poderá, de forma discricionária e justificada, alterar temporariamente os prazos de repasse e liquidação financeira das Transações, ou realizar investigações aprofundadas antes de sua efetivação. Tais cenários incluem, sem limitação, aumentos substanciais e repentinos no volume transacionado, alterações atípicas nos valores médios das Transações, ou um incremento relevante no índice de Chargebacks ou de transações suspeitas. As medidas adotadas serão proporcionais ao risco identificado e comunicadas ao CONTRATANTE, visando à proteção do ecossistema de pagamentos e à mitigação de potenciais prejuízos.</P>

      <P>3.7. O CONTRATANTE autoriza expressa e irrevogavelmente a PIN BANK a instituir, a qualquer tempo, gravames e ônus sobre os recebíveis de arranjos de pagamento constituídos ou a serem constituídos em sistemas de registro, nos termos da regulamentação do Banco Central do Brasil, como forma de garantia das obrigações assumidas no presente Contrato. Essa trava sobre os recebíveis poderá ser utilizada para assegurar o cumprimento de quaisquer débitos do CONTRATANTE perante a PIN BANK, incluindo, mas não se limitando a, tarifas, multas, Chargebacks e indenizações, constituindo um direito de garantia em favor da PIN BANK, que poderá ser exercido mediante simples comunicação ao sistema de registro competente.</P>

      <P>3.8. Na hipótese de a PIN BANK, por mera liberalidade e mediante acordo específico com o CONTRATANTE, oferecer o serviço de antecipação de recebíveis, o custo de tal operação será baseado na variação da taxa dos Certificados de Depósito Interbancário (CDI). Desta forma, a PIN BANK reserva-se o direito de alterar o custo efetivo total ou a taxa de desconto aplicada à antecipação, a seu exclusivo critério e de acordo com as flutuações do CDI e outras condições de mercado, sem a necessidade de aviso prévio ou da celebração de aditivo contratual para cada alteração, refletindo a natureza dinâmica do custo de captação de recursos.</P>

      <ClauseTitle>CLÁUSULA QUARTA - DOS DIREITOS E DAS OBRIGAÇÕES FUNDAMENTAIS DAS PARTES</ClauseTitle>

      <P>4.1. Constituem direitos e obrigações essenciais da PIN BANK, sem prejuízo de outras disposições contidas neste instrumento e seus anexos:</P>
      <P style={{ paddingLeft: '20px' }}>a) A disponibilização da Plataforma PIN BANK e dos Módulos de Serviço contratados em estrita conformidade com as condições aqui pactuadas, assegurando a funcionalidade e a segurança intrínseca dos sistemas;</P>
      <P style={{ paddingLeft: '20px' }}>b) O emprego dos melhores esforços e das mais avançadas tecnologias disponíveis para garantir a segurança, a estabilidade e a disponibilidade da plataforma, em observância aos Acordos de Nível de Serviço (SLAs) definidos no Anexo IV, o que inclui a implementação de medidas robustas de cibersegurança e a manutenção de uma infraestrutura resiliente;</P>
      <P style={{ paddingLeft: '20px' }}>c) O cumprimento rigoroso de toda a legislação aplicável às suas atividades como instituição de pagamento, notadamente as normas emanadas do Banco Central do Brasil, a Lei Geral de Proteção de Dados Pessoais (LGPD) e as regulamentações de Prevenção à Lavagem de Dinheiro e Financiamento do Terrorismo (PLD/FT);</P>
      <P style={{ paddingLeft: '20px' }}>d) A prestação de suporte técnico qualificado ao CONTRATANTE, a análise e aprovação do credenciamento e das transações com base em suas políticas de risco, o fornecimento de relatórios detalhados, a adoção de procedimentos rigorosos de verificação de identidade (KYC/KYB) e o exercício do direito-dever de não autorizar movimentações financeiras suspeitas de irregularidades ou crimes financeiros.</P>

      <P>4.2. Constituem direitos e obrigações fundamentais do CONTRATANTE, como contrapartida e condição para a regular prestação dos serviços:</P>
      <P style={{ paddingLeft: '20px' }}>a) O dever de fornecer à PIN BANK todas as informações e documentos necessários para os processos de credenciamento, ativação e manutenção contínua dos serviços, garantindo em todos os momentos a veracidade, a completude e a atualização de tais dados, assumindo integral responsabilidade por quaisquer prejuízos diretos ou indiretos decorrentes do fornecimento de informações falsas, imprecisas ou desatualizadas;</P>
      <P style={{ paddingLeft: '20px' }}>b) A utilização dos serviços de forma estritamente lícita, ética e em plena conformidade com este Contrato, seus Anexos, a legislação vigente e as melhores práticas de mercado, sendo o único e exclusivo responsável pela relação comercial com seus Consumidores Finais e Estabelecimentos, o que abrange a entrega de produtos, a prestação de serviços, o suporte, as políticas de devolução e a observância do Código de Defesa do Consumidor;</P>
      <P style={{ paddingLeft: '20px' }}>c) A manutenção de seus sistemas, ambientes tecnológicos e equipamentos em condições adequadas e seguras para a integração e o uso da Plataforma PIN BANK, implementando as melhores práticas de segurança da informação para proteger suas próprias redes e sistemas contra acessos não autorizados;</P>
      <P style={{ paddingLeft: '20px' }}>d) A responsabilidade exclusiva pela guarda e confidencialidade de suas credenciais de acesso (logins, senhas, chaves de API), devendo comunicar imediatamente à PIN BANK qualquer suspeita de perda, roubo, extravio ou utilização não autorizada de suas credenciais, sob pena de ser responsabilizado pelas operações indevidas realizadas por terceiros antes da efetiva comunicação;</P>
      <P style={{ paddingLeft: '20px' }}>e) A comunicação imediata à PIN BANK sobre qualquer suspeita de fraude, vulnerabilidade de segurança ou incidente que possa comprometer a segurança da Plataforma ou dos dados processados, bem como o dever de manter seu cadastro rigorosamente atualizado;</P>
      <P style={{ paddingLeft: '20px' }}>f) O reconhecimento da validade jurídica e da força probante de todas as interações, instruções e confirmações realizadas por meio dos canais eletrônicos disponibilizados pela PIN BANK, incluindo a plataforma web e as APIs, que serão consideradas manifestações de vontade válidas e eficazes;</P>
      <P style={{ paddingLeft: '20px' }}>g) A manutenção de saldo suficiente em sua Conta de Pagamento para a liquidação de débitos, tarifas e outras obrigações financeiras decorrentes da utilização dos serviços;</P>
      <P style={{ paddingLeft: '20px' }}>h) A responsabilidade integral pelos atos praticados por seu Usuário Master e por quaisquer outros usuários por si credenciados, que serão considerados, para todos os fins, como atos do próprio CONTRATANTE;</P>
      <P style={{ paddingLeft: '20px' }}>i) O compromisso de manter o aplicativo e as integrações via API sempre atualizados para as últimas versões disponibilizadas pela PIN BANK, a fim de garantir a segurança e o correto funcionamento dos serviços;</P>
      <P style={{ paddingLeft: '20px' }}>j) A responsabilidade solidária por quaisquer prejuízos, incluindo, mas não se limitando a, Chargebacks, fraudes, multas e indenizações, que seus clientes diretos (doravante denominados "Estabelecimentos") causem à PIN BANK, caso os fundos de tais Estabelecimentos ou as garantias prestadas sejam insuficientes para cobrir os respectivos débitos.</P>
    </>
  );
}