import React from 'react';
import { ClauseTitle, SubClauseTitle, P } from './ContratoStyles';

export default function ContratoClausulas10a14() {
  return (
    <>
      <ClauseTitle>CLÁUSULA DÉCIMA - DA EXTINÇÃO CONTRATUAL E SUAS CONSEQUÊNCIAS</ClauseTitle>

      <SubClauseTitle>SEÇÃO I - DA RESCISÃO IMOTIVADA</SubClauseTitle>
      <P>10.1.1. O presente Contrato Master poderá ser rescindido unilateralmente, de forma imotivada e a qualquer tempo, por qualquer uma das PARTES, sem que isso gere direito a qualquer tipo de multa, indenização ou penalidade compensatória. A rescisão imotivada representa uma prerrogativa de reavaliação da conveniência e oportunidade da continuidade da parceria comercial.</P>
      <P>10.1.2. A PARTE que desejar rescindir imotivadamente o Contrato deverá comunicar sua decisão à outra PARTE, por escrito e de forma inequívoca, com uma antecedência mínima de 60 (sessenta) dias em relação à data pretendida para o término efetivo dos serviços. Durante o período de aviso prévio, todas as cláusulas e obrigações contratuais permanecerão em pleno vigor, devendo as PARTES continuar a cumprir com suas respectivas responsabilidades, incluindo o processamento de transações e a liquidação financeira.</P>
      <P>10.1.3. O exercício do direito de rescisão imotivada, desde que respeitado o prazo de aviso prévio estipulado, não exime as PARTES do cumprimento de todas as obrigações pendentes e residuais, incluindo o acerto final de contas, a liquidação de repasses, o pagamento de tarifas devidas e a observância das cláusulas de sobrevivência, como as de confidencialidade e de retenção de valores para cobertura de passivos.</P>

      <SubClauseTitle>SEÇÃO II - DA RESCISÃO POR JUSTA CAUSA E DAS PENALIDADES APLICÁVEIS</SubClauseTitle>
      <P>10.2.1. O presente Contrato Master poderá ser rescindido de pleno direito e com efeito imediato por qualquer das PARTES, por justa causa, na ocorrência de qualquer uma das seguintes hipóteses, que configuram inadimplemento contratual grave: o descumprimento de qualquer obrigação essencial prevista neste Contrato Master ou em seus Anexos, desde que a infração não seja sanada no prazo de 15 (quinze) dias corridos a contar do recebimento de notificação escrita; a decretação de falência, o deferimento de pedido de recuperação judicial ou extrajudicial, a dissolução, liquidação ou a constatação de estado de insolvência de qualquer das PARTES; a prática comprovada e dolosa de fraude ou atividades ilícitas relacionadas ao uso da Plataforma PAGSMILE; a violação intencional das cláusulas de Propriedade Intelectual, Confidencialidade ou Proteção de Dados; a inadimplência financeira do CONTRATANTE por período superior a 30 (trinta) dias; a identificação de um padrão reiterado e injustificado de fraudes e chargebacks que exceda os limites previstos neste contrato; o descumprimento grave de normas de compliance; a recusa injustificada em cooperar com investigações ou auditorias; a utilização deliberada da plataforma para facilitação de atividades proibidas pelo Anexo III; o recebimento, pela PAGSMILE, de uma ordem ou solicitação formal de descredenciamento do CONTRATANTE por parte de um Adquirente ou Instituidor de Arranjo de Pagamento; a identificação, por meio de procedimentos de KYC contínuo, de que o CONTRATANTE passou a apresentar um perfil de risco inaceitável; ou a irregularidade do CNPJ do CONTRATANTE.</P>
      <P>10.2.2. A rescisão por justa causa, quando motivada por uma das hipóteses previstas no item 10.2.1, sujeitará a PARTE infratora ao pagamento de perdas e danos, a serem apurados em procedimento próprio, sem prejuízo da aplicação de multas específicas, caso previstas. Se a rescisão por justa causa for motivada por conduta fraudulenta, dolosa ou de má-fé do CONTRATANTE, este ficará sujeito a uma multa não compensatória correspondente a 20% (vinte por cento) do volume médio mensal de transações (TPV) dos últimos 6 (seis) meses, limitada ao teto de R$ 100.000,00 (cem mil reais), a ser paga em favor da PAGSMILE, sem prejuízo da apuração de perdas e danos suplementares.</P>

      <SubClauseTitle>SEÇÃO III - DAS CONSEQUÊNCIAS DA EXTINÇÃO CONTRATUAL</SubClauseTitle>
      <P>10.3.1. A rescisão do Contrato Master, por qualquer motivo, resultará no término automático e imediato de todos os Módulos de Serviço que estiverem ativos, observando-se, contudo, as disposições específicas de encerramento e acerto de contas previstas para cada um. O encerramento da Conta de Pagamento está condicionado ao resgate total dos fundos, devendo o CONTRATANTE fornecer seus dados bancários para a devolução dos recursos, deduzidas as tarifas e débitos pendentes, em processo que observará os prazos de retenção de segurança.</P>
      <P>10.3.2. Em caso de rescisão do Contrato, por qualquer motivo, a PAGSMILE reterá os saldos existentes e quaisquer valores a serem repassados ao CONTRATANTE pelo prazo de 180 (cento e oitenta) dias, contados da data da última transação processada. Este período de retenção destina-se a constituir um fundo de reserva para a cobertura de eventuais passivos que possam surgir após o término da relação contratual, como Chargebacks, disputas, multas, reclamações administrativas ou processos judiciais.</P>
      <P>10.3.3. Caso a rescisão contratual decorra de conduta irregular do CONTRATANTE que, por sua natureza, possa gerar responsabilidades de longo prazo ("long-tail liabilities"), tais como processos judiciais complexos, investigações por autoridades, multas de valores significativos ou um volume de Chargebacks com potencial de manifestação tardia, a PAGSMILE poderá, a seu exclusivo critério, e mediante notificação fundamentada, estender a manutenção da retenção de valores por prazo indeterminado. A retenção perdurará até que todas as responsabilidades e riscos pendentes sejam plenamente quantificados e quitados, ou até que se constate, de forma inequívoca, que não subsistem mais riscos de prejuízos financeiros ou legais para a PAGSMILE decorrentes da operação do CONTRATANTE. A liberação dos valores ocorrerá de forma progressiva, à medida que os riscos se dissiparem.</P>
      <P>10.3.4. Na eventualidade de modificações na legislação, em regulamentos setoriais, ou na emissão de ordens por parte do governo, do Banco Central do Brasil ou de outras autoridades regulatórias competentes, que afetem substancialmente a execução do escopo deste Contrato Master ou que interfiram de maneira impeditiva no cumprimento das obrigações assumidas pela PAGSMILE, fica esta autorizada a, a seu critério, rever os termos do contrato ou rescindi-lo, bem como os Módulos de Serviço afetados, a qualquer momento, sem que tal ato gere para si a incidência de qualquer ônus, multa ou penalidade.</P>

      <ClauseTitle>CLÁUSULA DÉCIMA PRIMEIRA - DA PROTEÇÃO DE DADOS PESSOAIS E DA LGPD</ClauseTitle>
      <P>11.1. As PARTES declaram, de forma solene e para todos os efeitos legais, que possuem pleno conhecimento e se comprometem a cumprir integralmente as disposições da Lei Geral de Proteção de Dados Pessoais (LGPD - Lei nº 13.709/2018), bem como de toda e qualquer legislação correlata aplicável à proteção de dados pessoais e privacidade. As obrigações e responsabilidades específicas de cada PARTE no que tange ao tratamento de dados pessoais no âmbito deste contrato estão detalhadas no Anexo VI - Tratamento de Dados Pessoais, que constitui parte indissociável deste instrumento.</P>
      <P>11.2. Para a exata delimitação das responsabilidades no âmbito da LGPD, fica estabelecido que, para os fins deste Contrato Master, o CONTRATANTE atuará na qualidade de Controlador dos dados pessoais de seus Consumidores Finais, sendo sua a responsabilidade primária pela determinação das finalidades e das bases legais que legitimam o tratamento de tais dados. A PAGSMILE, por sua vez, atuará estritamente na qualidade de Operadora em relação a esses dados, tratando-os em nome, por conta e em estrita conformidade com as instruções lícitas e documentadas do CONTRATANTE, para a finalidade exclusiva de prestar os serviços contratados.</P>
      <P>11.3. A PAGSMILE, como Operadora, compromete-se a adotar medidas de segurança, técnicas e administrativas aptas a proteger os dados pessoais de acessos não autorizados e de situações acidentais ou ilícitas de destruição, perda, alteração, comunicação ou qualquer forma de tratamento inadequado ou ilícito. Tais medidas deverão ser, no mínimo, compatíveis com os padrões de mercado para empresas de seu porte e setor de atuação, incluindo, mas não se limitando a, controles de acesso, criptografia, monitoramento de rede e planos de resposta a incidentes.</P>
      <P>11.4. Na hipótese de ocorrência de um incidente de segurança que envolva os dados pessoais tratados sob este contrato e que possa acarretar risco ou dano relevante aos titulares dos dados, a PAGSMILE, na qualidade de Operadora, compromete-se a notificar o CONTRATANTE, na qualidade de Controlador, em um prazo máximo de 48 (quarenta e oito) horas, contadas a partir do momento em que tomar conhecimento efetivo do incidente. A notificação deverá conter as informações relevantes disponíveis sobre a natureza, os titulares afetados, as consequências do incidente e as medidas que estão sendo tomadas para remediar a situação, a fim de permitir que o CONTRATANTE cumpra suas próprias obrigações de notificação à Autoridade Nacional de Proteção de Dados (ANPD) e aos titulares. O CONTRATANTE, por sua vez, cooperará com a PAGSMILE na investigação e mitigação do incidente.</P>

      <ClauseTitle>CLÁUSULA DÉCIMA SEGUNDA - DA TAXA DE PROCESSAMENTO DE PRÉ-CHARGEBACK E CHARGEBACK</ClauseTitle>
      <P>12.1. Será imputada ao CONTRATANTE uma taxa de serviço no valor fixo de R$ 65,00 (sessenta e cinco reais) por cada evento de Pré-Chargeback e/ou Chargeback que for gerado em conexão com as transações processadas em seu nome. Esta taxa visa a remunerar os custos operacionais e administrativos da PAGSMILE no tratamento de tais contestações. Contudo, na hipótese de a disputa de Chargeback ser revertida em favor do CONTRATANTE, com o reconhecimento da legitimidade da transação pela bandeira ou pelo emissor, a taxa de R$ 65,00 referente a este evento específico será integralmente estornada ao CONTRATANTE.</P>
      <P>12.2. As taxas devidas em razão de Pré-Chargebacks e/ou Chargebacks serão deduzidas de forma automática, por meio de split de pagamento, da próxima Transação processada em favor do CONTRATANTE após a geração do alerta de contestação. O desconto será efetuado diretamente sobre o valor a ser repassado ao CONTRATANTE, sendo esta uma condição expressamente autorizada para a agilização dos acertos financeiros.</P>
      <P>12.3. Caso o valor líquido da próxima Transação a ser repassada seja insuficiente para cobrir integralmente o montante das taxas de Pré-Chargeback e/ou Chargeback devidas, o saldo devedor remanescente será automaticamente transportado e deduzido dos valores a serem repassados nas Transações subsequentes, de forma sucessiva, até que a quitação integral do débito seja alcançada.</P>
      <P>12.4. A PAGSMILE compromete-se a notificar o CONTRATANTE a respeito da cobrança das referidas taxas no exato momento da dedução, fornecendo um extrato claro que informe os valores descontados, a qual transação ou evento de contestação eles se referem e o eventual saldo devedor remanescente a ser compensado em operações futuras, garantindo a total transparência do processo.</P>
      <P>12.5. Para a perfeita compreensão e aplicação das disposições deste Contrato, fica definido que "Pré-Chargeback" se refere à notificação prévia de uma potencial contestação, enviada pela bandeira do cartão ou pelo adquirente, antes da efetivação do débito do chargeback, permitindo uma tentativa de resolução amigável ou preparação de defesa. Por sua vez, "Chargeback" designa a contestação efetiva e formal de uma Transação, iniciada pelo Consumidor Final junto ao banco emissor de seu cartão, e que resulta, em um primeiro momento, no estorno do valor da transação da conta da PAGSMILE e, consequentemente, do CONTRATANTE.</P>

      <ClauseTitle>CLÁUSULA DÉCIMA TERCEIRA - DA RESERVA DE SEGURANÇA PARA TRANSAÇÕES COM CARTÃO DE CRÉDITO</ClauseTitle>
      <P>13.1. Como medida de mitigação de risco e garantia de obrigações futuras, a PAGSMILE reterá um percentual de 5% (cinco por cento) sobre o valor bruto de todas as Transações realizadas por meio de cartão de crédito, a título de constituição de uma "Reserva de Segurança". Este fundo será destinado exclusivamente a cobrir eventuais débitos do CONTRATANTE para com a PAGSMILE, incluindo, mas não se limitando a, valores de Chargebacks, estornos, multas aplicadas por bandeiras ou reguladores, e outras obrigações financeiras previstas neste Contrato.</P>
      <P>13.2. A constituição da Reserva de Segurança ocorrerá de forma automática e concomitante ao processamento de cada Transação de cartão de crédito. O percentual de 5% (cinco por cento) será deduzido do valor a ser liquidado e repassado ao CONTRATANTE, sendo o montante correspondente apartado e mantido em conta específica de controle da PAGSMILE, vinculada ao CONTRATANTE.</P>
      <P>13.3. Os valores retidos na Reserva de Segurança serão progressivamente liberados e creditados na Conta de Pagamento do CONTRATANTE, observadas as seguintes condições temporais e de risco: uma liberação parcial ocorrerá após o transcurso de 60 (sessenta) dias corridos, contados da data de cada Transação, condicionada à inexistência de Chargebacks ou outras contestações pendentes de resolução relacionadas à respectiva Transação; a liberação total do saldo remanescente de cada Transação ocorrerá após o decurso do prazo de 120 (cento e vinte) dias corridos, contados da data da operação, independentemente da ocorrência de Chargebacks, exceto se, neste momento, existirem outros débitos vencidos e não pagos do CONTRATANTE para com a PAGSMILE, os quais deverão ser devidamente comprovados para justificar a manutenção da retenção.</P>
      <P>13.4. O CONTRATANTE autoriza expressamente a PAGSMILE a utilizar, a qualquer momento e sem necessidade de notificação prévia, os valores mantidos na Reserva de Segurança para compensar e liquidar automaticamente quaisquer débitos pendentes. Esta compensação poderá ser utilizada para cobrir valores de Chargebacks e as respectivas taxas de serviço, no valor de R$ 65,00 (sessenta e cinco reais) por evento; estornos e cancelamentos solicitados; multas aplicadas por Bandeiras ou órgãos reguladores em decorrência das operações do CONTRATANTE; e quaisquer outros débitos vencidos do CONTRATANTE, previstos neste Contrato e seus anexos.</P>
      <P>13.5. Na hipótese de o saldo da Reserva de Segurança se mostrar insuficiente para cobrir integralmente os débitos do CONTRATANTE, este permanecerá obrigado pelo pagamento da diferença. O CONTRATANTE deverá quitar o valor remanescente nos termos e prazos estipulados na Cláusula Terceira deste Contrato Master, sob pena de incidência das penalidades por mora ali previstas, incluindo multa e juros.</P>
      <P>13.6. Com o intuito de garantir a transparência na gestão da Reserva de Segurança, a PAGSMILE disponibilizará ao CONTRATANTE, através de sua plataforma online ou por outros meios eletrônicos, relatórios mensais detalhados. Estes relatórios discriminarão os valores retidos a cada período, os montantes utilizados para compensação de débitos, com a respectiva justificativa, e os valores liberados e creditados na conta do CONTRATANTE.</P>
      <P>13.7. Em caso de rescisão do Contrato Master ou do Módulo Subadquirência (Anexo I-A), por qualquer motivo, os saldos remanescentes na Reserva de Segurança serão retidos e administrados conforme as disposições da Seção III da Cláusula Décima, sendo liberados apenas após o decurso dos prazos de segurança e a liquidação de todos os passivos potenciais, notadamente o prazo de 180 (cento e oitenta) dias para manifestação de Chargebacks tardios, podendo ser estendido conforme a necessidade de cobertura de responsabilidades de longo prazo.</P>

      <ClauseTitle>CLÁUSULA DÉCIMA QUARTA - DA RETENÇÃO DE SEGURANÇA PARA PIX E OUTROS MEIOS DE PAGAMENTO</ClauseTitle>
      <P>14.1. A PAGSMILE poderá, a seu exclusivo critério e com base em uma análise de risco contínua do perfil transacional e de negócio do CONTRATANTE, instituir a retenção de um percentual de 1% (um por cento) sobre o valor de todas as Transações realizadas por meios de pagamento distintos do cartão de crédito, tais como PIX e boleto bancário. Esta retenção formará uma Reserva de Segurança específica, destinada a cobrir eventuais perdas decorrentes de fraudes, falhas operacionais, devoluções iniciadas através do Mecanismo Especial de Devolução (MED) do PIX e demais obrigações do CONTRATANTE relacionadas a estas modalidades de pagamento.</P>
      <P>14.2. Caso instituída, a Reserva de Segurança para PIX e outros meios será constituída de forma automática a cada Transação, mediante a dedução do percentual estabelecido do valor a ser repassado ao CONTRATANTE. Os valores retidos serão mantidos em conta de controle, de forma segregada da reserva para cartões de crédito. A decisão de aplicar esta retenção será comunicada previamente ao CONTRATANTE.</P>
      <P>14.3. Os valores retidos nesta Reserva de Segurança específica serão liberados integralmente ao CONTRATANTE após o decurso do prazo de 90 (noventa) dias corridos, contados da data de cada Transação individual. A liberação poderá ser postergada, no entanto, caso exista, em relação à transação específica, uma suspeita fundamentada de fraude, amparada por evidências concretas, uma solicitação de devolução via MED ainda pendente de análise e decisão, ou a existência de débitos específicos do CONTRATANTE com a PAGSMILE que sejam diretamente relacionados a estas modalidades de transação.</P>
      <P>14.4. Fica a PAGSMILE expressamente autorizada pelo CONTRATANTE a utilizar os valores desta Reserva de Segurança para compensar, de forma automática e independentemente de notificação prévia, quaisquer débitos do CONTRATANTE que sejam oriundos de fraudes comprovadas, falhas operacionais ou devoluções efetivadas via MED em transações PIX, boleto ou outros meios de pagamento que não sejam cartão de crédito. A compensação será realizada pelo valor exato do prejuízo sofrido pela PAGSMILE.</P>
      <P>14.5. Se o montante disponível na Reserva de Segurança para PIX e outros meios for insuficiente para a cobertura integral dos débitos apurados, o CONTRATANTE se obriga a efetuar o pagamento do valor complementar, conforme o procedimento e os prazos estabelecidos na Cláusula Terceira deste Contrato Master. A não complementação do pagamento no prazo estipulado sujeitará o CONTRATANTE à incidência das penalidades por atraso ali detalhadas.</P>
    </>
  );
}