import React from 'react';
import { ClauseTitle, P } from './ContratoStyles';

export default function ContratoClausulas5a9() {
  return (
    <>
      <ClauseTitle>CLÁUSULA QUINTA - DA CONFORMIDADE REGULATÓRIA E COMPLIANCE</ClauseTitle>
      <P>5.1. O CONTRATANTE declara, para todos os fins de direito e sob as penas da lei, que suas atividades empresariais são conduzidas em estrita conformidade com toda a legislação aplicável ao seu setor de atuação. Declara, ainda, que não pratica, não praticou e não facilitará, por ação ou omissão, a ocorrência de atividades fraudulentas de qualquer natureza, comprometendo-se a implementar e manter controles internos adequados e eficazes para a prevenção de fraudes. O CONTRATANTE atesta que todas as informações fornecidas no processo de abertura de conta são verídicas e completas, comprometendo-se a notificar a PIN BANK sobre quaisquer alterações, assumindo total responsabilidade pelas consequências do descumprimento desta obrigação.</P>
      <P>5.2. O CONTRATANTE assume a obrigação de implementar e manter, às suas expensas, políticas e procedimentos robustos de Prevenção à Lavagem de Dinheiro e ao Financiamento do Terrorismo (PLD/FT), incluindo um rigoroso processo de identificação e qualificação de seus próprios clientes e Estabelecimentos (Know Your Customer - KYC), em total conformidade com as normas do Banco Central do Brasil, em especial a Circular BCB nº 3.978/2020 e a Resolução BCB nº 142/2021. Tais procedimentos deverão ser compatíveis com a natureza de seu negócio e o perfil de risco de suas operações, e deverão ser continuamente atualizados.</P>
      <P>5.3. O CONTRATANTE garante à PIN BANK, por si e por suas afiliadas ou auditores independentes, o livre e irrestrito acesso, mediante solicitação, a todos os dados, informações e documentos coletados em seus processos de KYC/PLD. O objetivo deste acesso é permitir que a PIN BANK realize a validação, a auditoria e o monitoramento contínuo da eficácia dos controles do CONTRATANTE, bem como cumprir com suas próprias obrigações regulatórias perante o Banco Central e outras autoridades.</P>
      <P>5.4. A PIN BANK poderá, a qualquer momento durante a vigência contratual, solicitar documentos e informações adicionais para fins de aprofundamento dos procedimentos de KYC e KYB (Know Your Business), visando a reavaliação do perfil de risco, o atendimento a novas exigências regulatórias ou a realização de um processo de KYC contínuo. O CONTRATANTE deverá fornecer a documentação solicitada no prazo máximo de 7 (sete) dias úteis, contados do recebimento da solicitação. A falha no fornecimento tempestivo, a entrega de informações insuficientes ou a recusa em apresentar os dados solicitados será considerada infração contratual grave, sujeitando o CONTRATANTE, a critério da PIN BANK, à suspensão imediata dos serviços e/ou ao descredenciamento definitivo de sua plataforma, sem prejuízo de outras sanções cabíveis.</P>
      <P>5.5. Caso a PIN BANK, em suas análises de monitoramento contínuo, identifique indícios consistentes de irregularidades graves ou de um padrão de não conformidade nas operações do CONTRATANTE, poderá exigir, como medida de aprofundamento da verificação, a realização de uma certificação de compliance por uma empresa de auditoria independente de renome. Os custos e despesas decorrentes de tal auditoria correrão integralmente por conta do CONTRATANTE, que deverá cooperar para a sua realização. A recusa em contratar ou cooperar com a auditoria será considerada uma violação contratual grave.</P>
      <P>5.6. O descumprimento de quaisquer das obrigações de conformidade, compliance e atualização cadastral estabelecidas nesta Cláusula constitui infração contratual e poderá resultar, a critério exclusivo e discricionário da PIN BANK, na suspensão imediata e sem aviso prévio da prestação de todos os serviços. Se for verificado que as informações fornecidas são ou se tornaram desatualizadas, inexatas, falsas ou incompletas, e o CONTRATANTE não as regularizar após solicitação, a PIN BANK poderá, cumulativa ou alternativamente: não aprovar a contratação de novos produtos ou serviços; suspender toda e qualquer movimentação na Conta de Pagamento; encerrar a Conta e rescindir o contrato por justa causa; e/ou comunicar a irregularidade às autoridades competentes, em conformidade com seus deveres legais e regulatórios.</P>
      <P>5.7. As PARTES acordam em armazenar e manter, de forma segura e organizada, todos os registros tangíveis de informações de transações de pagamento e os dados cadastrais completos dos Estabelecimentos e Consumidores Finais pelo prazo mínimo de 10 (dez) anos. Este prazo é estipulado em conformidade com o artigo 67, inciso I, da Circular BCB nº 3.978/2020, e começará a contar a partir da conclusão dos respectivos fluxos destinados a conhecer os clientes e a monitorar as transações de pagamento, garantindo a rastreabilidade e a disponibilidade das informações para fins de auditoria e fiscalização pelas autoridades competentes.</P>

      <ClauseTitle>CLÁUSULA SEXTA - DO SISTEMA DE ALERTAS E MONITORAMENTO DE RISCO</ClauseTitle>
      <P>6.1. A PIN BANK implementará um sistema automatizado de monitoramento de transações, baseado em score de risco, que classificará as operações do CONTRATANTE em níveis de alerta. A operação será considerada normal quando o score de risco estiver na faixa de 0 a 30%, correspondendo ao Nível Verde. O Nível Amarelo, compreendendo um score de 31% a 60%, implicará um monitoramento intensificado das atividades. Caso o score atinja a faixa de 61% a 80%, classificado como Nível Laranja, todas as transações passarão por análise manual obrigatória antes da liquidação. O Nível Vermelho, de 81% a 95%, acarretará a suspensão temporária e automática das operações para análise aprofundada. Por fim, o Nível Crítico, correspondente a um score entre 96% e 100%, resultará no bloqueio imediato da conta e dos serviços para investigação de potencial fraude ou atividade ilícita.</P>
      <P>6.2. Cada nível de alerta disparará ações automáticas e proporcionais ao risco identificado. No Nível Amarelo, será gerado um relatório semanal de transações para acompanhamento pelo CONTRATANTE e pela equipe de risco da PIN BANK. Ao atingir o Nível Laranja, as transações serão submetidas à análise manual em até 4 (quatro) horas, e um relatório diário de atividades será enviado. A entrada no Nível Vermelho implicará a suspensão imediata das operações, com início da análise do caso em até 2 (duas) horas. O Nível Crítico resultará no bloqueio total da conta e no início de uma investigação imediata e prioritária sobre as atividades suspeitas.</P>
      <P>6.3. O CONTRATANTE será notificado em tempo real sobre qualquer mudança em seu nível de alerta, garantindo a transparência do processo de monitoramento. As notificações serão enviadas por meio de múltiplos canais de comunicação, que poderão incluir, de forma não exaustiva, e-mail para o endereço cadastrado, notificações via SMS para o telefone de contato e alertas direcionados à sua interface de programação de aplicações (API), permitindo uma reação rápida e a apresentação de esclarecimentos, se necessário.</P>

      <ClauseTitle>CLÁUSULA SÉTIMA - DO MONITORAMENTO COMPORTAMENTAL DE TRANSAÇÕES</ClauseTitle>
      <P>7.1. A PIN BANK implementará e manterá um sofisticado sistema de monitoramento comportamental contínuo, que analisará as transações do CONTRATANTE em tempo real, buscando por anomalias e desvios de padrão. Este sistema avaliará, entre outros fatores, a existência de padrões de transação que sejam incompatíveis com o perfil de negócio declarado pelo CONTRATANTE no momento de seu cadastro; a concentração anômala de transações em horários, valores ou frequências atípicas; a origem geográfica suspeita das transações, correlacionando-as com regiões de alto risco de fraude; a velocidade de processamento que se mostre incompatível com a natureza do negócio; e a correlação de dados das transações com bases de dados externas e internas de fraudes conhecidas e documentadas.</P>
      <P>7.2. O CONTRATANTE, ao aderir a este Contrato, autoriza expressa e inequivocamente a PIN BANK a suspender, de forma preventiva e automática, quaisquer transações que apresentem um score de risco superior a 80% (oitenta por cento) em sua análise comportamental. Uma vez suspensa a transação, a PIN BANK se compromete a notificar o CONTRATANTE em um prazo máximo de 2 (duas) horas, para que este possa prestar os devidos esclarecimentos, apresentar documentação comprobatória da legitimidade da operação e permitir a reavaliação da decisão de suspensão pela equipe de risco.</P>
      <P>7.3. As transações que, após a análise do sistema de monitoramento comportamental, apresentarem um score de risco situado na faixa entre 60% (sessenta por cento) e 80% (oitenta por cento) serão automaticamente direcionadas para um fluxo de análise manual adicional, a ser conduzido por analistas de risco especializados. Em decorrência deste procedimento de verificação suplementar, poderá haver um atraso no processo de liquidação e repasse dos valores correspondentes a tais transações, o qual não excederá, em nenhuma hipótese, o prazo de 48 (quarenta e oito) horas a contar do momento da transação.</P>

      <ClauseTitle>CLÁUSULA OITAVA - DA UTILIZAÇÃO DE INTELIGÊNCIA ARTIFICIAL NA PREVENÇÃO A FRAUDES</ClauseTitle>
      <P>8.1. A PIN BANK declara que poderá utilizar, em suas plataformas e sistemas de segurança, algoritmos avançados de inteligência artificial (IA) e aprendizado de máquina (machine learning). Tais tecnologias serão empregadas com o objetivo primordial de aprimorar a detecção automática de padrões fraudulentos complexos e emergentes, realizar uma análise comportamental dinâmica e preditiva das transações, possibilitar a prevenção proativa de fraudes antes de sua consumação, e otimizar as taxas de aprovação de transações legítimas, minimizando os falsos positivos e o impacto negativo na experiência dos Consumidores Finais.</P>
      <P>8.2. O CONTRATANTE, ciente da importância e da eficácia de tais tecnologias para a segurança do ecossistema de pagamentos, autoriza expressamente a PIN BANK a utilizar os dados transacionais agregados e anonimizados gerados em sua operação para fins de treinamento, calibração e aperfeiçoamento contínuo dos referidos algoritmos de IA. A PIN BANK garante que todo e qualquer uso de dados para essa finalidade será realizado em estrita conformidade com as disposições da Lei Geral de Proteção de Dados Pessoais (LGPD) e demais normativas de privacidade, respeitando os princípios da finalidade, necessidade e segurança.</P>
      <P>8.3. Reconhecendo que decisões automatizadas podem, em raras ocasiões, resultar em bloqueios indevidos de transações legítimas, a PIN BANK garante ao CONTRATANTE o direito de contestar qualquer decisão de bloqueio que tenha sido tomada exclusivamente com base em processamento automatizado. Uma vez recebida a contestação, a PIN BANK se compromete a assegurar a revisão humana da decisão por um analista de risco qualificado, em um prazo máximo de 4 (quatro) horas, garantindo a análise contextual e a possibilidade de reversão do bloqueio mediante a apresentação de evidências que comprovem a legitimidade da transação.</P>

      <ClauseTitle>CLÁUSULA NONA - DA CONFIDENCIALIDADE E DO SIGILO DAS INFORMAÇÕES</ClauseTitle>
      <P>9.1. As PARTES, por si, seus representantes legais, prepostos, empregados e consultores, assumem a obrigação irrevogável e irretratável de manter em absoluto e permanente sigilo todas e quaisquer Informações Confidenciais a que venham a ter acesso, de forma direta ou indireta, em virtude da celebração e execução do presente Contrato Master. Comprometeram-se, ainda, a utilizar as referidas informações exclusivamente para os fins estritamente necessários ao cumprimento de suas obrigações e ao exercício de seus direitos aqui previstos, abstendo-se de qualquer uso, divulgação ou exploração para finalidades diversas.</P>
      <P>9.2. Para os fins deste Contrato, o termo "Informações Confidenciais" deverá ser interpretado da forma mais ampla possível, abrangendo quaisquer dados, informações, especificações técnicas, segredos comerciais, know-how, modelos de negócio, estratégias de marketing, informações financeiras, operacionais, dados de clientes, algoritmos, software, documentação, e quaisquer outros materiais ou conhecimentos, em formato tangível ou intangível, oral, escrito, eletrônico ou visual, que sejam trocados entre as PARTES ou aos quais tenham acesso em decorrência desta relação contratual, e que não sejam de conhecimento público geral.</P>
      <P>9.3. A obrigação de confidencialidade aqui estabelecida não se aplicará àquelas informações que comprovadamente: já eram de domínio público no momento da divulgação; tornem-se de domínio público subsequentemente, desde que não por culpa ou violação contratual da PARTE Receptora; já eram legitimamente conhecidas pela PARTE Receptora antes de sua divulgação pela PARTE Reveladora, conforme evidenciado por registros preexistentes; sejam legitimamente recebidas de terceiros que não possuam obrigação de confidencialidade para com a PARTE Reveladora; ou cuja divulgação seja exigida por força de lei, regulamento ou ordem judicial ou administrativa de autoridade competente. Neste último caso, a PARTE obrigada a divulgar deverá, sempre que legalmente permitido, notificar previamente a PARTE Reveladora para que esta possa tomar as medidas que julgar cabíveis para proteger suas informações.</P>
      <P>9.4. A violação, por qualquer das PARTES, das obrigações de confidencialidade estipuladas nesta Cláusula sujeitará a PARTE infratora à obrigação de indenizar a outra PARTE por todas as perdas e danos, diretos e indiretos, incluindo danos emergentes e lucros cessantes, que forem efetivamente comprovados e que decorram diretamente da quebra do sigilo. A apuração do montante da indenização será realizada em procedimento judicial ou arbitral, sem prejuízo da possibilidade de a PARTE lesada buscar medidas de urgência para cessar a divulgação indevida.</P>
      <P>9.5. As obrigações de confidencialidade e sigilo estabelecidas neste instrumento sobreviverão ao término ou à rescisão do Contrato Master, por qualquer motivo que seja, e permanecerão em pleno vigor e efeito pelo período de 5 (cinco) anos, contados a partir da data de extinção do vínculo contratual, refletindo a natureza sensível e o valor estratégico das informações compartilhadas.</P>
      <P>9.6. Nenhuma das PARTES poderá fazer qualquer anúncio público, comunicado à imprensa ou divulgação de qualquer natureza sobre os termos específicos deste Contrato, ou sobre informações comerciais, técnicas, financeiras ou operacionais da outra PARTE, sem obter a autorização prévia, expressa e por escrito da outra PARTE, a qual não poderá ser injustificadamente negada em casos de necessidade de cumprimento de obrigações legais ou regulatórias de divulgação.</P>
      <P>9.7. Na hipótese de uma das PARTES compartilhar Informações Confidenciais com suas afiliadas, controladas, controladoras, ou com representantes e consultores, a PARTE que realizou o compartilhamento responderá de forma solidária por qualquer violação da obrigação de confidencialidade cometida por tais terceiros. A PARTE que divulga se compromete a garantir que todos os receptores das informações estejam cientes de seu caráter confidencial e vinculados, por obrigação contratual ou legal, a um dever de sigilo pelo menos tão rigoroso quanto o estabelecido neste Contrato.</P>
    </>
  );
}